# Python Programming Basics

In [2]:
a = "12"
integ_a = int(a)
print(type(a))                                                                                                       # Type function returns the data type of the argument.
print(f"\
    Type for {integ_a} is ... {type(integ_a)}\n\
    Type for {a} is ... {type(a)}")                                            # Both of the variables will print out as 12 but the data type is different from each other.

<class 'str'>
    Type for 12 is ... <class 'int'>
    Type for 12 is ... <class 'str'>

##### Conversion Operations

In [2]:
x = "24"
y = 88
z = 12.0

x_n = float(x)      # Conversion to "float" data type
y_n = str(y)        # Conversion to "string" data type
z_n = int(z)        # Conversion to "integer" data type

print(f"After the conversion,\n{x}'s data type is ... {type(x_n)}\n\
{y}'s data type is ... {type(y_n)}\n\
{z}'s data type is ... {type(z_n)}")

After the conversion,
24's data type is ... <class 'float'>
88's data type is ... <class 'str'>
12.0's data type is ... <class 'int'>

##### Escaping In a Variable

In [3]:
print("Ahmet's birthday")

print("\"Ahmet\" is here.")                                                                                             # \ symbol changes " character's purpose/definition

print("First row\nSecond row\nThird row")           # \n skips to the next row

print("far\taway")          # \t skips as much as "Tab" would skip.

print("One","Two","Three",sep="\t")         # We can use escapes with "sep" or "end".

import random
rand = random.choice("abcdefghijklmnopqrstwxyz")           # random.choice() module chooses a random element in the variable.
print(rand)

rand_r = random.randrange(1, 100)          # random.randrange() chooses a random item from range(start, stop[, step]).
print(rand_r)

Ahmet's birthday
"Ahmet" is here.
First row
Second row
Third row
far	away
One	Two	Three
s
27

##### Condition Dependent Situations

In [ ]:
a = input("a: ")
b = input("b: ")

if a==b:                                                                  # "if" keyword checks if the statement is true or false. If it's true, the operations will happen.
    print(f"{a} is equal to {b}.")

elif a > b:                                                                                        # "elif" keyword will be used when there is multiple conditions to check.
    print(f"{a} is greater than {b}.")

elif a < b:
    print(f"{a} is less than {b}.")

import math
import random

t = int(random.choice("0123456789"))
x = math.sin(t)
print(f"x: {x}")
y = math.cos(t)
print(f"y: {y}")

if x == y:
    print(f"sin({t}) is equal to cos({t}).")

else:                                                                                      # "else" keyword checks 'all' the other conditions which haven't been specified.
    print(f"sin({t}) is NOT equal to cos({t}).")

# cx_Freeze is a non-standart library which helps us to make an ".exe" file of the program we wrote.

##### Loops

In [ ]:
a = 0
while a < 100:                                                           # "while" keywords is used to make the program continue the loop as long as it meets the condition.
    a += 1          # a is increased by 1.
    print(a)

# # (?) Problem: Find a way to start a program if user presses "Enter".
# We can get the key with the module "getkey"
# (!) Couldn't download the getkey package!

for letter in "Ahmet":          # Every new iteration, the value of "letter" changes in to next value in the "sequence".
    print(letter,end="\t")

for num in "123456789":
    print(num)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
A	h	m	e	t	1
2
3
4
5
6
7
8
9

##### Project: _Sum of Numbers_

In [ ]:
sum = 0

for num in range(1,101):
    sum = sum + num
    print(sum)

1
3
6
10
15
21
28
36
45
55
66
78
91
105
120
136
153
171
190
210
231
253
276
300
325
351
378
406
435
465
496
528
561
595
630
666
703
741
780
820
861
903
946
990
1035
1081
1128
1176
1225
1275
1326
1378
1431
1485
1540
1596
1653
1711
1770
1830
1891
1953
2016
2080
2145
2211
2278
2346
2415
2485
2556
2628
2701
2775
2850
2926
3003
3081
3160
3240
3321
3403
3486
3570
3655
3741
3828
3916
4005
4095
4186
4278
4371
4465
4560
4656
4753
4851
4950
5050

##### "range( )" Function

In [6]:
print(*range(100))          # "*" operator slices off the range(100) value to its bits.

print("\nSame process:\n")

for i in range(100):            # Same process with the first line.
    print(i)

print("\n| | | Grading System | | |\n")

score = input("Score:\t")

if not score:           # (!!!) If there is "NO INPUT" from a user.
    print("Please enter a score to continue:\t")
    quit()
else:
    score = int(score)          # "str" converted to "int" to declare the grade with range().


if score not in range(101):         # If score is over 100.
    print("Score can't be over 100:\t")
    quit()                                                                                                                      # (***) quit() function exits the program.

elif score in range(90,101):
    grade = "AA"

elif score in range(85,90):
    grade = "BA"

elif score in range(80,85):                 # # GRADE CALCULATION # #
    grade = "BB"
 
# elif score in range(75,80):
    # grade: "CB"

elif score in range(70,75):
    grade = "CC"

elif score in range(60,70):
    grade = "DC"

elif score in range(50,60):
    grade = "DD"

else:
    grade = "FF"

print(f"Grade:\t{grade}")           # Printing the grade.

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99

Same process:

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

| | | Grading System | | |

Grade:	BA

##### "len( )" Function

In [8]:
# len() function returns the length of the given variable.
# It can only be used for data type "str".

Name = "Bilgehan"
print(len(Name))

password = input("Please enter a password: ")

if len(password) < 6:
    print("Password should be 6 characters or longer\n")
    password = input("Please enter a password:")

else:
    print(f"{password} is set as password.")

8
abs.9090 is set as password.

##### "break" Term

In [9]:
# "break" term is used to break out from a loop.

# while True:

    # username = input("Username: ")
    # password = input("Password: ")

    # if username == "Ahmet" and password == "8081":
        # print("Username and password are accepted!")
        # break           # break stops the operation.

    # else:
        # print("The username or the password is wrong. Please try again.")

##### "continue" Term

In [10]:
# "continue" is used to skip every part of the operation after it and returns to the beggining.

integer = "123090295043503453590904"
print(len(integer))         # 24
print(type(len(integer)))          # <class 'int'>

cnt = 0

for i in integer:
    cnt = cnt + 1           # Counting the loop to finish the code with "\n"
    
    if i == "0":
        continue
    else:
        print(i,end="")
        if cnt == len(integer):         # When all i is printed, finish the code with "\n".
            print(i,end="\n")

24
<class 'int'>
1239295435345359944

##### "in" Operator

In [11]:
# "in" operator is used to determine whether "variable" is in the list or not.

Name = "Ahmet Bilgehan SERÇE"

"z" in Name        # Is "z" character in the "Name" string?
    # Output : False

"a" in Name        # Is "a" character in the "Name" string?
    # Output : True

# while True:

    # ex_code = input("To exit, please type E/e: ")

    # if "e" in ex_code or "E" in ex_code:
        # print("You exit the program.")
        # quit()          # Exits the loop.

    # else:
        # print("You didn't exit the program.")
        # continue            # Returns to the beggining of the loop.

True

##### Project: _Number Guessing Game_

In [ ]:
import random

int_rand = random.randint(0,100)         # random number between 0 to 99

print("There is a number in my mind. Can you guess what number it is?\n")
print("Type\"Q\" to exit")

while True:         # Endless Loop
    guessUser = input("Your guess: ")
    print(type(guessUser))

    if guessUser == "Q":            # "Q" is for exit.
        print("Exitting the game...")
        break

    guessUser = int(guessUser)          # "str" to "int" conversion to compare.

    if guessUser == int_rand:            # Correct guess
        print("That's a correct guess!")
        break

    elif guessUser < integer:           # Lower guess
        print("It's higher.\n")

    else:           # Higher guess
        print("It's lower.\n")

##### Project: _Word Analysis_

In [14]:
word = input("Please enter a word: ")

word_length = len(word)         # length of the word.

letters =  ""

for letter in word:             # "letter" variable get's the value of each letter in "word" string with every loop.
    if letter not in letters:           #  (!!!) If there is multiple same letter, it's gonna be listed once.
        letters += letter


freq = ""           # frequency of the letters in the word.

for l in letters:           # The "l" variable is used to store how many times the letters in the variable "letters" occur in the variable "word".    (Ex.) word = "yazılım"
    #                                                                                                                                                       letters = "yazılm"
    i = 0           # Counter (i) is set to 0
    for w in word:          # "w" variable get's the value of all the letters in "word" string with every loop.
        if l == w:
            i += 1
    
    freq += f"\n\tThere is {i} \"{l}\" letter in \"{word}\". "

print(freq)

print("\n********************************************************************\n")

print(f"\t Word consists of {word_length} letters.")

print(f"\t\"{word}\" consists of the letters swohn below:\n")

print("\t",*letters,sep=",",end="\n")

	There is 2 "c" letter in "classical".
	There is 2 "l" letter in "classical".
	There is 2 "a" letter in "classical".
	There is 2 "s" letter in "classical".
	There is 1 "i" letter in "classical".

********************************************************************

	 Word consists of 9 letters.
	"classical" consists of the letters swohn below:

	,c,l,a,s,i

##### Project: _Average Grade Calculator_

In [16]:
num_student = int(input("Number of students: "))            # Number of Students
score_sum = 0            # Sum of the total score

for i in range(num_student):            # for every student
    score_sum += int(input(f"Student {i+1}'s score: "))         # N: range starts with 0, that's why we used {i+1} for listing the student's scores. (There is no 0. student)

avg = score_sum / num_student           # Average score for all students.

print(f"Average score for {i} students is \"{avg}\".")

Average score for 11 students is "57.083333333333336".

##### Data Types

In [27]:
# We can learn any data's data type with type() function

Name = "Ahmet"          # <class 'str'>
Age = 22            # <class 'int'>
Height = 180.0          # <class 'float'>
Married = False         # <class 'bool'>

# Example 1
print("\n* * * Example 1 * * *")
print(type(Name),type(Age),type(Height),type(Married),sep="\n")

# Example 2
print("\n* * * Example 2 * * *")

n = input("Please enter any number: ")
print(type(n),sep="")

m = int(n)
print(type(m))

* * * Example 1 * * *
<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

* * * Example 2 * * *
<class 'str'>
<class 'int'>

##### "help( )" Function

In [15]:
# When learning about a module, internet offers the wider variety of information. To get a quick information of a module, we use help() function.
print("* * * * PRINT() FUNCTION * * * *\n")
help(print)

import random
print("* * * * RANDOM MODULE * * * *\n")
help(random)

# dir() function is used to let the user see the contents of the module/function or any kind off directory.

print("* * * * WEBBROWSER MODULE * * * *\n")
import webbrowser
dir(webbrowser)

# in "webbrowser" module;
print("# webbrowser.open() Function\n")
help(webbrowser.open)

* * * * PRINT() FUNCTION * * * *

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.

* * * * RANDOM MODULE * * * *

Help on module random:

NAME
    random - Random variable generators.

MODULE REFERENCE
    https://docs.python.org/3.10/library/random.html

    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
        bytes
        -----
               uniform bytes (values between 0 and 255)

        integers
        --------
               uniform within range

        sequences
        ---------
               pick random element
               pick random sample
               pick weighted random sample
               generate random permutation

        distributions on the real line:
        ------------------------------
               uniform
               triangular
               normal (Gaussian)
               lognormal
               negative exponential
               gamma
               beta
               pareto
               Weibull

        distributions on the circle (angles 0 to 2pi)
        ---------------------------------------------
               circular uniform
               von Mises

    General notes on the underlying Mersenne Twister core generator:

    * The period is 2**19937-1.
    * It is one of the most extensively tested generators in existence.
    * The random() method is implemented in C, executes in a single Python step,
      and is, therefore, threadsafe.

CLASSES
    _random.Random(builtins.object)
        Random
            SystemRandom

    class Random(_random.Random)
     |  Random(x=None)
     |
     |  Random number generator base class used by bound module functions.
     |
     |  Used to instantiate instances of Random to get generators that don't
     |  share state.
     |
     |  Class Random can also be subclassed if you want to use a different basic
     |  generator of your own devising: in that case, override the following
     |  methods:  random(), seed(), getstate(), and setstate().
     |  Optionally, implement a getrandbits() method so that randrange()
     |  can cover arbitrarily large ranges.
     |
     |  Method resolution order:
     |      Random
     |      _random.Random
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __getstate__(self)
     |      # Issue 17489: Since __reduce__ was defined to fix #759889 this is no
     |      # longer called; we leave it here because it has been here since random was
     |      # rewritten back in 2001 and why risk breaking something.
     |
     |  __init__(self, x=None)
     |      Initialize an instance.
     |
     |      Optional argument x controls seeding, as for Random.seed().
     |
     |  __reduce__(self)
     |      Helper for pickle.
     |
     |  __setstate__(self, state)
     |
     |  betavariate(self, alpha, beta)
     |      Beta distribution.
     |
     |      Conditions on the parameters are alpha > 0 and beta > 0.
     |      Returned values range between 0 and 1.
     |
     |  choice(self, seq)
     |      Choose a random element from a non-empty sequence.
     |
     |  choices(self, population, weights=None, *, cum_weights=None, k=1)
     |      Return a k sized list of population elements chosen with replacement.
     |
     |      If the relative weights or cumulative weights are not specified,
     |      the selections are made with equal probability.
     |
     |  expovariate(self, lambd)
     |      Exponential distribution.
     |
     |      lambd is 1.0 divided by the desired mean.  It should be
     |      nonzero.  (The parameter would be called "lambda", but that is
     |      a reserved word in Python.)  Returned values range from 0 to
     |      positive infinity if lambd is positive, and from negative
     |      infinity to 0 if lambd is negative.
     |
     |  gammavariate(self, alpha, beta)
     |      Gamma distribution.  Not the gamma function!
     |
     |      Conditions on the parameters are alpha > 0 and beta > 0.
     |
     |      The probability distribution function is:
     |
     |                  x ** (alpha - 1) * math.exp(-x / beta)
     |        pdf(x) =  --------------------------------------
     |                    math.gamma(alpha) * beta ** alpha
     |
     |  gauss(self, mu, sigma)
     |      Gaussian distribution.
     |
     |      mu is the mean, and sigma is the standard deviation.  This is
     |      slightly faster than the normalvariate() function.
     |
     |      Not thread-safe without a lock around calls.
     |
     |  getstate(self)
     |      Return internal state; can be passed to setstate() later.
     |
     |  lognormvariate(self, mu, sigma)
     |      Log normal distribution.
     |
     |      If you take the natural logarithm of this distribution, you'll get a
     |      normal distribution with mean mu and standard deviation sigma.
     |      mu can have any value, and sigma must be greater than zero.
     |
     |  normalvariate(self, mu, sigma)
     |      Normal distribution.
     |
     |      mu is the mean, and sigma is the standard deviation.
     |
     |  paretovariate(self, alpha)
     |      Pareto distribution.  alpha is the shape parameter.
     |
     |  randbytes(self, n)
     |      Generate n random bytes.
     |
     |  randint(self, a, b)
     |      Return random integer in range [a, b], including both end points.
     |
     |  randrange(self, start, stop=None, step=1)
     |      Choose a random item from range(start, stop[, step]).
     |
     |      This fixes the problem with randint() which includes the
     |      endpoint; in Python this is usually not what you want.
     |
     |  sample(self, population, k, *, counts=None)
     |      Chooses k unique random elements from a population sequence or set.
     |
     |      Returns a new list containing elements from the population while
     |      leaving the original population unchanged.  The resulting list is
     |      in selection order so that all sub-slices will also be valid random
     |      samples.  This allows raffle winners (the sample) to be partitioned
     |      into grand prize and second place winners (the subslices).
     |
     |      Members of the population need not be hashable or unique.  If the
     |      population contains repeats, then each occurrence is a possible
     |      selection in the sample.
     |
     |      Repeated elements can be specified one at a time or with the optional
     |      counts parameter.  For example:
     |
     |          sample(['red', 'blue'], counts=[4, 2], k=5)
     |
     |      is equivalent to:
     |
     |          sample(['red', 'red', 'red', 'red', 'blue', 'blue'], k=5)
     |
     |      To choose a sample from a range of integers, use range() for the
     |      population argument.  This is especially fast and space efficient
     |      for sampling from a large population:
     |
     |          sample(range(10000000), 60)
     |
     |  seed(self, a=None, version=2)
     |      Initialize internal state from a seed.
     |
     |      The only supported seed types are None, int, float,
     |      str, bytes, and bytearray.
     |
     |      None or no argument seeds from current time or from an operating
     |      system specific randomness source if available.
     |
     |      If *a* is an int, all bits are used.
     |
     |      For version 2 (the default), all of the bits are used if *a* is a str,
     |      bytes, or bytearray.  For version 1 (provided for reproducing random
     |      sequences from older versions of Python), the algorithm for str and
     |      bytes generates a narrower range of seeds.
     |
     |  setstate(self, state)
     |      Restore internal state from object returned by getstate().
     |
     |  shuffle(self, x, random=None)
     |      Shuffle list x in place, and return None.
     |
     |      Optional argument random is a 0-argument function returning a
     |      random float in [0.0, 1.0); if it is the default None, the
     |      standard random.random will be used.
     |
     |  triangular(self, low=0.0, high=1.0, mode=None)
     |      Triangular distribution.
     |
     |      Continuous distribution bounded by given lower and upper limits,
     |      and having a given mode value in-between.
     |
     |      http://en.wikipedia.org/wiki/Triangular_distribution
     |
     |  uniform(self, a, b)
     |      Get a random number in the range [a, b) or [a, b] depending on rounding.
     |
     |  vonmisesvariate(self, mu, kappa)
     |      Circular data distribution.
     |
     |      mu is the mean angle, expressed in radians between 0 and 2*pi, and
     |      kappa is the concentration parameter, which must be greater than or
     |      equal to zero.  If kappa is equal to zero, this distribution reduces
     |      to a uniform random angle over the range 0 to 2*pi.
     |
     |  weibullvariate(self, alpha, beta)
     |      Weibull distribution.
     |
     |      alpha is the scale parameter and beta is the shape parameter.
     |
     |  ----------------------------------------------------------------------
     |  Class methods defined here:
     |
     |  __init_subclass__(**kwargs) from builtins.type
     |      Control how subclasses generate random integers.
     |
     |      The algorithm a subclass can use depends on the random() and/or
     |      getrandbits() implementation available to it and determines
     |      whether it can generate random integers from arbitrarily large
     |      ranges.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  VERSION = 3
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from _random.Random:
     |
     |  getrandbits(self, k, /)
     |      getrandbits(k) -> x.  Generates an int with k random bits.
     |
     |  random(self, /)
     |      random() -> x in the interval [0, 1).
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from _random.Random:
     |
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.

    class SystemRandom(Random)
     |  SystemRandom(x=None)
     |
     |  Alternate random number generator using sources provided
     |  by the operating system (such as /dev/urandom on Unix or
     |  CryptGenRandom on Windows).
     |
     |   Not available on all systems (see os.urandom() for details).
     |
     |  Method resolution order:
     |      SystemRandom
     |      Random
     |      _random.Random
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  getrandbits(self, k)
     |      getrandbits(k) -> x.  Generates an int with k random bits.
     |
     |  getstate = _notimplemented(self, *args, **kwds)
     |
     |  randbytes(self, n)
     |      Generate n random bytes.
     |
     |  random(self)
     |      Get the next random number in the range [0.0, 1.0).
     |
     |  seed(self, *args, **kwds)
     |      Stub method.  Not used for a system random number generator.
     |
     |  setstate = _notimplemented(self, *args, **kwds)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from Random:
     |
     |  __getstate__(self)
     |      # Issue 17489: Since __reduce__ was defined to fix #759889 this is no
     |      # longer called; we leave it here because it has been here since random was
     |      # rewritten back in 2001 and why risk breaking something.
     |
     |  __init__(self, x=None)
     |      Initialize an instance.
     |
     |      Optional argument x controls seeding, as for Random.seed().
     |
     |  __reduce__(self)
     |      Helper for pickle.
     |
     |  __setstate__(self, state)
     |
     |  betavariate(self, alpha, beta)
     |      Beta distribution.
     |
     |      Conditions on the parameters are alpha > 0 and beta > 0.
     |      Returned values range between 0 and 1.
     |
     |  choice(self, seq)
     |      Choose a random element from a non-empty sequence.
     |
     |  choices(self, population, weights=None, *, cum_weights=None, k=1)
     |      Return a k sized list of population elements chosen with replacement.
     |
     |      If the relative weights or cumulative weights are not specified,
     |      the selections are made with equal probability.
     |
     |  expovariate(self, lambd)
     |      Exponential distribution.
     |
     |      lambd is 1.0 divided by the desired mean.  It should be
     |      nonzero.  (The parameter would be called "lambda", but that is
     |      a reserved word in Python.)  Returned values range from 0 to
     |      positive infinity if lambd is positive, and from negative
     |      infinity to 0 if lambd is negative.
     |
     |  gammavariate(self, alpha, beta)
     |      Gamma distribution.  Not the gamma function!
     |
     |      Conditions on the parameters are alpha > 0 and beta > 0.
     |
     |      The probability distribution function is:
     |
     |                  x ** (alpha - 1) * math.exp(-x / beta)
     |        pdf(x) =  --------------------------------------
     |                    math.gamma(alpha) * beta ** alpha
     |
     |  gauss(self, mu, sigma)
     |      Gaussian distribution.
     |
     |      mu is the mean, and sigma is the standard deviation.  This is
     |      slightly faster than the normalvariate() function.
     |
     |      Not thread-safe without a lock around calls.
     |
     |  lognormvariate(self, mu, sigma)
     |      Log normal distribution.
     |
     |      If you take the natural logarithm of this distribution, you'll get a
     |      normal distribution with mean mu and standard deviation sigma.
     |      mu can have any value, and sigma must be greater than zero.
     |
     |  normalvariate(self, mu, sigma)
     |      Normal distribution.
     |
     |      mu is the mean, and sigma is the standard deviation.
     |
     |  paretovariate(self, alpha)
     |      Pareto distribution.  alpha is the shape parameter.
     |
     |  randint(self, a, b)
     |      Return random integer in range [a, b], including both end points.
     |
     |  randrange(self, start, stop=None, step=1)
     |      Choose a random item from range(start, stop[, step]).
     |
     |      This fixes the problem with randint() which includes the
     |      endpoint; in Python this is usually not what you want.
     |
     |  sample(self, population, k, *, counts=None)
     |      Chooses k unique random elements from a population sequence or set.
     |
     |      Returns a new list containing elements from the population while
     |      leaving the original population unchanged.  The resulting list is
     |      in selection order so that all sub-slices will also be valid random
     |      samples.  This allows raffle winners (the sample) to be partitioned
     |      into grand prize and second place winners (the subslices).
     |
     |      Members of the population need not be hashable or unique.  If the
     |      population contains repeats, then each occurrence is a possible
     |      selection in the sample.
     |
     |      Repeated elements can be specified one at a time or with the optional
     |      counts parameter.  For example:
     |
     |          sample(['red', 'blue'], counts=[4, 2], k=5)
     |
     |      is equivalent to:
     |
     |          sample(['red', 'red', 'red', 'red', 'blue', 'blue'], k=5)
     |
     |      To choose a sample from a range of integers, use range() for the
     |      population argument.  This is especially fast and space efficient
     |      for sampling from a large population:
     |
     |          sample(range(10000000), 60)
     |
     |  shuffle(self, x, random=None)
     |      Shuffle list x in place, and return None.
     |
     |      Optional argument random is a 0-argument function returning a
     |      random float in [0.0, 1.0); if it is the default None, the
     |      standard random.random will be used.
     |
     |  triangular(self, low=0.0, high=1.0, mode=None)
     |      Triangular distribution.
     |
     |      Continuous distribution bounded by given lower and upper limits,
     |      and having a given mode value in-between.
     |
     |      http://en.wikipedia.org/wiki/Triangular_distribution
     |
     |  uniform(self, a, b)
     |      Get a random number in the range [a, b) or [a, b] depending on rounding.
     |
     |  vonmisesvariate(self, mu, kappa)
     |      Circular data distribution.
     |
     |      mu is the mean angle, expressed in radians between 0 and 2*pi, and
     |      kappa is the concentration parameter, which must be greater than or
     |      equal to zero.  If kappa is equal to zero, this distribution reduces
     |      to a uniform random angle over the range 0 to 2*pi.
     |
     |  weibullvariate(self, alpha, beta)
     |      Weibull distribution.
     |
     |      alpha is the scale parameter and beta is the shape parameter.
     |
     |  ----------------------------------------------------------------------
     |  Class methods inherited from Random:
     |
     |  __init_subclass__(**kwargs) from builtins.type
     |      Control how subclasses generate random integers.
     |
     |      The algorithm a subclass can use depends on the random() and/or
     |      getrandbits() implementation available to it and determines
     |      whether it can generate random integers from arbitrarily large
     |      ranges.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from Random:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from Random:
     |
     |  VERSION = 3
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from _random.Random:
     |
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.

FUNCTIONS
    betavariate(alpha, beta) method of Random instance
        Beta distribution.

        Conditions on the parameters are alpha > 0 and beta > 0.
        Returned values range between 0 and 1.

    choice(seq) method of Random instance
        Choose a random element from a non-empty sequence.

    choices(population, weights=None, *, cum_weights=None, k=1) method of Random instance

##### Lists

In [18]:
# List of datas are called "lists". Lists are defined with square brackets ( [ data0 , data1, data2, data3, ... ] ).

urls = ["google","youtube","reddit","instagram"]
urls

# Lists can be consist of different data types.

lists = ["Ahmet","Bilgehan","SERÇE",22,False]

# List can be consist of another list/listes.

matrix = [[1,2,3], [4,5,6], [7,8,9]]

# len() function can be used to know the list's length

len(urls)
len(lists)
len(matrix)

print("\t\tExample\t\t")

import webbrowser

for u in urls:
    webbrowser.open(f"www.{u}.com")         # for every url, open in  web.

		Example

##### Methods for Lists

In [8]:
dir(list)           # dir([])

# In the output, the keywords which doesn't have any "_" before them are especially important.

print("*Important Features\n")

for m in dir(list):                                                                                                 # (!!!) STUDY "FOR" LOOPS!
    if "_" not in m:
        print(m)

*Important Features

append
clear
copy
count
extend
index
insert
pop
remove
reverse
sort

##### "append( )" Method

In [28]:
# append() is used to add a new data to a list.

kripto = ["bitcoin","etherium","litecoin"]
print(kripto)
kripto.append("ripple")         # "ripple" data is added to the "kripto" list. (to the end)

print(kripto)

# "for" loop can be used to add multiple data.

kripto_owned = ["cardano","stellar","chainlink"]

for i in kripto_owned:
    kripto.append(i)

print(kripto)

# List of Students 
print("\n * * * * List of Students * * * * \n")
print("Student's Name and Surname ")
print("\nType \"Q\" to finish.\n")

stud = []           # Student list (empty)
count = 0           # Student Population

while True:
    count += 1
    student = input(f"Student {count}: ")

    if (student == "q" and not stud) or (student == "Q" and not stud):          # To stop the program anytime. This line means if the user presses "q" or "Q", they
    #                                                                           # can exit without inputting anything.
        break
    elif (student == "q" and stud) or (student == "Q" and stud):                # To stop the program after inputting every student, user can press "q" or "Q" to exit.
        print("\n----------- Student List is created. -----------\n")
    
        for s in stud:          # Every student's name get's printed.
            print(s)
    
        print("Student Population: ",len(stud))         # Number of student's in the list is printed.
        break

    else:
        stud.append(student)            # User can add a new student to the list under "else" keyword.

['bitcoin', 'etherium', 'litecoin']
['bitcoin', 'etherium', 'litecoin', 'ripple']
['bitcoin', 'etherium', 'litecoin', 'ripple', 'cardano', 'stellar', 'chainlink']

 * * * * List of Students * * * *

Student's Name and Surname

Type "Q" to finish.


----------- Student List is created. -----------

Ahmet Bilgehan SERÇE
Feyzanur Betül SERÇE
Kemal SERÇE
Asuman SERÇE
Student Population:  4

##### "extend( )" Method

In [23]:
list1 = ["door","window","house","garden"]
list2 = ["table","chair","sofa","television"]

# To add these two list together, we can use "for" loop.

for item in list1:          # Every data in "list1" defined as "item" in order.
    list2.append(item)          # "item" data has been added to "list2".
    print(f"\"{item}\" is added.",list2,sep="\t")

# To do the exact operation with a more practical way, we cna use extend to add a list to another list.

list3 = ["Python","Maachine","AI","Data","Neural Network"]
print(f"\nlist3 = {list3}")
list4 = ["MatLab","Deep Learning","Machine Learning"]
print(f"list4 = {list4}")
list3.extend(list4)         # Data in "list4" has been added to "list3" with extend() method.
print("New list3: ",list3)            # New "list3".

# Two list can be added with simply "+" operator as well.

print("\n >> Two lists can be appended into each other with simply \"+\" operator as well.")
list3 = ["Python","Maachine","AI","Data","Neural Network"]
print(f"\nlist3 = {list3}")

list4 = ["MatLab","Deep Learning","Machine Learning"]
print(f"list4 = {list4}")

list_new = list3 + list4
print("New list: ",list_new)            # New list (list3 + list4).

# (!) In this method, you need to create another list that consists of "list3" and "list4".

"door" is added.	['table', 'chair', 'sofa', 'television', 'door']
"window" is added.	['table', 'chair', 'sofa', 'television', 'door', 'window']
"house" is added.	['table', 'chair', 'sofa', 'television', 'door', 'window', 'house']
"garden" is added.	['table', 'chair', 'sofa', 'television', 'door', 'window', 'house', 'garden']

list3 = ['Python', 'Maachine', 'AI', 'Data', 'Neural Network']
list4 = ['MatLab', 'Deep Learning', 'Machine Learning']
New list3:  ['Python', 'Maachine', 'AI', 'Data', 'Neural Network', 'MatLab', 'Deep Learning', 'Machine Learning']

 >> Two lists can be appended into each other with simply "+" operator as well.

list3 = ['Python', 'Maachine', 'AI', 'Data', 'Neural Network']
list4 = ['MatLab', 'Deep Learning', 'Machine Learning']
New list:  ['Python', 'Maachine', 'AI', 'Data', 'Neural Network', 'MatLab', 'Deep Learning', 'Machine Learning']

##### "insert( )" Method

In [9]:
# With this method, we can add an element to a list while being able to choose the location of it.

listA = ["Zero","One","Two","Three"]            # ( ! ! ) Lists start with "data0"!
print(f"{listA = }")
listA.insert(0,"Insert!")
print(f"{listA = }")            # New 0th element is "Insert!".

listA.insert(3,"Insert!")
print(f"{listA = }")            # New 3rd element is "Insert!".

listA = ['Zero', 'One', 'Two', 'Three']
listA = ['Insert!', 'Zero', 'One', 'Two', 'Three']
listA = ['Insert!', 'Zero', 'One', 'Insert!', 'Two', 'Three']

##### "remove( )" Method

In [30]:
# With this method, we can remove any element from any list.

listOfNames = ["Ahmet","Mehmet","Kemal","Asuman","Feyzanur","jdtjoad8y6*"]
print(f"{listOfNames = }")

listOfNames.remove("jdtjoad8y6*")
print(f"{listOfNames = }")

listOfNames = ['Ahmet', 'Mehmet', 'Kemal', 'Asuman', 'Feyzanur', 'jdtjoad8y6*']
listOfNames = ['Ahmet', 'Mehmet', 'Kemal', 'Asuman', 'Feyzanur']

##### "pop( )" Method

In [33]:
# With this method, we can remove an element from a list and print it to see which element is removed.

listOfNames = ["Ahmet","Mehmet","Kemal","Asuman","Feyzanur","jdtjoad8y6*"]
print(f"{listOfNames = }")

listOfNames.pop(5)          # 5 = Index of an element.

listOfNames = ['Ahmet', 'Mehmet', 'Kemal', 'Asuman', 'Feyzanur', 'jdtjoad8y6*']

'jdtjoad8y6*'

##### "index( )" Method

In [37]:
# With this method, we can learn any element's index in a list.

listOfNames = ["Ahmet","Mehmet","Kemal","Asuman","Feyzanur","jdtjoad8y6*"]
print(f"{listOfNames = }")

listOfNames.index("Ahmet")

listOfNames = ['Ahmet', 'Mehmet', 'Kemal', 'Asuman', 'Feyzanur', 'jdtjoad8y6*']

0

##### "sort( )" Method

In [47]:
# With this method, we can sort the elements in "alphabetic order".

listOfNames = ["Ahmet","Mehmet","Kemal","Asuman","Feyzanur","jdtjoad8y6*"]
print(f"{listOfNames = }")
listOfNames.remove("jdtjoad8y6*")

listOfNames.sort()
print(f"Sorted {listOfNames = }")

# sort() can be used to sort out numerical values as well (lower to higher).

listNum = [1, 0, -1, 4, 10, 3, 6]
print(f"\n{listNum = }")
listNum.sort()
print(f"Sorted {listNum = }")

# To sort in a different way, we can set "reverse" option to "True" (higher to lower).

listNum.sort(reverse=True)
print(f"Re-sorted {listNum = }")

listOfNames = ['Ahmet', 'Mehmet', 'Kemal', 'Asuman', 'Feyzanur', 'jdtjoad8y6*']
Sorted listOfNames = ['Ahmet', 'Asuman', 'Feyzanur', 'Kemal', 'Mehmet']

listNum = [1, 0, -1, 4, 10, 3, 6]
Sorted listNum = [-1, 0, 1, 3, 4, 6, 10]
Re-sorted listNum = [10, 6, 4, 3, 1, 0, -1]

##### "reverse( )" Method

In [52]:
# With this method, we can reverse indexes of all the elements.

listOfNames = ["Ahmet","Mehmet","Kemal","Asuman","Feyzanur","jdtjoad8y6*"]
print(f"{listOfNames = }")
listOfNames.remove("jdtjoad8y6*")

listOfNames.sort()
print(f"\nSorted {listOfNames = }")
print("\"Ahmet\" element's index = ",listOfNames.index("Ahmet"))

listOfNames.reverse()
print(f"\nReversed and sorted {listOfNames = }")
print("\"Ahmet\" element's index = ",listOfNames.index("Ahmet"))

listOfNames = ['Ahmet', 'Mehmet', 'Kemal', 'Asuman', 'Feyzanur', 'jdtjoad8y6*']

Sorted listOfNames = ['Ahmet', 'Asuman', 'Feyzanur', 'Kemal', 'Mehmet']
"Ahmet" element's index =  0

Reversed and sorted listOfNames = ['Mehmet', 'Kemal', 'Feyzanur', 'Asuman', 'Ahmet']
"Ahmet" element's index =  4

##### "count( )" Method

In [1]:
# With this method, we can learn if there is any elements that repeats.

Char = ["a","b","a","a","b","c","d","c","c","c","d","f"]
print(f"{Char = }",end="\n")

print(f"\"a\" repeats ",Char.count("a")," times.",end="\n")
print(f"\"b\" repeats ",Char.count("b")," times.",end="\n")
print(f"\"c\" repeats ",Char.count("c")," times.",end="\n")
print(f"\"d\" repeats ",Char.count("d")," times.",end="\n")
print(f"\"e\" repeats ",Char.count("e")," times.",end="\n")         # There is no "e" element.
print(f"\"f\" repeats ",Char.count("f")," times.",end="\n")

# We can do "almost the same process" with "for" loop (P R A C T İ C E). 

print("\n>> Alternative way:\n")
print(f"{Char = }",end="\n")
listOfChar = []

for c in Char:
    if c not in listOfChar:
        listOfChar.append(c)
    else:
        continue

for reChar in listOfChar:
    print(f"\"{reChar}\" repeats ",Char.count(reChar)," times.",end="\n")

# In alternative way, we can't check the non-existed elements.

Char = ['a', 'b', 'a', 'a', 'b', 'c', 'd', 'c', 'c', 'c', 'd', 'f']
"a" repeats  3  times.
"b" repeats  2  times.
"c" repeats  4  times.
"d" repeats  2  times.
"e" repeats  0  times.
"f" repeats  1  times.

>> Alternative way:

Char = ['a', 'b', 'a', 'a', 'b', 'c', 'd', 'c', 'c', 'c', 'd', 'f']
"a" repeats  3  times.
"b" repeats  2  times.
"c" repeats  4  times.
"d" repeats  2  times.
"f" repeats  1  times.

##### Slicing the Lists

In [8]:
listA = ["Ahmet","Mehmet","Asuman","Feyzanur","Kemal"]

Name = listA[0]
print(Name)

lastA = listA[-1]           # Last element of the "listA"
print(lastA)

lastA = listA[len(listA) - 1]         # We can select the last element with the help of "len()"" function as well.
print(lastA)

secLast = listA[len(listA) - 2]
print(secLast)

# ( ! ) We can imagine the list as;
# ... , "Ahmet" , "Mehmet" , "Asuman" , "Feyzanur" , "Kemal" , "Ahmet" , "Mehmet" , "Asuman" , "Feyzanur" , "Kemal", ...
#        ( -5 )    (- 4 )     ( -3 )      ( -2 )      ( -1 )    ( 0 )      ( 1 )     ( 2 )        ( 3 )      ( 4 )

print(">> Slicing lists with the definiton of start, stop and step")
listRange = range(100)
print(*listRange,sep=",")
listSeconds = listRange[0:100:2]            # from 0 to 100 with 2 steps.
print("New list is:")
print(*listSeconds,sep=",")

# Same process can be done with len() function.

print("\n>> Same process with \"len()\" function")
listRange = range(100)
print(*listRange,sep=",")
listSeconds = listRange[0:len(listRange):2]            # from 0 to 100 with 2 steps.
print("New list is:")
print(*listSeconds,sep=",")

# To reverse the list in arrangement

listRev = listRange[::-1]           # or listRev = listRange.reverse()
print("Reversed list is:")
print(*listRev,sep=",")

# With the slicing method, we can replace or change the existing elements in a list.

listFr = ["Apple","Stone","Peach","Banana","Orange"]
listFr[1] = "Apricot"           # Removed "Stone" and added "Apricot"
print(f"\n{listFr}")

# We can add new elements to a list with slicing method.

listFr = ["Apple","Peach","Banana","Orange"]
listFr[len(listFr):] = ["Cherry","Strawberry"]          # len(listFr) represent the last element of the list.
print(f"\nNew list is (\"Cherry\" and \"Strawberry\" is added.):\n{listFr}")

# We can remove an element and add multiple elements to it's place.

listFr = ["Apple","Stone","Peach","Banana","Orange"]
listFr[2] = ["Cherry","Strawberry"]
print(f"\nNew list is (\"Stone\" removed):\n{listFr}")

Ahmet
Kemal
Kemal
Feyzanur
>> Slicing lists with the definiton of start, stop and step
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99
New list is:
0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98

>> Same process with "len()" function
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99
New list is:
0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98
Reversed list is:
99,98,97,96,95,94,93,92,91,90,89,88,87,86,85,84,83,82,81,80,79,78,77,76,75,74,73,72,71,70,69,68,67,66,65,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0

['Apple', 'Apricot', 'Peach', 'Banana', 'Orange']

New list is ("Cherry" and "Strawberry" is added.):
['Apple', 'Peach', 'Banana', 'Orange', 'Cherry', 'Strawberry']

New list is ("Stone" removed):
['Apple', 'Stone', ['Cherry', 'Strawberry'], 'Banana', 'Orange']

##### Nested Lists

In [10]:
# When there is a list inside an another list, the list which has a list inside called "nested list".

matrix = [[1,2,3], [4,5,6], [7,8,9]]
one = matrix[0][0]      # one = matrix[0][0]    >>     matrix[0] = [1,2,3] from this list, matrix[0][0] = "1"
four = matrix[1][0]     # 0nd element of "matrix[1]".
# ...
nine = matrix[2][2]     # 2nd element of "matrix[2]".

print(f"First element of the nested list is {matrix[0]}, first element of it is {one}.")
print(f"Second element of the nested list is {matrix[1]}, first element of it is {four}.")
print(f"Third element of the nested list is {matrix[2]}, last element of it is {nine}.")

First element of the nested list is [1, 2, 3], first element of it is 1.
Second element of the nested list is [4, 5, 6], first element of it is 4.
Third element of the nested list is [7, 8, 9], last element of it is 9.

##### "list( )" Function

In [23]:
# With this function, we can convert a data type from anything to a list.

ran = range(0,11)
print(f"Our variable:  {ran}")
print(f"Data type: {type(ran)}")

ran_l = list(ran)
print(f"\nOur variable after \"list()\" function:  {ran_l}")
print(f"Data type: {type(ran_l)}")

Our variable:  range(0, 11)
Data type: <class 'range'>

Our variable after "list()" function:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Data type: <class 'list'>

##### Tuples

In [33]:
# Tuples are very similar to lists except tuples "can't be changed".

import platform
print(f"Python version: {platform.python_version()}")
print(f"Data type: {type(platform.python_version())}")

print(f"\nPython version as a tuple: {platform.python_version_tuple()}\t")
print(f"Data type: {type(platform.python_version_tuple())}")

# When defining a tuple, we use parantheses. We don't need to use parantheses, we can define a tuple with just commas (,) as well.

tupleA = ("Ahmet","Bilgehan","Serçe",22,False)
print(f"\ntupleA data type: {type(tupleA)}")

tupleB = "Mehmet","Oğuzhan","Serçe",22,False
print(f"tupleB data type: {type(tupleB)}")

# Both "tupleA" and "tupleB" data types are <class 'tuple'>.

# To create an "empty" tuple, we leave it blank.

emptyTuple = ()

# To create a tuple with a single element, we need to use a comma after the element. If we don't, it will be registered as <class 'str'>.

singleTuple = ("one",)          # Data type is registered as <class 'tuple'>
print(f"\nData type is {type(singleTuple)}")

notSingleTuple = ("one")         # ( ! ) Data type is registered as <class 'str'>
print(f"Data type is {type(notSingleTuple)}")

# We use tuples to protect the data from any changes. Tuples are faster to use and program with than lists.
# Because tuples are very similar to lists, we can do almost every operation to tuples that we can do to lists.

tupleA = ("Ahmet","Bilgehan","Serçe",22,False)
print(len(tupleA))         # len() Function

NameTuple = tupleA[0:3]          # Slicing Method
print(f"\n{NameTuple}")
print(type(NameTuple))

NameStr = str(NameTuple)            # Conversion
print(f"\n{NameStr}")
print(type(NameStr))

matrixTuple = ((1,2,3),(4,5,6),(7,8,9))         # Nested tuples

firstTuple = matrixTuple[0]
secondTuple = matrixTuple[1]
thirdTuple = matrixTuple[2]

one = matrixTuple[0][0]     # First element of the first tuple.
two = matrixTuple[0][1]     # Second element of the first tuple.
four = matrixTuple[1][0]        # First element of the second tuple.
nine = matrixTuple[2][2]        # Third element of the third tuple.

print(f"\nDefined elements:\n{one = }\n{two = }\n{four = }\n{nine = }")

Python version: 3.10.1
Data type: <class 'str'>

Python version as a tuple: ('3', '10', '1')
Data type: <class 'tuple'>

tupleA data type: <class 'tuple'>
tupleB data type: <class 'tuple'>

Data type is <class 'tuple'>
Data type is <class 'str'>
5

('Ahmet', 'Bilgehan', 'Serçe')
<class 'tuple'>

('Ahmet', 'Bilgehan', 'Serçe')
<class 'str'>

Defined elements:
one = 1
two = 2
four = 4
nine = 9

##### Tuple Methods

In [41]:
dir(tuple)      # We can also use dir(()).
print(f"{dir(())}\n")

for method in dir(tuple):
    if "_" not in method:
        print(method)

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']

count
index

##### "count( )" Function

In [49]:
# We can use "count()" to learn how many times an element repeats.

tupleRep = (0,1,1,1,2,2,3,5,5,5,5,5)

print(f"There is {tupleRep.count(0)} of \"{tupleRep[0]}\".")
print(f"There is {tupleRep.count(1)} of \"{tupleRep[1]}\".")
print(f"There is {tupleRep.count(2)} of \"{tupleRep[4]}\".")
print(f"There is {tupleRep.count(3)} of \"{tupleRep[6]}\".")
print(f"There is {tupleRep.count(4)} of \"4\".")
print(f"There is {tupleRep.count(3)} of \"{tupleRep[7]}\".")

There is 1 of "0".
There is 3 of "1".
There is 2 of "2".
There is 1 of "3".
There is 0 of "4".
There is 1 of "5".

##### "index( )" Method

In [52]:
# We can use "index()" to determine the index of an element.

tupleA = ("Ahmet","Bilgehan","Serçe",22,False)
print(tupleA.index("Ahmet"))
print(tupleA.index(22))
print(tupleA.index(False))

0
3
4

##### "tuple( )" Function

In [56]:
# We can convert any data type to "tuple" data type.

ran = range(0,11)
print(f"{ran = }\twith a data type of\t{type(ran)}")
ranTuple = tuple(ran)           # Conversion from   <class 'range'>   to   <class 'tuple'>
print(f"{ranTuple = }\twith a data type of\t{type(ranTuple)}")

ran = range(0, 11)	with a data type of	<class 'range'>
ranTuple = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)	with a data type of	<class 'tuple'>

##### Dictionaries

In [13]:
# Dictionaries consists of 2 type of elements: 
# 1. Key
# 2. Key Value

dictA = {"Ahmet": "0551 415 80 81","Kemal": "0535 245 41 83", "Asuman": "0507 101 62 71"}
print(type(dictA))

# In the example;   "Ahmet", "Kemal" and "Asuman" are defined as "keys".
#                   "0551 415 80 81", "0535 245 41 83" and "0507 101 62 71" are defined as "key values".

print(dictA["Ahmet"])          # Prints the key value of "Ahmet".

# To add a new key and it's value to a dictionary ve can use the same method.

dictA["Feyzanur"] = "0507 101 62 61"
print(f"New {dictA = }")

# To delete any key and it's value, we can use "del" operator.

del dictA["Ahmet"]
print(f"New {dictA = }")

<class 'dict'>
0551 415 80 81
New dictA = {'Ahmet': '0551 415 80 81', 'Kemal': '0535 245 41 83', 'Asuman': '0507 101 62 71', 'Feyzanur': '0507 101 62 61'}
New dictA = {'Kemal': '0535 245 41 83', 'Asuman': '0507 101 62 71', 'Feyzanur': '0507 101 62 61'}

##### Dictionary Methods

In [8]:
dir(dict)

for d in dir(dict):         # The functions which is embedded in "dict" directory.
    if "_" not in d:
        print(d)

clear
copy
fromkeys
get
items
keys
pop
popitem
setdefault
update
values

##### "keys( )" Method

In [14]:
# We can use "keys()" to get every key in a dictionary.

dictB = {"Apple": "Fruit",21: "Number",False: "Statement"}
dictB.keys()

dict_keys(['Apple', 21, False])

##### "values( )" Method

In [15]:
# We can use "values()" to get every key's value in a dictionary.

dictB = {"Apple": "Fruit",21: "Number",False: "Statement"}
dictB.values()

dict_values(['Fruit', 'Number', 'Statement'])

##### "items( )" Method

In [20]:
# We can use "items()" to get every key and it's value in a dictionary.

dictC = {"a": 0,"b": 2,"c": 8,"d": 5}
dictC.items()

# Output will be in a form that is a "list with nested tuples inside".

for key, value in dictC.items():            # Different type of output.
    print(f"{key} = {value}")

a = 0
b = 2
c = 8
d = 5

##### "clear( )" Method

In [ ]:
# We can use "clear()" to clear every key and it's value from a dictionary.

dictC.clear()

##### "get( )" Method

In [26]:
forecast = {"Istanbul": 29,"Bursa": 31,"Izmir": 34,"Ankara": 34,"Sakarya": 30}

q = input("Which city would you like to know the weather forecast for?\n")

if q in forecast:
    print(f"The weather in {q} is currently {forecast.get(q)} C.")
else:
    print(f"There is no forecast information about {q}.")


#       We can create the same process with "if" keyword but:
#           1. Dictionaries makes it possible with less code.
#           2. Dictionaries are faster to use than "if".
#           3. Dictionaries makes the code cleaner so debugging will be much more easier.
#           4. With dictionaries, same process is more practical.

The weather in Istanbul is currently 29 C.

##### Sets

In [1]:
word = "Classical"
print(word)
wordSet = set(word)     # "set()" function turns any variable to a set. Sets don't have any repeating elements and the elements won't be in order.
print(wordSet)

# Sets are an "unordered" data type. Beacuse there is no order for elements, we are not able to use the "slicing method".

# wordB = wordSet[0:3]    >>>    ERROR! : TypeError: 'set' object is not subscriptable

# We can use sets to get rid of repeating elements in any list.

listAny = [0,1,2,2,3,4,5,5,5,6,5,7,8,9]

SetAny = set(listAny)
print(f"{SetAny = }")

listOnly = list(SetAny)
print(f"{listOnly = }")

# We can create "empty" sets with "set()" function as well.

Empty = set()
print(Empty)        # Output   >>   set()

# From "type()" function, we can actually see how sets are defined in Python.

setA = set(["Ahmet","Mehmet","Kemal","Asuman","Feyzanur"])
print(f"Set is {setA}\nData type is {type(setA)}")      # <class 'set'>

# We can create sets with curly brackets/braces {}.

setB = {"a","b","c","d","e"}
print(setB,type(setB))

# ( ! ) We can't use the curly brackets/braces {} to create an "empty" set.

Empty = {}
print(Empty,type(Empty), sep="\n")        # Output   >>   <class 'dict'>

Classical
{'s', 'l', 'i', 'a', 'c', 'C'}
SetAny = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
listOnly = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
set()
Set is {'Mehmet', 'Asuman', 'Kemal', 'Ahmet', 'Feyzanur'}
Data type is <class 'set'>
{'a', 'e', 'b', 'c', 'd'} <class 'set'>
{}
<class 'dict'>

##### Set Methods

In [6]:
dir(set)

for method in dir(set):     # Methods which we are going to use.
    if "_" not in method:
        print(method)

# Sets are the same as in math, that's why "union()", "intersection()" and "difference()" terms are important.

add
clear
copy
difference
discard
intersection
isdisjoint
issubset
issuperset
pop
remove
union
update

##### "add( )" Method

In [21]:
# "add()" Method

# We use "add()" to add any element to a set.

set1 = {"a","b","c","d"}
print(f"Set1 before addition: {set1}")
set1.add("e")
print(f"Set1 after addition: {set1}")

# We can add multiple elements with a loop.

setNum = set()
for  i in range(0,11):
    setNum.add(i)

print(f"Setnum after the loop: {setNum}")

Set1 before addition: {'c', 'b', 'd', 'a'}
Set1 after addition: {'c', 'e', 'a', 'b', 'd'}
Setnum after the loop: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

##### "remove( )" Method

In [29]:
# We use "remove()" to remove any element to a set.

setEx = {"a","b","c","d","e","******"}
print(f"Old setEx : {setEx}")
setEx.remove("******")
print(f"New setEx : {setEx}")

# We could use dictionaries to create a set. With this method, "elements of the set" will be consist of the "keys of the dictionary".

dictA = {"Ahmet": 22, "Mehmet": 22, "Feyzanur": 22, "Asuman": 51, "Kemal": 60}      # dict = {a: b, ...}   >>   a: key, b: key value
setA = set(dictA)
print(f"Dictionary after the conversion: {setA}")

# If we want to create a set with the values of a dictionary, we can use a different method.

dictA = {"Ahmet": 22, "Mehmet": 22, "Feyzanur": 22, "Asuman": 51, "Kemal": 60}      # dict = {a: b, ...}   >>   a: key, b: key value

setA_alt = set(dictA.values())
print(f"Set of the dictionary with it's values: {setA_alt}")

# ( ! ) Sets won't have repeating elements.

print(set([22,22,22]))

# We can create a pair of sets with dictionaries keys and it's values.

dictPhone = {"Ahmet": "0551 415 80 81", "Feyzanur": "0507 101 62 61", "Asuman": "0507 101 62 71", "Kemal": "0535 245 41 83"}

setPerson = set(dictPhone.keys())
setPhone = set(dictPhone.values())

print(f"People: {setPerson}\nPhone Number: {setPhone}")

Old setEx : {'c', 'e', 'd', 'b', '******', 'a'}
New setEx : {'c', 'e', 'd', 'b', 'a'}
Dictionary after the conversion: {'Feyzanur', 'Asuman', 'Ahmet', 'Kemal', 'Mehmet'}
Set of the dictionary with it's values: {51, 60, 22}
{22}
People: {'Feyzanur', 'Asuman', 'Ahmet', 'Kemal'}
Phone Number: {'0551 415 80 81', '0507 101 62 61', '0535 245 41 83', '0507 101 62 71'}

##### "discard( )" Method

In [32]:
# We use "discard()" to remove/discard the element. It's only difference from "remove()" method is, "it doesn't give any errors" if the element doesn't exists.

setEx = {"a","b","c","d","e","******"}
setEx.discard("f")      # Nothing happens. (No errors.)
print(setEx)

# setEx.remove("f")     >>      ERROR!: KeyError: 'f'
# print(setEx)

{'c', 'e', 'd', 'b', '******', 'a'}

##### "clear( )" Method

In [33]:
# We use "clear()" to cleaar out all the elements from a set.

setEx = {"a","b","c","d","e","******"}
setEx.clear()
print(setEx)        # Output   >>   set()

set()

##### "pop( )" Method

In [39]:
# We use "pop()" to erase "a random element" from a set and print it out.

setEx = {"a","b","c","d","e","******"}
setEx.pop()         # Output   >>   'c'
print(setEx)

{'e', 'd', 'b', '******', 'a'}

##### "update( )" Method

In [42]:
# We use "update()" to add a new element to a set. It's similar to "add()" in lists with the only difference of we can add multiple elements with "update()".

setEx = {"a","b","c","d","e"}
setEx.update("f","g")
print(f"New setEx: {setEx}")

# We can use lists, tuples and dictionaries as a variable in "update()".

setEx = {"a","b","c","d","e"}

listAdd = ["list 1","list 2"]
tupAdd = ("tup 1","tup 2")
dictAdd = {"dict 1": 1, "dict 2": 2}

setEx.update(listAdd)       # List
setEx.update(tupAdd)        # Tuple
setEx.update(dictAdd)       # Dictionary

print(f"setEx with all the new elements: {setEx}")

New setEx: {'c', 'e', 'd', 'b', 'f', 'g', 'a'}
setEx with all the new elements: {'c', 'list 2', 'dict 1', 'list 1', 'b', 'e', 'tup 2', 'a', 'dict 2', 'tup 1', 'd'}

##### "copy( )" Method

In [43]:
# We use "copy()" to copy a set.

setEx = {"a","b","c","d","e"}
setEx.copy()

{'a', 'b', 'c', 'd', 'e'}

##### Set Operations

In [5]:
# We use "union()" to find the union of two sets.    
setNumA = {1,2,3,4,5}
setNumB = {6,7,8,9,10}

setUnion = setNumA.union(setNumB)
print(f"Union of {setNumA} and {setNumB}:   >>   {setUnion}")

# If we need to find "union()" of a pair of sets, we can use "|" operator.
setNumA = {1,2,3,4,5}
setNumB = {3,4,5,6,7}
setNumUnion = setNumA | setNumB
print(f"Union of {setNumA} and {setNumB} is   >>   {setNumUnion}")

# If we need to find "difference()" between a pair of sets, we can use "-" operator.
setNumA = {1,2,3,4,5}
setNumB = {3,4,5,6,7}
setNumDiff = setNumA - setNumB
print(f"Difference between {setNumA} and {setNumB} is   >>   {setNumDiff}")

# If we need to find "symmetric_difference()" between a pair of sets, we can use "^" operator.
setNumA = {1,2,3,4,5}
setNumB = {3,4,5,6,7}
setNumSymDiff = setNumA ^ setNumB
print(f"Symmetrial difference between {setNumA} and {setNumB} is   >>   {setNumSymDiff}")

# If we need to find "intersection()" between a pair of sets, we can use "&" operator.
setNumA = {1,2,3,4,5}
setNumB = {3,4,5,6,7}
setNumInt = setNumA & setNumB
print(f"Intersection between {setNumA} and {setNumB} is   >>   {setNumInt}")

# If we need to determine if a set is a subset of another set, we used "issubset()" but we can use "<=" as well.
setNumA = {1,2,3,4,5}
setNumB = {3,4,5,6,7}
setNumSub = setNumA <= setNumB          # setNumA is the subset.
print(f"Is {setNumA} is a subset of {setNumB}?   >>   {setNumSub}")

# If we need to determine if a set is a superset of another set, we used "issuperset()" but we can use ">=" as well.
setNumA = {3,4,5}
setNumB = {3,4,5,6,7}
setNumSup = setNumB >= setNumA          # setNumB is the superset.
print(f"Is {setNumB} is a superset of {setNumA}?   >>   {setNumSup}")

Union of {1, 2, 3, 4, 5} and {6, 7, 8, 9, 10}:   >>   {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
Union of {1, 2, 3, 4, 5} and {3, 4, 5, 6, 7} is   >>   {1, 2, 3, 4, 5, 6, 7}
Difference between {1, 2, 3, 4, 5} and {3, 4, 5, 6, 7} is   >>   {1, 2}
Symmetrial difference between {1, 2, 3, 4, 5} and {3, 4, 5, 6, 7} is   >>   {1, 2, 6, 7}
Intersection between {1, 2, 3, 4, 5} and {3, 4, 5, 6, 7} is   >>   {3, 4, 5}
Is {1, 2, 3, 4, 5} is a subset of {3, 4, 5, 6, 7}?   >>   False
Is {3, 4, 5, 6, 7} is a superset of {3, 4, 5}?   >>   True

##### Functions

In [1]:
# Functions are a set of tools that let us perform any certain order of operations. 
# "print()","input()","len()" or "range()" are some of the python's "built-in functions". We can use built-in function as well as creating our own functions.
# Functions can be considered as an outline of an operation.

##### Defining a Function

In [4]:
def Hello():            # Defining a function named "Hello()".
    print("Hello World!")           # Operation/s of the function.

# To use a function in a program, we need to call it in synthax.
Hello()         # Calling the function.

def assignment():
    name = input("Person's name: ")
    print(f"The assignment is for {name}.")

assignment()

# Another example with functions.
def odd():
    print(f"{i} is an odd number.")

def even():
    print(f"{i} is an even number.")

i = input("Please type any number: ")

if int(i) % 2 == 0:         # When i is divided by 2, remaining of the result is 0 (i can be divided by 2).
    even()

else:
    odd()

Hello World!
The assignment is for Ahmet.
24 is an even number.

##### Parameters in a Function

In [13]:
# We can define parameters for functions.
def Hello(name):
    print(f"Hello {name}!")

Hello("Ahmet")      # We defined "name" as "Ahmet".     >>      name    =     "Ahmet"
#                                                            (Parameter)     (Argument)

# The process is the same as in math.
#        f(x)     =     2x + 1    >>    x = 4 (x: parameter, 4: argument)
#     (Function)

# We can only give arguments as many as parameters to a function. If function defined with 1 parameter, it could only work with 1 argument.

def multiplication(list):
    result = 1
    for i in list:
        result *= i
    print(f"Multiplication of the elements in list is: {result}")

multiplication([1,2,3,4,5])
multiplication(range(1,6))

# We can use functions to easily do series of operations without re-writing the code.

def document(receiver,date,sender):
    print(f"\nDear {receiver};\n\nWe would like to inform you that, the conference scheduled for tomorrow is delayed to the next day.\n\nfrom {sender}\n{date}")

document("Mehmet","5 Ağustos 2022","Ahmet")

Hello Ahmet!
Multiplication of the elements in list is: 120
Multiplication of the elements in list is: 120

Dear Mehmet;

We would like to inform you that, the conference scheduled for tomorrow is delayed to the next day.

from Ahmet
5 Ağustos 2022

##### Positional Parameters

In [11]:
# We can create a function with parameters as many as we want.

def signup(name,surname,city,job,phone,adress):
    signUp = {}     # Dictionary

    signUp[f"{name} {surname}:"] = [city,job,phone,adress]      # {name} {surname} >> key      city,job,phone,adress >> key's values
    print("Personal information registered.")

    print(signUp.items())           # [ ( 'Ahmet Bilgehan SERÇE:', ['Bursa', 'Student', '+905514158081', 'İhsaniye'] ) ]
#                                       ( <          key        >, <                  key's value                  > )
    for key,value in signUp.items():
        print(key)
        print("-"*len(key))
        
        for i in value:
            print(i)

signup("Ahmet Bilgehan","SERÇE","Bursa","Student","+905514158081","İhsaniye")

# When assigning values for any multi-parameter function, we must assign them sequentially (positionally). We can avoid this limitation if we use "named/keyword arguments".

Personal information registered.
dict_items([('Ahmet Bilgehan SERÇE:', ['Bursa', 'Student', '+905514158081', 'İhsaniye'])])
Ahmet Bilgehan SERÇE:
---------------------
Bursa
Student
+905514158081
İhsaniye

##### Named/Keyword Arguments

In [5]:
# When assigning the arguments to parameters, we can parameters with their names while assigning.

def signup(name,surname,city,job,phone,adress):
    signUp = {}     # Dictionary

    signUp[f"{name} {surname}:"] = [city,job,phone,adress]      # {name} {surname} >> key      city,job,phone,adress >> key's values
    print("Personal information registered.")

    print(signUp.items())           # [ ( 'Ahmet Bilgehan SERÇE:', ['Bursa', 'Student', '+905514158081', 'İhsaniye'] ) ]
#                                       ( <          key        >, <                  key's value                  > )
    for key,value in signUp.items():
        print(key)
        print("-"*len(key))
        
        for i in value:
            print(i)

signup(name = "Ahmet Bilgehan", surname = "SERÇE", city = "Bursa", job = "Student", phone = "+905514158081", adress  = "Turkey")
# We assigned argument with an emphasis to parameters names.

# Named/Keyword Arguments mostly useful when function has different type of parameters.

def promotion(person, oldPos, newPos, oldSalary, raiseSalary):
    print(f"\n{person} is promoted from {oldPos} to {newPos}.")
    print(f'''\nSalary update for {person}:\nOld Salary: {oldSalary} €\nRaise: {raiseSalary} €\nNew Salary = {oldSalary+raiseSalary} €''')

promotion(person = "Ahmet Bilgehan SERÇE", oldPos = "Junior Engineer", newPos = "AI Team Captain", oldSalary = 5000, raiseSalary = 2500)

# Sometimes, it's better to call parameters with just keywords."sep = " and "end = " parameters can be given as an example to this fact. We can define parametes just like the given examples.

def change(list, old, new):         # Function which changes an element from a list.
    indx = list.index(old)
    list[indx] = new
    print(list)

change([1, 2, 3, 4], 2, 3)          # Changing "old" element at "indx" with "new" element in the "list".

# To restrict the function to just be able to define the arguments to parameters with keywords, we use "*" operator.

def change(*,list, old, new):         # Function which changes an element from a list.
    indx = list.index(old)
    list[indx] = new
    print(list)

change(list = [1, 2, 3, 4], old = 2, new = 3)          # Changing "old" element at "indx" with "new" element in the "list".

# To restrict the function to just be able to call parameters with in order, we use "/" operator.

def change(list, /, old, new):         # Function which changes an element from a list.
    indx = list.index(old)
    list[indx] = new
    print(list)

change([1, 2, 3, 4], old = 2, new = 3)          # Changing "old" element at "indx" with "new" element in the "list".

# Some functions can take "endless" amount of parameters however some functions have limits how many parameters they can take.
# To give an example:   "print()" function can take "limitless parameters".
#                       "len()" function can only take "1 parameter (limited).

len("Ahmet")
# len("Ahmet","Bilgehan","SERÇE")         # ERROR! : len() takes exactly one argument (3 given)

# To define a function which can take "endless" amount of parameters, we use "*" operator.

def endless(*parameters):
    for parameter in parameters:
        print(parameter)

endless("Ahmet","Bilgehan","SERÇE",21,False)

# To define a function which can just take "endless" parameters with keywords, we use "**" operator.

def endlessKey(**kwArg):
    for key, value in kwArg.items():
        print(f"{key} = {value}")

endlessKey(arg1 = 1, arg2 = 12, arg3 = 43, arg4 = 25)

#  We can use "limitless-ordered parameters" and "limitless-keyworded parameters" together in a function.

def All(*Args,**kwArgs):        # *Args   >>   Limitless-ordered parameters
    for arg in Args:            # **kwArgs   >>   Limitless-keyworded parameters
        print(arg)

    for key, value in kwArgs.items():
        print(f"{key} = {value}")

All(1, 2, 3, arg1 = 1, arg2 = 2, arg3 = 3)

Personal information registered.
dict_items([('Ahmet Bilgehan SERÇE:', ['Bursa', 'Student', '+905514158081', 'Turkey'])])
Ahmet Bilgehan SERÇE:
---------------------
Bursa
Student
+905514158081
Turkey

Ahmet Bilgehan SERÇE is promoted from Junior Engineer to AI Team Captain.

Salary update for Ahmet Bilgehan SERÇE:
Old Salary: 5000 €
Raise: 2500 €
New Salary = 7500 €
[1, 3, 3, 4]
[1, 3, 3, 4]
[1, 3, 3, 4]
Ahmet
Bilgehan
SERÇE
21
False
arg1 = 1
arg2 = 12
arg3 = 43
arg4 = 25
1
2
3
arg1 = 1
arg2 = 2
arg3 = 3

##### Built-in Functions

In [6]:
# "Built-in" functions are the functions that is "embedded to the python language". When using a built-in function, we dont need to import any libraries to use it.
# "len()","sum()","print()" and "range()" are the examples of built-in functions.

# "Built-in" functions are faster and more efficient than "user-defined functions".

##### "GLOBAL" Keyword

In [13]:
# As an example;

def func():     #  
    a = 5       # namespace (*)
    print(a)    # 

func()
# print(f"The value of a: {a}")       # ERROR!   >>   NameError: name 'a' is not defined

# (*) In functions, the area between the indents, is called "namespace". Everything that is defined in a function is limited by "namespace" which means, 
# the variable which we defined inside a function does not exist outside the "namespace".

def func():
    a = 5       # "a" value inside the "namespace".
    print(a)

func()
a = 10      # "a" value outside the "namespace".
print(f"a: {a}")

# To be able to use a variable that is defined inside the "namespace" outside of the function, we use the "global" keyword.

a = 10      # a's value outside of the "namespace".

def func():
    global a
    a = 5
    print(f"a inside the \"namespace\": {a}")

func()
print(f"a outside the \"namespace\": {a}")
# a's value outside of the "namespace" is deleted because of the use of "global" keyword.

# Using the "global" keyword causes problems on projects that many programmers are working on. 
# It deletes some values of the variables outside of the "namespace", causing confusion among programmers.

5
5
a: 10
a inside the "namespace": 5
a outside the "namespace": 5

##### "RETURN" Keyword

In [24]:
# In python, every function returns a value that depends on the given argument. Returning value is like a result of mathematical function.

def func():
    a = 5
    return a

# So why should we use "return"?

def func():
    a = 5
    print(a)

print(func())       # Even we don't emphasize returning any value, functions return a value of "None" by default.

def func():
    a = 5
    return a

print(func())       # If we include a "return" keyword, we can see the returning value of "a".

# In short,
# no "return"       >>      func() = None
# with "return"     >>      func() = any type of value

def OddOrEven():
    q = int(input("Please enter any number: "))
    return q        # We returned the value of "q"

Num = OddOrEven()       # Because we returned the value of "q", this is equal to:   Num = OddOrEven() = q

if Num % 2 == 0:
    print(f"{Num} is an even number.")
else:
    print(f"{Num} is an odd number.")

# "return" helps us to do series of operations outside of the "namespace" to the returning value from the function.

def changeList(list, old, new):          # With "return":        change() = list (with changes)
    indx = list.index(old)
    list[indx] = new
    return list

newList = changeList(["Python","C++","MatLAB","Ruby","ASRkldı45"], "ASRkldı45", "Change!")
print(newList)

5
None
5
86 is an even number.
['Python', 'C++', 'MatLAB', 'Ruby', 'Change!']

##### "PASS" Keyword

In [26]:
# We use "pass" keyword if we don't want to do any operations. It usually used as a "placeholder".
# The difference between a comment and a "pass" statement in Python is that while the interpreter ignores a comment entirely, "pass is not ignored".

def dep():
    listX = []
    
    while True:
        a = input("Input: ")

        if a == 0:      # if a = 0, a's value is not gonna be added to the "listX".
            pass
        elif a == "cancel":
            break
        else:
            listX.append(a)
            print(a)

dep()

10
15
55
36
45
48
89
55
0
5
15

##### Modules

In [33]:
# We use spesific modules to do spesific operations. "Built-in Modules" are embedded in the python itself. We can "import" them to use it.

import random

# When we import a module, we gain access to use it's functions and operations.

#  "External Packages/Modules" needs to be downloaded to use it. There are many modules around the world that we can use.
# To download an esternal package, we can write "pip install <module name>" to terminal.

# We can write our own modules if we need it.

# When importing a module, if the module's name is too long we can import with a bit different syntax.

import webbrowser as web  
web.open("https://www.youtube.com")     # "webbrowser" = "web"

# We can import modules with "from <module name> import *" synthax. With this, we can use module's functions and operations without stating the module's name.
# This method is not preferred by programmers because of the consequences.

from webbrowser import *
open("https://www.reddit.com")

# Sometimes, we just need some of the functions from a module. If we don't want to import the whole module, we can use "from <module name> import <function>" to import the wanted function/s.

from random import sample

# We can add more function/s than once.

from random import randrange, sample, shuffle

# Similarly, we can import function/s with a bit shorter module name.

from datetime import datetime as dt
here = dt.now()
print(here)

2022-08-08 20:09:54.806498

##### Standart Modules

In [4]:
# Standart/ Built-in Modules are embedded in the python language. To use them, we just need to "import" them.
# For Python Built-in Modules: https://docs.python.org/3/library/

# We can access the module's ".py" file with "__file__" function if we want to.

import webbrowser
webbrowser.__file__

# Some modules are written with different languages (like "sys"). To access the file: https://github.com/python/cpython/tree/master/Python

import sys
dir(sys)
for f in dir(sys):
    if "_" not in f:
        print(f)

data = input("Data: ")

if not data:
    print("Enter any data: ")
    sys.exit()          # We use "sys.exit()" to exit the program. 
else:
    print("Data: ",data)

# We use "argv" to control how the code will work/executed.

def siteOpen(webSite):
    
    webbrowser.open(webSite)

siteOpen(sys.argv[1])       # sys.argv[1]   >>   first argument

# To execute this section of the program, we need to specify the argument."sys.argv[int]" saves the arguments values as a list.

import sys
print(sys.argv)
print(sys.argv[0],sys.argv[1])

addaudithook
argv
audit
breakpointhook
byteorder
copyright
displayhook
dllhandle
excepthook
executable
exit
flags
getallocatedblocks
getdefaultencoding
getfilesystemencodeerrors
getfilesystemencoding
getprofile
getrecursionlimit
getrefcount
getsizeof
getswitchinterval
gettrace
getwindowsversion
hexversion
implementation
intern
maxsize
maxunicode
modules
path
platform
platlibdir
prefix
ps1
ps2
ps3
setprofile
setrecursionlimit
setswitchinterval
settrace
stderr
stdin
stdout
unraisablehook
version
warnoptions
winver
Data:  12
['c:\\Users\\MONSTER\\Desktop\\Python Files\\python_demo\\venvDemo\\lib\\site-packages\\ipykernel_launcher.py', '--ip=127.0.0.1', '--stdin=9003', '--control=9001', '--hb=9000', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"6d93cc95-199e-4139-aa8e-b7c93f222fb6"', '--shell=9002', '--transport="tcp"', '--iopub=9004', '--f=c:\\Users\\MONSTER\\AppData\\Roaming\\jupyter\\runtime\\kernel-v2-3872cP32fKoith5X.json']
c:\Users\MONSTER\Desktop\Python Files\python_demo\venvDemo\lib\site-packages\ipykernel_launcher.py --ip=127.0.0.1

##### External Packages/Modules

In [5]:
# There are modules which created by other people around the web. To use them, we need to download them first.
# Most of the External Packages/Modules are stored here: https://pypi.org/

# To download an external package/module, we use "pip install <module name>" line of code in terminal.
# After the download, we can use "import" to use them.

##### User-Created Packages/Modules

In [2]:
# We can create our own modules if we need to.

dictionary = {"Buchen": "Book",
            "Computer": "Computer",
            "Programmierung": "Programming"}

def search(word):
    err = f"{word} word doesn't exist."
    return dictionary.get(word,err)

##### If "\_\_name\_\_" == "\_\_main\_\_"

In [1]:
# To run a program, we can input "python <module name>.py" to the terminal.
    # If program excepts arguments, we can input "python <module name>.py <arg 1> <arg 2> <arg 3> ..." to the terminal.

# To run a program, we can import the module to a different program or a python virtual environment.
    # import <module name>

import sys, webbrowser

urls = {"Youtube": "https://www.youtube.com/results?search_query=",
        "Reddit": "https://www.reddit.com/search/?q=",
        "Google": "https://www.google.com/search?q="}

def searchUser(site,searchIn):
    adress = str(urls.get(site))
    webbrowser.open(adress + searchIn)

searchUser(sys.argv[1],sys.argv[2])

# As an example, we can input "python searchUser.py Youtube Python" to the terminal.        ( ! ) Youtube = sys.argv[1] = site        >>        Python = sys.argv[2] = searchIn

dictionary = {"Buchen": "Book",
            "Computer": "Computer",
            "Programmierung": "Programming"}

def search(word):
    err = f"{word} word doesn't exist."
    return dictionary.get(word,err.format(word))

# We can save this program as a ".py" file to be able to import it as a module to another program.

# import dictionary
# dictionary.search("Buchen")

# ( ! ) To be able to use a module as a program and as a module simultaneously, we can use the "__name__" method. 
# *** "__name__" gets the module's name as a value when we are """importing""" the module to a program. ***

import random
random.__name__

# If we """use a module as a program (run the .py file)""", "__name__" will get a the value from "__main__" (string).
# print(__name__)     >>     Output: __main__

# "__name__" get's a different value depending how the module is imported/transfered to workspace. 
# We are able to utilize this behaviour to create programs that executes different set of operations for different situations.

import sys, webbrowser

urls = {"Youtube": "https://www.youtube.com/results?search_query=",
        "Reddit": "https://www.reddit.com/search/?q=",
        "Google": "https://www.google.com/search?q="}

def searchUser(site,searchIn):
    adress = str(urls.get(site))
    webbrowser.open(adress + searchIn)

searchUser(sys.argv[1],sys.argv[2])

# In here, we can't import this program as a module, because "we stated the parameters spesifically which results in the program asking for parameters to run".

# We can change this behaviour to happen in stated conditions.

import sys, webbrowser

urls = {"Youtube": "https://www.youtube.com/results?search_query=",
        "Reddit": "https://www.reddit.com/search/?q=",
        "Google": "https://www.google.com/search?q="}

def searchUser(site,searchIn):
    adress = str(urls.get(site))
    webbrowser.open(adress + searchIn)

if "__name__" == "__main__":            # If this program "executed in terminal as a program (not as a module)", expect entries of parameters (sys.argv[1] and sys.argv[2]).
    searchUser(sys.argv[1],sys.argv[2])

# Here is another example:

import sys      # To be able to use "argv".

dictA = {"Kitap": "Book",
        "Bilgisayar": "Computer",
        "Programlama": "Programming",
        "Veri Bilimci": "Data Scientist"}
    
def searchAndFind(word):
    err = f"{word} is not found!"
    return dictA.get(word, err.format(word))

if "__name__" == "__main__":            # If the program executed as a "program" (not as a "module").
    if len(sys.argv) < 2:           # If sys.argv[2] not entered (sys.argv is a list of 2 elements. This "if" loop checks if sys.argv[2] exists.).
        print("How to use: python dictA.py <word>")
        print("Example: python dictA.py Programlama")
    else:
        print(dictA.get(sys.argv[1], f"{sys.argv[1]} is not found!",sep="\n"))

##### sys.path

In [ ]:
# To be able to use the modules which we created, the main "code file" must be in the same file with the module.

import sys
sys.path

# To import an external (self-built) module, the module file's drectory should be included in the list of "sys.path".

# Because "sys.path" is a "list", we can add a new path with "append()" or "insert()" if we want to.

sys.path.append("Any directory")
sys.path.insert(integer, "Any directory")

# When we want to add a new file to module path, we can do it with this method.

##### File Operations

In [1]:
# To create a new file, we can use "open()" function.

fileEx = open("fileEx.txt","x")

# While creating a file, we need to decide it's "encoding". We can check the xisting file's encoding with "<file name>.encoding".

fileEx.encoding         # Output     >>     cp1254 (Turkish Windows)

# In cases where we do not specify the encoding of a file, we can check it's encoding with "getpreferredencoding()" with importing "locale" module.

import locale
locale.getpreferredencoding()

# We should specify the encoding of a new file to have more control over a project. Mostly we suggest "utf-8" encoding because of it's language support and popularity.
# Most of the time, we should use "utf-8" encoding for files.

fileBetter = open("fileBetter.txt","w",encoding = "utf-8")
fileBetter.encoding         # Output     >>     utf-8

# <file variable> = open("<file name>.<file type>","<mode>","<encoding>")
# x   >>   This mode prevents system to delete the "<file name>.<file type>" if it's already exists.
# w   >>   This mode rewrites the "<file name>.<file type>" to it's existing copy.
# r   >>   This mode creates a file to have an attribute of "read-only". This means, you are not able to add any data or edit the file.
# a   >>   This mode allows us to add a new data/s to a file.

# If we don't specify any modes when creating a file, python automatically assigns "r" mode.

# We can specify file's directory while creating.

fileDir = open("C:/Users/MONSTER/Desktop/Python Files/python_demo/fileDir.txt","w",encoding = "utf-8")

##### Rewriting on a File

In [12]:
# To write any data to a file, we can use "write()". When we finished, we can close the file with "close()".

file = open("python.txt","w",encoding="utf-8")
file.write("Python Programming Basics")
file.close()

# In this practice, we can justify the importance of using the suitable encoding.

# (!) fileTest = open("python.txt","w")       # encoding is set to standart (cp1254 (Turkish Windows)).
# (!) fileTest.write("питон")
# (!) file.close()

# This line of code won't work because the standart encoding is not suitable for russian characters.
# We can solve this problem with using more supported encoder.

fileTest = open("python.txt","w",encoding="utf-8")
fileTest.write("Python")
file.close()

##### Methods for Files

In [42]:
print(dir(fileTest))
print(fileTest.encoding)

fileTest = open("python.txt","a",encoding="utf-8")          # We used "a" mode to "add" new data to a file.
fileTest.write("Python\nProgramming\nBasics")
fileTest.close()

fileTest = open("python.txt","a",encoding="utf-8")
fileTest.writelines(["\n\nHello!","\nWith \"writelines()\" method, we can write to a file more than once!","\nIsn't it awesome?\n"])
fileTest.close()

# We can write multiple times with "write()" with "for" loops.

fileTest = open("python.txt","a",encoding="utf-8")
listWrite = ["Ahmet", "Bilgehan", "Serçe"]
for i in listWrite:
    fileTest.write(i + "\n")

fileTest.close()

import platform

data = [
    ("System: ", platform.system()),
    ("Release: ", platform.release()),
    ("Machine: ", platform.machine()),
    ("Processor: ", platform.processor()),
    ("Python Version: ",platform.version())
]

for a, b in data:
    print(f"{a}{b}")

Ans = input("Do you want to save this data [Y/N]?\n")

if Ans == "Y":
    SystemInf = open("System Informations.txt","w",encoding="utf-8")
    for a,b in data:
        SystemInf.write(f"{a}{b}\n")
    
    SystemInf.close()
    print(f"Data is saved to {SystemInf.name}")
else:
    print("Exitting...")

['_CHUNK_SIZE', '__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__ne__', '__new__', '__next__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_checkClosed', '_checkReadable', '_checkSeekable', '_checkWritable', '_finalizing', 'buffer', 'close', 'closed', 'detach', 'encoding', 'errors', 'fileno', 'flush', 'isatty', 'line_buffering', 'mode', 'name', 'newlines', 'read', 'readable', 'readline', 'readlines', 'reconfigure', 'seek', 'seekable', 'tell', 'truncate', 'writable', 'write', 'write_through', 'writelines']
utf-8
System: Windows
Release: 10
Machine: AMD64
Processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Python Version: 10.0.19044
Data is saved to System Informations.txt

##### Reading a File

In [15]:
# To read from a file, we use "read()", "readlines()" and "readline()".

fileTest = open("Poem.txt","w",encoding="utf-8")
fileTest.write("Roses are red\nViolets are blue\nIf you are happy\nI'm happy too!")
                    
fileTest.close()
fileTest = open("Poem.txt", encoding="utf-8")
print(fileTest.read())

fileTest.readlines()            # Output is a list.
fileTest.readline()

# "readline()" reads the file from beginning to the first "\n" expression (Reads the first line).

# We can read all the lines with "for" loops as well.

fileTest = open("Poem.txt", encoding="utf-8")
for line in fileTest:
    print(line,end="")
fileTest.close()

# Every time we use "<file>.readline()", cursor get's relocated to the next line.

fileTest = open("Poem.txt", encoding="utf-8")

fileTest.readline()         # Second line is read.
fileTest.readline()

# We can relocate the cursor with "<file>.seek(<position>)".

fileTest.seek(0)        # Cursor is at 0 (1st line).
fileTest.seek(3)        # Cursor is at the 3rd "character".

# "seek()" can take 2 parameters.

fileTest.seek(5,0)          # 5 : Cursor's new location        >>        0 : Cursor's new location will be decided by "counting from the beginning".
fileTest.seek(5,1)          #                                            1 : Cursor's new location will be decided by "cursor's current location".

Roses are red
Violets are blue
If you are happy
I'm happy too!
Roses are red
Violets are blue
If you are happy
I'm happy too!

3

##### Deleting a File

In [7]:
# The easiest way to delete a file is to use "remove()" from "os" module.

import os

os.remove(r"C:\\Users\\MONSTER\Desktop\\Python Files\\python_demo\\python.txt")        # r""     >>     raw string

# In Python, strings prefixed with r or R , such as r'...' and r"..." , are called "raw strings" and treat backslashes \ as literal characters.

os.remove(r"C:\\Users\\MONSTER\Desktop\\Python Files\\python_demo\\Poem.txt")

##### Catching Errors

In [2]:
# ın programming, errors are common to occur. There are different type of errors. The errors we should be expecting is errors which is caused because of users.

integerA = int(input("Type in any number: "))
print("The number is: ",integerA, sep="")

# In this line of code, if the user enters an integer, there will be no errors and the program will work as excepted to be. But if user inputs anything other than an integer, an error will occur. To catch these errors and warn the user, we use "try... except..." keywords.

# The procedure of catching errors consists of 2 steps:
#   1.) Determine the excepted errors.
#   2.) Determine the operations if the error happens.

try:
    integerA = int(input("Type in any number: "))           # We add the part of the code which we think an error may occur under "try" block.
except ValueError:
    print("Please enter an integer:")           # We add set of operations if the error which we stated happens (in here, error is "ValueError")

print("The number is: ",integerA, sep="")

# We can use this same method with differen type of errors.


try:
    num = int(input("Enter any number to divide: "))
    div = int(input(f"Select any number which is gonna divide {num}: "))
    res = num/div
except ZeroDivisionError:
    print("Division can't be done with \"0\"!")
except ValueError:
    print("Please do not enter anything other than integer!")

print("The result is: ", res, sep= "")

# We can do the same operations for different type of errors.

try:
    num = int(input("Enter any number to divide: "))
    div = int(input(f"Select any number which is gonna divide {num}: "))
    res = num/div
except (ValueError, ZeroDivisionError):
    print("The data which you entered is not recognisable!")

The number is: 5
The number is: 25
The result is: 0.09655172413793103

##### "pass" Keyword

In [4]:
# "pass" is used to skip a set of operations in any loop. We use "pass" to continue the program without doing any operations.
# We can also use "pass" if we detect an excepted error and skip to the next step doing nothing.

try:
    first = int(input("First number: "))
    sec = int(input("Second number: "))
    res = float(first/sec)
except (ZeroDivisionError, ValueError):         # When "ZeroDivisionError" and "ValueError" is occured, we prefer to do nothing.
    pass

# Choosing to do nothing when an expected error occurs, sometimes it will be good or bad. If we want the user to be aware of the error, we could choose to show a message about the error to the user.

##### "String" Methods

In [53]:
print("Methods for Strings:")
for methods in dir(str):            # We could also use     >>     dir("")
    if "_" not in methods:
        print(">> ", methods)

# "capitalize( )" Method
print("ahmet".capitalize())

# "casefold( )" Method
print("ß".casefold())

# "center( )" Method
print("Centered".center(20))        # There is 20 spaces to the right and left side.

# "count( )" Method
print("classical".count("c"))

# "encode( )" Method
    # When a data is saved in the memory, it's converted to "bytes". This operation happens in the background. 
    # If we want to, we can do the same process backwards which means we can convert "bytes" to a data.
bytesToData = b'k\xc3\xa2\xc4\x9f\xc4\xb1t'
print(bytesToData.decode("utf-8"))

# If we don't know what encoding is used when storing the data, we can add another parameter to "decode".
bytesToData = b'k\xe2\xf0\xfdt'
print(bytesToData.decode("utf-8", "replace"))           # Replacing the unsupported characters with "�".

# We use "encode" to see the bytes that generated from the given data.
dataforEncoding = "Бильгехан"
print(dataforEncoding.encode("utf-8"))

dataforEncoding = "Erwin Schrödinger"
print(dataforEncoding.encode("cp1254"))

# "endswith( )" Method
print("Ahmet".endswith("t"))        # Ends with "t"    >>     True
print("Ahmet".endswith("x"))        # Ends with "x"    >>     False

# "expandtabs( )" Method
print("Ahmet\tBilgehan\tSERÇE".expandtabs(10))          # The empty spots between the words are increased to the given number.

# "find( )" Method
print("l***".find("l"))
print("*l**".find("l"))         # Index of the given character.
print("***l".find("l"))

# "format( )" Method
print("{} and {} are the most important parts of AI with Python.".format("Data Analysis", "Deep Learning Algorithms"))

# "index( )" Method
# Does the similiar operation as "find( )".
print("l***".index("l"))

# "isalnum( )" Method
# Checks if the given argument is "alphanumerical".
    # Alphanumerical: The string which includes "characters" and "numbers".

print("ABS2000".isalnum())

# "isalpha( )" Method
# Checks if the given argument is only consists of "characters".
print("Alphabet".isalpha())

# "isascii( )" Method
# Checks if the given argumnet only consists of "ASCII".
    # ASCII: Stands for "American Standard Code for Information Interchange (ASCII)". It is a character endcoding standard that uses numbers from 0 to 127 to represent English characters.
print("õ".isascii())
print("#".isascii())

# "isdecimal( )" Method
print("10".isdecimal())
print("0.1".isdecimal())

# "isdigit( )" Method
print("1".isdigit())
print("a".isdigit())

# "isidentifier( )" Method
# Checks if the given argument is usable for naming any variables/functions.
print("NameGiven".isidentifier())
print("0".isidentifier())

# "islower( )" Method
print("lowercase".islower())
print("NotLower".islower())

# "isnumeric( )" Method
print("Numeric001".isnumeric())
print("NotNumeric".isnumeric())

# "isprintable( )" Method
# Checks if all characters in the string are printable or the string is empty.
print("Ahmet Here".isprintable())
print("Ahmet\nHere".isprintable())

# "isspace( )" Method
print("NoSpacesHere".isspace())
print("     ".isspace())

# "istitle( )" and "title( )" Method
print("python programming basics".istitle())
print("python programming basics".title())

# "isupper( )" and "upper( )" Method
print("UPPER".isupper())
print("Upper".upper())

# "join( )" Method
print(".".join("LAPD"))

# "ljust( )" Method

Methods for Strings:
>>  capitalize
>>  casefold
>>  center
>>  count
>>  encode
>>  endswith
>>  expandtabs
>>  find
>>  format
>>  index
>>  isalnum
>>  isalpha
>>  isascii
>>  isdecimal
>>  isdigit
>>  isidentifier
>>  islower
>>  isnumeric
>>  isprintable
>>  isspace
>>  istitle
>>  isupper
>>  join
>>  ljust
>>  lower
>>  lstrip
>>  maketrans
>>  partition
>>  removeprefix
>>  removesuffix
>>  replace
>>  rfind
>>  rindex
>>  rjust
>>  rpartition
>>  rsplit
>>  rstrip
>>  split
>>  splitlines
>>  startswith
>>  strip
>>  swapcase
>>  title
>>  translate
>>  upper
>>  zfill
Ahmet
ss
      Centered
2
kâğıt
k���t
b'\xd0\x91\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xb3\xd0\xb5\xd1\x85\xd0\xb0\xd0\xbd'
b'Erwin Schr\xf6dinger'
True
False
Ahmet     Bilgehan  SERÇE
0
1
3
Data Analysis and Deep Learning Algorithms are the most important parts of AI with Python.
0
True
True
False
True
True
False
True
False
True
False
True
False
False
False
True
False
False
True
False
Python Programming Basics
True
UPPER
L.A.P.D

##### Regular Expressions

In [1]:
# Regular expressions help us to control strings/texts with ease. Usually programmers should prefer string methods but in some occasions, the problem can't be solved easily. 
# In these occasions, we use regular expressions.
# Regular expressions are hard to understand and perfect it but with a great effort, we can use thme efficiently.

##### Methods for Regular Expressions

In [3]:
# We use the "re" module to use regular expressions.

import re

print("Methods for \"re\"\n", dir(re))

Methods for "re"
 ['A', 'ASCII', 'DEBUG', 'DOTALL', 'I', 'IGNORECASE', 'L', 'LOCALE', 'M', 'MULTILINE', 'Match', 'Pattern', 'RegexFlag', 'S', 'Scanner', 'T', 'TEMPLATE', 'U', 'UNICODE', 'VERBOSE', 'X', '_MAXCACHE', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '_cache', '_compile', '_compile_repl', '_expand', '_locale', '_pickle', '_special_chars_map', '_subx', 'compile', 'copyreg', 'enum', 'error', 'escape', 'findall', 'finditer', 'fullmatch', 'functools', 'match', 'purge', 'search', 'split', 'sre_compile', 'sre_parse', 'sub', 'subn', 'template']

##### "match( )" Method

In [19]:
# We use "match()" to determine how many of a specific string is mentioned.

A = "Python is a programming language used for Machine Learning and AI."
re.match("Python", A)           # Output     >>     <re.Match object; span=(0, 6), match='Python'>

# The output from re.match() is called a "match object".

print("Match for A: ", re.match("CSS", A))           # When there is no match, the method does not return any value or object.

B = "Python Java"
print("Match for B: ", re.match("Java", B))

# Even "Java" string is a part of the given string, re.match didn't return any value. This is because of the re.match() method only checks the beginning of a string.

# We can do the same process with "split()" as well.
help(str.split)         # Returns a list of the words in the string, using sep as the delimiter string.
print("Match for B: ", B.split()[0] == "Python")

# We can use "startswith()" as well.
help(str.startswith)            # Returns "True" if string starts with the specified prefix, "False" otherwise.
print("Match for B: ", B.startswith("Python"))

s = "0123456789"
q = input("Please enter a string which is going to be checked if there is a match: ")
print("Results: ", re.match(q, s))

# Regular expressions are;
    # 1.) Have many ways to use and highly efficient in different situations.
    # 2.) Stored in a module called "re".
    # 3.) Many functions to choose from which we can learn by dir(re).
    # 4.) Dependent to the situations so we need to learn how to put them in a great use.

Match for A:  None
Match for B:  None
Help on method_descriptor:

split(self, /, sep=None, maxsplit=-1)
    Return a list of the words in the string, using sep as the delimiter string.

    sep
      The delimiter according which to split the string.
      None (the default value) means split according to any whitespace,
      and discard empty strings from the result.
    maxsplit
      Maximum number of splits to do.
      -1 (the default value) means no limit.

Match for B:  True
Help on method_descriptor:

startswith(...)
    S.startswith(prefix[, start[, end]]) -> bool

    Return True if S starts with the specified prefix, False otherwise.
    With optional start, test S beginning at that position.
    With optional end, stop comparing S at that position.
    prefix can also be a tuple of strings to try.

Match for B:  True
Results:  <re.Match object; span=(0, 4), match='0123'>

##### "group( )" Method

In [30]:
# If there is a match for "re.match()", we can get the string which we checked if there is a match for it with "re.group()" method.

ExA = "Perl, Python and Ruby are high-leveled programming language."
aMatch = re.match("Perl", ExA)

print(type(aMatch))         # Output     >>     <class 're.Match'>

print("Methods for a match object: ", *dir(aMatch), sep= "\n")

print(aMatch.group())           # ( ! ) "<variable>.group()" is a method for "match objects".

s = "0123456789"
q = input("Please enter a string which is going to be checked if there is a match: ")
match  = re.match(q, s)

if match:
    print(f"There is a match for {q}.")
else:
    print(f"There is NO match for {q}.")

<class 're.Match'>
Methods for a match object:
__class__
__class_getitem__
__copy__
__deepcopy__
__delattr__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__init__
__init_subclass__
__le__
__lt__
__module__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__setattr__
__sizeof__
__str__
__subclasshook__
end
endpos
expand
group
groupdict
groups
lastgroup
lastindex
pos
re
regs
span
start
string
Perl
There is NO match for 234.

##### "search( )" Method

In [16]:
# "search()" method, "checks the whole string" for any matches. This behaviour is the biggest difference from the "match()" method.

import re

st = "Python is a highl-level programming language."

stforMatch = re.match("programming", st)

stforSearch = re.search("programming", st)

print("With \"match()\" method: ", stforMatch, "\nWith \"search()\" method: ", stforSearch)

# As in the "match()" method, we can use "group()" for the "matching object" in the "search()" method.

stforSearch = re.search("programming", st)
SearchWord = stforSearch.group()
print(f"There is a match for \"{SearchWord}\".")

listX = ["Apple", "Pear", "Orange", "Peach"]
# re.search("Pear", listX)            # ERROR!     >>     TypeError: expected string or bytes-like object

# To apply the "search()" method to lists, we need to use loops to search the elements one-by-one.
searchedWord = input("Word: ")

for words in listX:
    IsSearch = re.search(searchedWord, words)

    if IsSearch:
        print(f"There is a match for \"{IsSearch.group()}\".")
    else:
        continue

With "match()" method:  None
With "search()" method:  <re.Match object; span=(24, 35), match='programming'>
There is a match for "programming".
There is a match for "Orange".

##### "findall( )" Method

In [26]:
# We use "findall()" method to determine how many times a string is used (a word is mentioned) in a string.

ChopinWiki = """
                Frédéric François Chopin (born Fryderyk Franciszek Chopin; 1 March 1810 - 17 October 1849) was a Polish composer and virtuoso pianist of the Romantic period, who wrote primarily for solo piano. He has maintained worldwide renown as a leading musician of his era, one whose "poetic genius was based on a professional technique that was without equal in his generation".
                Chopin was born in Żelazowa Wola in the Duchy of Warsaw and grew up in Warsaw, which in 1815 became part of Congress Poland. A child prodigy, he completed his musical education and composed his earlier works in Warsaw before leaving Poland at the age of 20, less than a month before the outbreak of the November 1830 Uprising. At 21, he settled in Paris. Thereafter  in the last 18 years of his life he gave only 30 public performances, preferring the more intimate atmosphere of the salon. He supported himself by selling his compositions and by giving piano lessons, for which he was in high demand. Chopin formed a friendship with Franz Liszt and was admired by many of his other musical contemporaries, including Robert Schumann.
                After a failed engagement to Maria Wodzińska from 1836 to 1837, he maintained an often troubled relationship with the French writer Aurore Dupin (known by her pen name George Sand). A brief and unhappy visit to Mallorca with Sand in 1838 - 1839 would prove one of his most productive periods of composition. In his final years, he was supported financially by his admirer Jane Stirling, who also arranged for him to visit Scotland in 1848. For most of his life, Chopin was in poor health. He died in Paris in 1849 at the age of 39, probably of pericarditis aggravated by tuberculosis.
                All of Chopin's compositions include the piano. Most are for solo piano, though he also wrote two piano concertos, a few chamber pieces, and some 19 songs set to Polish lyrics. His piano writing was technically demanding and expanded the limits of the instrument, his own performances noted for their nuance and sensitivity. His major piano works also include mazurkas, waltzes, nocturnes, polonaises, the instrumental ballade (which Chopin created as an instrumental genre), études, impromptus, scherzi, preludes, and sonatas, some published only posthumously. Among the influences on his style of composition were Polish folk music, the classical tradition of J. S. Bach, Mozart, and Schubert, and the atmosphere of the Paris salons, of which he was a frequent guest. His innovations in style, harmony, and musical form, and his association of music with nationalism, were influential throughout and after the late Romantic period.
                Chopin's music, his status as one of music's earliest celebrities, his indirect association with political insurrection, his high-profile love-life, and his early death have made him a leading symbol of the Romantic era. His works remain popular, and he has been the subject of numerous films and biographies of varying historical fidelity. Among his many memorials is the Fryderyk Chopin Institute, which was created by the Parliament of Poland to research and promote his life and works. It hosts the International Chopin Piano Competition, a prestigious competition devoted entirely to his works.
            """

HowManyChopin = re.findall("Chopin", ChopinWiki)
print(HowManyChopin, type(HowManyChopin), sep="\t")

print(f"The word \"Chopin\" is mentioned {len(HowManyChopin)} times.")

# We could do the same process with "search()" but it wouldn't be pracical.

ListOfWiki = ChopinWiki.split()
ListofMatches = []

for words in ListOfWiki:
    if Match := re.search("Chopin", words):
        ListofMatches.append(Match.group())

print(f"The word \"Chopin\" is mentioned {len(ListofMatches)} times.")

['Chopin', 'Chopin', 'Chopin', 'Chopin', 'Chopin', 'Chopin', 'Chopin', 'Chopin', 'Chopin', 'Chopin']	<class 'list'>
The word "Chopin" is mentioned 10 times.
The word "Chopin" is mentioned 10 times.

##### Metacharacters

In [29]:
listOfNames = ["Özcan", "Mehmet", "Süleyman", "Selim", "Kemal", "Özkan", "Esra", "Dündar", "Esin", "Esma", "Özhan", "Özlem"]

# Metacharacters are the symbols that have a special meaning to a programming language. "\n" and "\t" are metacharacters. These characters don't match with anything when we use "match()" method even when it seems like they exist in a string.

for Names in listOfNames:
    searchRes = re.search("Öz[chk]an", Names)           # "[]" is a metacharacter.
    searchRes2 = re.search("Es[rm]a", Names)
    
    if searchRes:
        print(f"There is a match for {searchRes.group()}.")
    elif searchRes2:
        print(f"There is a match for {searchRes2.group()}.")        

# ( ! ) Metacharacters create "regular expressions".

# The basic metacharacters are:     [] . * + {} ^ $ | ()

There is a match for Özcan
There is a match for Özkan
There is a match for Esra
There is a match for Esma
There is a match for Özhan

##### "[ ]" (Square Brackets)

In [72]:
# Python goes through every character in [] and applies them to a string.

listA = ["23BH56", "TY76Z", "4Y7UZ", "TYUDZ", "34534"]

print("With \"match()\" method: ")
for elm in listA:
    if re.match("[0-9]", elm):
        print(elm)          # Elements which starts with a number.

# Same process can be done with different operations.

print("\nWith \"search()\" method: ")
for elm in listA:
    searchforMatches = re.search("[0-9]", elm[0])         # All the elements which includes any number.

    if searchforMatches:         # If there is a find;
        print(elm)

# ( ? ) Figure out how to use "group()" for the alternative way.

With "match()" method:
23BH56
4Y7UZ
34534

With "search()" method:
23BH56
4Y7UZ
34534

##### _Project: New Salary Calculator_

In [45]:
# New Salary Calculator

from statistics import mean

salaryDollar = [1000, 2000, 2500, 2800, 3200, 3600, 4200, 4500, 4800, 5000]         # List of Salaries
print("Old Salaries: ", salaryDollar)


def newSalaries(listSalaries):
    idx = 0         # For getting the index of the current element.
    for salary in listSalaries:
        if salary < mean(listSalaries):
            listSalaries[idx] += int(salary* .04)
        else:
            listSalaries[idx] += int(salary*.02)
        idx += 1
    return(listSalaries)

print("New salaries: ", newSalaries(salaryDollar))

Old Salaries:  [1000, 2000, 2500, 2800, 3200, 3600, 4200, 4500, 4800, 5000]
New salaries:  [1040, 2080, 2600, 2912, 3328, 3672, 4284, 4590, 4896, 5100]

##### "." (Dot)

In [58]:
# This meta-character is used to represent all the characters not including the "\n".

import re

listOfNames = ["Özcan", "Mehmet", "Süleyman", "Selim", "Kemal", "Özkan", "Esra", "Dündar", "Esin", "Esma", "Özhan", "Özlem"]

for i in listOfNames:
    nameDot = re.match("Es.a", i)           # "Es.a"     >>     "Es [all characters] a"

    if nameDot:         # If "nameDot" exists...
        print(nameDot.group())

listRand = ["23BH56", "TY76Z", "4Y7UZ", "TYUDZ", "34534"]
listRand.append("lagAY54")

for i in listRand:
    if re.match(".[0-9a-z]", i):        # Look for a match for "[all characters][numbers][charachters]..."     >>     [23BH56, 34534, lagAY54] 
        print(i)

Esra
Esma
23BH56
34534
lagAY54

##### "*" (Star)

In [7]:
# This meta-character is used to match the characters more than "zero (0)".

import re

listMatch = ["st", "sat", "saat", "saaat", "whatever"]

for c in listMatch:
    if re.match("sa*t", c):         # Output: st   >>   0 times "a"
#                                             sat   >>   1 times "a"
#                                             saat   >>   2 times "a"
#                                             saaat   >>   3 times "a"
        print(c)

# If we want to match an element which starts with "s" and has at least zero or more "a", we can do it with "[sa]*t".

for s in listMatch:
    if re.match("[sa]*t", s):       # Output: st   >>   0 times "a"
#                                             sat   >>   1 times "a"
#                                             saat   >>   2 times "a"
#                                             saaat   >>   3 times "a"
        print(s)

listOfNames = ["Ahmet", "Mehmet", "Kemal"]

for a in listOfNames:
    if re.match(".*met", a):
        print(a)

listOfNames = ["Bilgehan", "Oğuzhan", "Kemal", "Asuman"]

for h in listOfNames:
    if re.match(".*han", h):
        print(h)

# We use this method to organize/gather specific file types from a file.

import os, re
file = os.listdir(os.getcwd())

help(os.getcwd)

for i in file:
    if re.match(".*mp3", i):
        print(i)

st
sat
saat
saaat
st
sat
saat
saaat
Ahmet
Mehmet
Bilgehan
Oğuzhan
Help on built-in function getcwd in module nt:

getcwd()
    Return a unicode string representing the current working directory.

##### "+" (Plus)

In [17]:
# This meta-character is similar to "*". It extracts the characters which repeats before it.

listX = ["ahmet", "mehmet", "met", "kemal"]

print("With \"+\":")
for i in listX:
    if re.match(".+met", i):            # The string must include something before "met".
        print(i)

print("\nWith \"*\":")
for i in listX:
    if re.match(".*met", i):            # The string does not need to include any characters before "met".
        print(i)

listSt = ["st", "sat", "saat", "saaat"]

print("\nWith \"+\":")
for i in listSt:
    if re.match("sa+t", i):         # The string must include one or more "a".     
        print(i)

print("\nWith \"*\":")
for i in listSt:
    if re.match("sa*t", i):        # The string does not need to include any "a".    
        print(i)

A = ["23BH56", "TY76Z", "4Y7UZ", "TYUDZ", "34534"]          # We need to extract "TY76Z"

print("\nWith \"+\":")
for a in A:
    if re.match("[A-Z]+[0-9]+[A-Z]", a):
        print(a)

With "+":
ahmet
mehmet

With "*":
ahmet
mehmet
met

With "+":
sat
saat
saaat

With "*":
st
sat
saat
saaat

With "+":
TY76Z

##### "?" (Question Mark)

In [18]:
# This meta-character extracts the strings if there is one (1) or zero (0) matches.

listSt = ["st", "sat", "saat", "saaat"]

print("\nWith \"+\":")
for i in listSt:
    if re.match("sa+t", i):         # The string must include one or more "a".     
        print(i)

print("\nWith \"*\":")
for i in listSt:
    if re.match("sa*t", i):        # The string does not need to include any "a".    
        print(i)

print("\nWith \"?\":")
for i in listSt:
    if re.match("sa?t", i):        # The string should have one or zero matches for "a".            Output     >>     st (zero matches)
#                                                                                                                     sat  (one matches)
        print(i)

With "+":
sat
saat
saaat

With "*":
st
sat
saat
saaat

With "?":
st
sat

##### "{ }" (Curly Brackets)

In [27]:
# This meta-character makes us be able to specify the amount of matches.

listSt = ["st", "sat", "saat", "saaat"]

print("With \"{}\"")
for i in listSt:
    if re.match("sa{3}t", i):           # Output     >>     saaat (3 matches for "a")
        print(i)

print("\nWith \"{}\" with a specific range:")
for i in listSt:
    if re.match("sa{0,3}t", i):         # There should be minimum 0 and maximum 3 matches for "a".
        print(i)

With "{}"
saaat

With "{}" with a specific range:
st
sat
saat
saaat

##### "^" (Hat)

In [37]:
# This meta-character is same as the "match()" method. It checks the beginning of a string for any matches.

a = ["23BH56", "TY76Z", "4Y7UZ", "TYUDZ", "34534", "lagAY54"]

print("With \"search()\" Method:")
for i in a:
    if re.search("[A-Z]+[0-9]", i):         # The output is not clear.
        print(i)

# To optimize the output;

print("\nGrouped output:")
for i in a:
    SearchEx = re.search("[A-Z]+[0-9]", i)          # The output is optimized. (Locating the match in strings)
    if SearchEx:
        print(SearchEx.group())

print("\nWith \"^\":")
for i in a:
    SearchEx = re.search("^[A-Z]+[0-9]", i)          # Same process with control over the beginning of a string.
    if SearchEx:
        print(SearchEx.group())

# "^" meta-character just extracts the matching parts.

# If we want to extract the whole string which makes up the conditions;

print("\nWith \"^\" but the whole string:")
for i in a:
    SearchEx = re.search("^[A-Z]+[0-9].*", i)          # Same process with control over the beginning of a string. This time the output is the whole string.
    if SearchEx:
        print(SearchEx.group())

With "search()" Method:
23BH56
TY76Z
4Y7UZ
lagAY54

Grouped output:
BH5
TY7
Y7
AY5

With "^":
TY7

With "^" but the whole string:
TY76Z

##### "$" (Dollar)

In [4]:
# This meta-character is similar to "^". It checks the ending of a string for any matches.

import re

listMatch = ["at", "katkı", "fakat", "atkı", "rahat", "mat", "yat", "sat", "satılık", "katılım"]

print("With \"$\":")
for i in listMatch:
    if re.search("at$", i):         # All string which ends with "at".
        print(i)

With "$":
at
fakat
rahat
mat
yat
sat

##### "\\" (Reverse Slash)

In [6]:
# We always used "\" as an escape string. This meta-character's purpose is, to find any meta-characters in a string. 
# With "\", we can avoid the special interaction (which is it being a meta-character) between any meta-character.

listValue = ["10$", "25€", "20$", "10₺", "25€"]

# To seperate the strings which includes "$" sign:

print("With \"\\\":")
for i in listValue:
    if re.search("[0-9]+\$", i):        # All strings which includes the "$" meta-character.
        print(i)

With "\":
10$
20$

##### "|" (Straight Line)

In [9]:
# This meta-character is used to search any matches with multiple conditions needed.

listMatch = ["at", "katkı", "fakat", "atkı", "rahat", "mat", "yat", "sat", "satılık", "katılım"]

print("With \"|\":")
for i in listMatch:
    if re.search("^at|at$", i):         # All the strings which starts with "at" AND ends with "at". Strings does NOT need to meet every condition. It is sufficient to satisfy just one.
        print(i)

With "|":
at
fakat
atkı
rahat
mat
yat
sat

##### Methods for Matched Objects

In [12]:
# When we get a mached object (<class 're.Match'>), we can use several methods to fulfill our needs.

##### "group( )" Method ( ! )

In [24]:
# "group()" method, is used to control the matched objects with ease.

import re

a = "Python is a high-level programming language"
Object = re.search("(Python) (is) (a) (high-level) (programming) (language)", a)            # Grouped "a" variable (with the help of "()" meta-character.)
print(Object.group())

# Now, we can access to the elements in the group.

print(Object.group(0))          # The whole variable is stored in the 0th element in "matched object".

print(Object.group(1))
print(Object.group(2))
print(Object.group(3))
print(Object.group(4))
print(Object.group(5))
print(Object.group(6))

# We can use this method to have a control over the variable.

li = ['a href="about_the_book.html">About the Book</a>', 
    'a href="about_python.html">About Python</a>',
    'a href="download.html">Downloading Python</a>',
    'a href="version.html">Version of Python</a>',]

import re

for elm in li:
    objectX = re.search('a href="(.+html)">(.+)</a>', elm)          # All string which has:          any characters before "html"
    #                                                                                                any characters between "<\a>" and ">"

    if objectX:
        print(f"Title: {objectX.group(2).ljust(25)} Link: {objectX.group(1)}")          # objectX.group(2)   >>   About the Book, About Python, Downloading Python, Version of Python
        #                                                                                 objectX.group(1)   >>   about_the_book.html, about_python.html, download.html, version.html

Python is a high-level programming language
Python is a high-level programming language
Python
is
a
high-level
programming
language
Title: About the Book            Link: about_the_book.html
Title: About Python              Link: about_python.html
Title: Downloading Python        Link: download.html
Title: Version of Python         Link: version.html

##### "groups( )" Method

In [1]:
# We use "groups()" mehod for grouped objects to store them as "tuple".

li = ['a href="about_the_book.html">About the Book</a>', 
    'a href="about_python.html">About Python</a>',
    'a href="download.html">Downloading Python</a>',
    'a href="version.html">Version of Python</a>',]

import re

for elm in li:
    objectX = re.search('a href="(.+html)">(.+)</a>', elm)          # All string which has:          any characters before "html"
    print(objectX.groups())

('about_the_book.html', 'About the Book')
('about_python.html', 'About Python')
('download.html', 'Downloading Python')
('version.html', 'Version of Python')

##### Special Strings

In [2]:
# There are characters which has a special purpose other than meta-characters.

##### "\s" String

In [5]:
# "\s" is used to catch any spaces " " in a string.
import re
a = ["November 5", "March27", "4 October", "April 3"]
for i in a:
    obj = re.search("[A-Za-z]+\s[0-9]", i)
    if obj:
        print(obj.group())

November 5
April 3

##### "\d" String

In [6]:
# "\d" is used to match the float type integer in a string.
import re
a = ["November 5", "March27", "4 October", "April 3"]
for i in a:
    obj = re.search("[A-Za-z]+\s\d", i)
    if obj:
        print(obj.group())

November 5
April 3

##### "\w" String

In [8]:
# "\w" is used to match the "alphanumerical values" in a string. 

import re
a = "abc123_$%+"
print(re.search("\w*", a).group())

abc123_

In [10]:
# This string's capitalized versions to the opposite.

##### Compiling Regular Expressions

##### "compile( )" Method

In [11]:
import re
listA = ["Python3.5", "Python3.6", "Python3.7", "Python3.8", "Java"]

comp = re.compile("[A-Za-z]+[0-9]\.[0-9]")          # We can specify the layout or conditions with "compile" before any operations. This makes it easier to use.
for i in listA:
    if obj := comp.search(i):
        print(obj.group())

# ( & ) "[A-Za-z]+[0-9]\.[0-9]"     >>     Starts with "A-Z" and continues with "a-z more than one (+)", and ends with "0-9\.0-9". 
#                                              # Backslash ("\") is used to escape the "." variable, to treat it as a "regular string".

Python3.5
Python3.6
Python3.7
Python3.8

##### Compile Options with "compile( )"

##### "re.IGNORCASE" or "re.I"

In [12]:
# "re.IGNORECASE" si used to ignore upper-lower case difference when compiled and using methods.

AI_file = """Yapay zeka (Artificial intelligence, AI), insanlar da dahil olmak üzere hayvanlar tarafından görüntülenen doğal zekânın aksine makineler tarafından görüntülenen zekâ çeşididir İlk ve ikinci kategoriler arasındaki ayrım genellikle seçilen kısaltmayla ortaya çıkar. "Güçlü" yapay zeka genellikle Yapay genel zeka (Artificial General Intelligence kelimelerinin kısaltılmışı olarak: AGI) olarak etiketlenirken "doğal" zekayı taklit etme girişimleri yapay biyolojik zeka (Artificial Biological Intelligence: ABI) olarak adlandırılır. Önde gelen yapay zeka ders kitapları, alanı zeki etmenlerin çalışması olarak tanımlar: Çevresini algılayan ve hedeflerine başarıyla ulaşma şansını en üst düzeye çıkaran eylemleri gerçekleştiren herhangi bir cihaz.[3] Halk arasında, "yapay zeka" terimi genellikle insanların insan zihni ile ilişkilendirdiği "öğrenme" ve "problem çözme" gibi "bilişsel" işlevleri taklit eden makineleri tanımlamak için kullanılır.
Makineler gittikçe daha yetenekli hale geldikçe, "zeka" gerektirdiği düşünülen görevler genellikle AI etkisi olarak bilinen bir fenomen olan AI tanımından çıkarılır. Tesler'in Teoremindeki bir espri, "AI henüz yapılmamış şeydir" der. Örneğin, optik karakter tanıma AI olarak değerlendirilen şeylerin dışında tutulur, rutin teknoloji haline gelir."""

comp = re.compile("zeka", re.IGNORECASE)
print(comp.findall(AI_file))

['zeka', 'zeka', 'zeka', 'zeka', 'zeka', 'zeka', 'zeka', 'zeka']

##### "re.DOTALL" or "re.S"

In [14]:
import re

a = "I'm Python, \nMonty Python"
print(re.search("Python.*", a).group())         # "." meta-character does not include "\n" while searching. That's why this code cannot pass the "\n" and find another match in a string.

comp = re.compile("Python.*", re.DOTALL)
obj = comp.search(a)
if obj:
    print(obj.group())

Python,
Python,
Monty Python

##### "sub( )" Method

In [4]:
# Until this time, we mentioned about finding a match in a string with using regular expressions but this is not the only use of it. 
# We can use regular expressions to make changes in a string as well. To achieve this, we use two different methods:
# 1.) "sub()" Method
# 2.) "subn()" Method

import re

Python_Wiki = """Python, nesne yönelimli, yorumlamalı, birimsel (modüler) ve etkileşimli yüksek seviyeli bir programlama dilidir. 
Girintilere dayalı basit söz dizimi, dilin öğrenilmesini ve akılda kalmasını kolaylaştırır. 
Bu da ona söz diziminin ayrıntıları ile vakit yitirmeden programlama yapılmaya başlanabilen bir dil olma özelliği kazandırır. 
Modüler yapısı, sınıf dizgesini (sistem) ve her türlü veri alanı girişini destekler. Hemen hemen her türlü platformda çalışabilir (Unix, Linux, Mac, Windows, Amiga, Symbian). 
Python ile sistem programlama, kullanıcı arabirimi programlama, ağ programlama, web programlama, uygulama ve veri tabanı yazılımı programlama gibi birçok alanda yazılım geliştirebilirsiniz. 
Büyük yazılımların hızlı bir şekilde prototiplerinin üretilmesi ve denenmesi gerektiği durumlarda da C ya da C++ gibi dillere tercih edilir. 
Python 1980'lerin sonunda ABC programlama diline alternatif olarak tasarlanmıştı. 
Python 2.0, ilk kez 2000 yılında yayınlandı.
2008'de yayınlanan Python 3.0, dilin önceki versiyonuyla tam uyumlu değildir ve Python 2.x'te yazılan kodların Python 3.x'te çalışması için değiştirilmesi gerekmektedir. 
Python 2 versiyonun resmi geliştirilme süreci, dilin son sürümü olan Python 2.7.x serisi versiyonların ardından 1 Ocak 2020 itibarıyla resmi olarak sona erdi.
Python 2.x geliştirilme desteğinin sona ermesinin ardından, Python dilinin 3.6.x ve sonraki sürümlerinin geliştirilmesi devam etmektedir."""

comp = re.compile("Python", re.IGNORECASE)
print(comp.sub("C++", Python_Wiki))         # "sub()" method changes the selected string to another string. Here we changed "Python" to "C++".

# "sub()" method is equivalent to "replace()" method for strings. "sub()" method has a wider range of uses and it's better because we can use it with "compile()" method.

C++, nesne yönelimli, yorumlamalı, birimsel (modüler) ve etkileşimli yüksek seviyeli bir programlama dilidir.
Girintilere dayalı basit söz dizimi, dilin öğrenilmesini ve akılda kalmasını kolaylaştırır.
Bu da ona söz diziminin ayrıntıları ile vakit yitirmeden programlama yapılmaya başlanabilen bir dil olma özelliği kazandırır.
Modüler yapısı, sınıf dizgesini (sistem) ve her türlü veri alanı girişini destekler. Hemen hemen her türlü platformda çalışabilir (Unix, Linux, Mac, Windows, Amiga, Symbian).
C++ ile sistem programlama, kullanıcı arabirimi programlama, ağ programlama, web programlama, uygulama ve veri tabanı yazılımı programlama gibi birçok alanda yazılım geliştirebilirsiniz.
Büyük yazılımların hızlı bir şekilde prototiplerinin üretilmesi ve denenmesi gerektiği durumlarda da C ya da C++ gibi dillere tercih edilir.
C++ 1980'lerin sonunda ABC programlama diline alternatif olarak tasarlanmıştı.
C++ 2.0, ilk kez 2000 yılında yayınlandı.
2008'de yayınlanan C++ 3.0, dilin önceki versiyonuyla tam uyumlu değildir ve C++ 2.x'te yazılan kodların C++ 3.x'te çalışması için değiştirilmesi gerekmektedir.
C++ 2 versiyonun resmi geliştirilme süreci, dilin son sürümü olan C++ 2.7.x serisi versiyonların ardından 1 Ocak 2020 itibarıyla resmi olarak sona erdi.
C++ 2.x geliştirilme desteğinin sona ermesinin ardından, C++ dilinin 3.6.x ve sonraki sürümlerinin geliştirilmesi devam etmektedir.

##### "subn( )" Method

In [5]:
# "subn()" method is almost the same as "sub()" with soe different instances. "subn()" method also includes how many changes are made.

import re

Python_Wiki = """Python, nesne yönelimli, yorumlamalı, birimsel (modüler) ve etkileşimli yüksek seviyeli bir programlama dilidir. 
Girintilere dayalı basit söz dizimi, dilin öğrenilmesini ve akılda kalmasını kolaylaştırır. 
Bu da ona söz diziminin ayrıntıları ile vakit yitirmeden programlama yapılmaya başlanabilen bir dil olma özelliği kazandırır. 
Modüler yapısı, sınıf dizgesini (sistem) ve her türlü veri alanı girişini destekler. Hemen hemen her türlü platformda çalışabilir (Unix, Linux, Mac, Windows, Amiga, Symbian). 
Python ile sistem programlama, kullanıcı arabirimi programlama, ağ programlama, web programlama, uygulama ve veri tabanı yazılımı programlama gibi birçok alanda yazılım geliştirebilirsiniz. 
Büyük yazılımların hızlı bir şekilde prototiplerinin üretilmesi ve denenmesi gerektiği durumlarda da C ya da C++ gibi dillere tercih edilir. 
Python 1980'lerin sonunda ABC programlama diline alternatif olarak tasarlanmıştı. 
Python 2.0, ilk kez 2000 yılında yayınlandı.
2008'de yayınlanan Python 3.0, dilin önceki versiyonuyla tam uyumlu değildir ve Python 2.x'te yazılan kodların Python 3.x'te çalışması için değiştirilmesi gerekmektedir. 
Python 2 versiyonun resmi geliştirilme süreci, dilin son sürümü olan Python 2.7.x serisi versiyonların ardından 1 Ocak 2020 itibarıyla resmi olarak sona erdi.
Python 2.x geliştirilme desteğinin sona ermesinin ardından, Python dilinin 3.6.x ve sonraki sürümlerinin geliştirilmesi devam etmektedir."""

comp = re.compile("Python", re.IGNORECASE)
print(comp.subn("C++", Python_Wiki))         # "subn()" method changes the selected string to another string. Here we changed "Python" to "C++" and show how many changes has been made.

("C++, nesne yönelimli, yorumlamalı, birimsel (modüler) ve etkileşimli yüksek seviyeli bir programlama dilidir. \nGirintilere dayalı basit söz dizimi, dilin öğrenilmesini ve akılda kalmasını kolaylaştırır. \nBu da ona söz diziminin ayrıntıları ile vakit yitirmeden programlama yapılmaya başlanabilen bir dil olma özelliği kazandırır. \nModüler yapısı, sınıf dizgesini (sistem) ve her türlü veri alanı girişini destekler. Hemen hemen her türlü platformda çalışabilir (Unix, Linux, Mac, Windows, Amiga, Symbian). \nC++ ile sistem programlama, kullanıcı arabirimi programlama, ağ programlama, web programlama, uygulama ve veri tabanı yazılımı programlama gibi birçok alanda yazılım geliştirebilirsiniz. \nBüyük yazılımların hızlı bir şekilde prototiplerinin üretilmesi ve denenmesi gerektiği durumlarda da C ya da C++ gibi dillere tercih edilir. \nC++ 1980'lerin sonunda ABC programlama diline alternatif olarak tasarlanmıştı. \nC++ 2.0, ilk kez 2000 yılında yayınlandı.\n2008'de yayınlanan C++ 3.0, dilin önceki versiyonuyla tam uyumlu değildir ve C++ 2.x'te yazılan kodların C++ 3.x'te çalışması için değiştirilmesi gerekmektedir. \nC++ 2 versiyonun resmi geliştirilme süreci, dilin son sürümü olan C++ 2.7.x serisi versiyonların ardından 1 Ocak 2020 itibarıyla resmi olarak sona erdi.\nC++ 2.x geliştirilme desteğinin sona ermesinin ardından, C++ dilinin 3.6.x ve sonraki sürümlerinin geliştirilmesi devam etmektedir.", 11)

#### Database Programming with SQLITE

In [1]:
# Databases are collections of data and information which is stored electronically in a computer system. Databeases are usually controlled by "Database Management System (DBMS)".
# Databases are modelled as a "table" in a program to understand it's behaviour easily. To manipulate the data inside or execute operations, programmers use "Structured Query Language (SQL)".
# SQL is a programming language which is used to manipulate the data inside a database and execute operations with it.

##### Using SQLITE

In [2]:
# SQLITE is a preffered DBMS to fulfill our needs because:
    # 1.) Python has "sqlite3" standart module to use it for accessing the SQLITE database.
    # 2.) There is no need for any installations.
    # 3.) It's easier to use from the other alternatives.
    # 4.) SQLITE is open to the community which means we can use it as how as we like.
    # 5.) Despite it's being  basic, it's used by big and well-known companies for their projects suh as Adobe, Apple, Mozilla/Firefox and Google.

##### The Structure of SQLITE

In [3]:
# All the databases store the data with a method which is similar to a "table".
# ( ! ) It's very similar to "matrix" with the difference of not being mathematical.

# To understand it's behaviour better; extract the file from "https://www.dropbox.com/s/d9a0ek2yw9m0i1e/kitaplar.sqlite?dl=1".

import sqlite3

database = sqlite3.connect("kitaplar.sqlite")           # We use "connect()" method to create or connect an existing database to a variable.
databaseTemp = sqlite3.connect(":memory:")          # Creating a temporary database (executed in RAM). This database is deleted after closing it.
databaseTempDisc = sqlite3.connect("")           # Creating a temporary database (executed in disc).

# Temporary databases are mostly useful when testing. While working in a temporary database; if error occurs, it's caused by coding not because of the data.

##### Connecting With an Existing Database

In [4]:
import sqlite3

database = sqlite3.connect("kitaplar.sqlite")           # We use "connect()" method to connect an existing database to a variable.

##### Creating a Cursor

In [5]:
# After creating a database; to be able to make operations in it, we need to define a cursor.
# To create a cursor, we use "cursor()" method.

cs = database.cursor()          # Defining a cursor.

##### Creating a Table

In [9]:
# After creating/defining a cursor, we can use "execute()" to execute operations.

import sqlite3

dt = sqlite3.connect("dt.sqlite")
crsr = dt.cursor()
crsr.execute("CREATE TABLE Address_Book (Name, Surname)")          # In this line, we created a table with "CREATE TABLE" command and give the created table a name which is "Address_Book" 
#                                                                     and added two columns which named "Name" and "Surname".

# "CREATE TABLE" is a SQL command which we use to create a table.

##### Creating a Table "Conditionally"

In [12]:
# We can create a "table" in a database with "CREATE TABLE". But if there is already a table exists, this line of code will result in an error.

import sqlite3

dt = sqlite3.connect("dt.sqlite")
crsr = dt.cursor()
# crsr.execute("CREATE TABLE Address_Book (Name, Surname)")           # ERROR!     >>     OperationalError: table Address_Book already exists

# If we want to create a table conditionally (without getting an error), we use "CREATE TABLE IF NOT EXISTS".

crsr.execute("CREATE TABLE IF NOT EXISTS Address_Book (Name, Surname)")

##### Entering Data to a Table

In [14]:
# After all the operations, we can add data of any kind to a table.

crsr.execute("""INSERT INTO Address_Book VALUES ("Ahmet", "SERÇE")""")

# We can use '' as well.

crsr.execute("INSERT INTO Address_Book VALUES ('Mehmet', 'SERÇE')")

##### Commiting the Entered Data

In [16]:
# After we entered the values, we need to save the process or "commit" to the entered values. For this, we use "<database>.commit()".

dt.commit()

# This saves or changes the table with the entered data.

##### Closing the Database

In [20]:
# After all the operations we wanted to do, we need to close the database. For this purpose, we simply use "<database>.close()".

dt.close()

# With this line of code, we let our system to let go the working resources for the database. Normally, when we close a program, 
# sqlite databases close automatically but it's better to do it controllably.

# If we want the system to close the database when we are done with the operations, we could use "with" to do it.

import sqlite3

with sqlite3.connect("dtEx.sqlite") as dtEx:
    crsrEx = dtEx.cursor()
    crsrEx.execute("CREATE TABLE IF NOT EXISTS Staff (Name, Surname, Country)")
    crsrEx.execute("INSERT INTO Staff VALUES ('Ahmet', 'Serçe', 'TURKEY')")
    dtEx.commit()

# With "with" keyword; after all the operations, database will be closed by the system automatically.

##### Parameterized Data Submission

In [22]:
# For some instances, we want to enter the data with it's perks without the data. 
# If the data is going to be collected from an external source, we need to let the system know that the data is "parameterized".

import sqlite3

with sqlite3.connect("dtB") as dtB:
    crs = dtB.cursor()

    data = [("Ahmet", "Serçe", 22), 
            ("Mehmet", "Serçe", 22), 
            ("Feyzanur", "Serçe", 22)]

    crs.execute("CREATE TABLE IF NOT EXISTS Family (Name, Surname, Age)")

    for d in data:
        crs.execute("INSERT INTO Family VALUES (?, ?, ?)", d)           # We use "?" to let the system know that the data is "parameterized".
    
    dtB.commit()

##### Selecting/Choosing a Data in a Table

In [24]:
# After all the submissions, we want to do the opposite which is extracting any data we want. To achieve this, we use "SELECT <data> FROM <table>".

import sqlite3

dtEx = sqlite3.connect("dtEx.sqlite")
crsEx = dtEx.cursor()

crsEx.execute("CREATE TABLE IF NOT EXISTS Bills (Bill, Amount, Payment Date, Last Payment Date)")
crsEx.execute("INSERT INTO Bills VALUES ('Electricity', '50$', '20 October', '28 October')")

dtEx.commit()

dtEx.execute("SELECT * FROM Bills")         # ( ! ) In this line, "*" means "all the elements".

# After this operation we select all the data from "Bills" table but we haven't "extracted" them.

##### Extracting the Selected Data from a Table

##### "fetchall( )" Method

In [3]:
import sqlite3

dtExB = sqlite3.connect("dtExB.sqlite")
crsExB = dtExB.cursor()

crsExB.execute("CREATE TABLE IF NOT EXISTS Bills (Bill, Amount, Payment Date, Last Payment Date)")
crsExB.execute("INSERT INTO Bills VALUES ('Electricity', '50$', '20 October', '28 October')")

dtExB.commit()

dtExB.execute("SELECT * FROM Bills")         # ( ! ) In this line, "*" means "all the elements".

# After this operation we select all the data from "Bills" table but we haven't "extracted" them.
# To extract the selected data, we could use "fetchall()" method.

dataExB = crsExB.fetchall()            # This line extracts the selected data to a variable named "dataExB".
print(dataExB)

# If this section of the program repeatedly gets executed, the same data will be added every time. 
# If we want to make the system to add the data just once to a database, we need to use a different aproach.

import sqlite3, os

file = "vt.sqlite"
fileExists = os.path.exists(file)           # Test whether a path exists.  Returns "False" for broken symbolic links.

help(os.path)

vt = sqlite3.connect(file)
im = vt.cursor()

im.execute("CREATE TABLE IF NOT EXISTS Bills (Bill, Amount, First Payment Date, Last Payment Date)")

if not fileExists:
    im.execute("INSERT INTO Bills VALUES ('Electricity', '50 €', '25 October', '30 October')")
    vt.commit()

im.execute("SELECT * FROM Bills ")
dataBills = im.fetchall()
print(dataBills)

[]
Help on module ntpath:

NAME
    ntpath - Common pathname manipulations, WindowsNT/95 version.

MODULE REFERENCE
    https://docs.python.org/3.10/library/ntpath.html

    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    Instead of importing this module directly, import os and refer to this
    module as os.path.

FUNCTIONS
    abspath(path)
        Return the absolute version of a path.

    basename(p)
        Returns the final component of a pathname

    commonpath(paths)
        Given a sequence of path names, returns the longest common sub-path.

    commonprefix(m)
        Given a list of pathnames, returns the longest common leading component

    dirname(p)
        Returns the directory component of a pathname

    exists(path)
        Test whether a path exists.  Returns False for broken symbolic links

    expanduser(path)
        Expand ~ and ~user constructs.

        If user or $HOME is unknown, do nothing.

    expandvars(path)
        Expand shell variables of the forms $var, ${var} and %var%.

        Unknown variables are left unchanged.

    getatime(filename)
        Return the last access time of a file, reported by os.stat().

    getctime(filename)
        Return the metadata change time of a file, reported by os.stat().

    getmtime(filename)
        Return the last modification time of a file, reported by os.stat().

    getsize(filename)
        Return the size of a file, reported by os.stat().

    isabs(s)
        Test whether a path is absolute

    isdir(s)
        Return true if the pathname refers to an existing directory.

    isfile(path)
        Test whether a path is a regular file

    islink(path)
        Test whether a path is a symbolic link.
        This will always return false for Windows prior to 6.0.

    ismount(path)
        Test whether a path is a mount point (a drive root, the root of a
        share, or a mounted volume)

    join(path, *paths)
        # Join two (or more) paths.

    lexists(path)
        Test whether a path exists.  Returns True for broken symbolic links

    normcase(s)
        Normalize case of pathname.

        Makes all characters lowercase and all slashes into backslashes.

    normpath(path)
        Normalize path, eliminating double slashes, etc.

    realpath(path, *, strict=False)

    relpath(path, start=None)
        Return a relative version of a path

    samefile(f1, f2)
        Test whether two pathnames reference the same actual file or directory

        This is determined by the device number and i-node number and
        raises an exception if an os.stat() call on either pathname fails.

    sameopenfile(fp1, fp2)
        Test whether two open file objects reference the same file

    samestat(s1, s2)
        Test whether two stat buffers reference the same file

    split(p)
        Split a pathname.

        Return tuple (head, tail) where tail is everything after the final slash.
        Either part may be empty.

    splitdrive(p)
        Split a pathname into drive/UNC sharepoint and relative path specifiers.
        Returns a 2-tuple (drive_or_unc, path); either part may be empty.

        If you assign
            result = splitdrive(p)
        It is always true that:
            result[0] + result[1] == p

        If the path contained a drive letter, drive_or_unc will contain everything
        up to and including the colon.  e.g. splitdrive("c:/dir") returns ("c:", "/dir")

        If the path contained a UNC path, the drive_or_unc will contain the host name
        and share up to but not including the fourth directory separator character.
        e.g. splitdrive("//host/computer/dir") returns ("//host/computer", "/dir")

        Paths cannot contain both a drive letter and a UNC path.

    splitext(p)
        Split the extension from a pathname.

        Extension is everything from the last dot to the end, ignoring
        leading dots.  Returns "(root, ext)"; ext may be empty.

DATA
    __all__ = ['normcase', 'isabs', 'join', 'splitdrive', 'split', 'splite...
    altsep = '/'
    curdir = '.'
    defpath = r'.;C:\bin'
    devnull = 'nul'
    extsep = '.'
    pardir = '..'
    pathsep = ';'
    sep = r'\'
    supports_unicode_filenames = True

FILE
    c:\users\monster\appdata\local\programs\python\python310\lib\ntpath.py


[('Electricity', '50 €', '25 October', '30 October')]

##### "fetchone( )" and "fetchmany( )" Methods

In [ ]:
#                                                       WILL BE RETURNED

##### Data Filtering

In [ ]:
#                                                       WILL BE RETURNED

##### Safety of the Database

In [ ]:
#                                                       WILL BE RETURNED

#### Object-Oriented Programming (OOP)

##### Classes

In [1]:
# Classes help us to group/organize functions and variables. 
# We use classes to "group elements which are used for same or similar purpose". With this grouping, we are able to work more efficiently and our code will be easier to read/navigate through.

class Sınıf:
    var1 = "value1"

    def func_1():
        pass

    def func_2():
        pass

# For instance, if we are doing operations based on a database:

import sqlite3, os

db = sqlite3.connect(":memory:")

class dbOp:
    
    def connect_db():
        db_location = dir(db)        
        if db_location != "":
            print("Connection acquired!")

    def lost_db():
        if db.commit():
            print("Connection lost!")

    def query_db(): 
        print("Query started!")

##### Objects

In [1]:
# ( ! ) EVERYTHING IS AN OBJECT IN PYTHON !

# Object is an element which has "methods/functions" for programmers to use.

Name = "Ahmet"          # "Name" variable is is also an oobject because of it's methods.
print(*dir(Name), sep=" ")

# Classes makes us to be able to create an object/objects.

# To create an object:
import sqlite3, os

db = sqlite3.connect(":memory:")

class dbOp:
    db_location = dir(db)
    
    def connect_db():
        db_location = dir(db)    
        if db_location != "":
            print("Connection acquired!")

    def lost_db():
        if db.commit():
            print("Connection lost!")

    def query_db(): 
        print("Query started!")


dbObj = dbOp()
print("\n",dir(dbOp), sep="")           # In this output, "db_location" is an attribute but "connect_db()", "lost_db()" and "query_db()" are methods.

# In OOP; we call variables in a class "attribute" and functions "methods".

# When we create an object, we take the attributes and the methods of a class and assign them to an object. This process is called "instantiation".

__add__ __class__ __contains__ __delattr__ __dir__ __doc__ __eq__ __format__ __ge__ __getattribute__ __getitem__ __getnewargs__ __gt__ __hash__ __init__ __init_subclass__ __iter__ __le__ __len__ __lt__ __mod__ __mul__ __ne__ __new__ __reduce__ __reduce_ex__ __repr__ __rmod__ __rmul__ __setattr__ __sizeof__ __str__ __subclasshook__ capitalize casefold center count encode endswith expandtabs find format format_map index isalnum isalpha isascii isdecimal isdigit isidentifier islower isnumeric isprintable isspace istitle isupper join ljust lower lstrip maketrans partition removeprefix removesuffix replace rfind rindex rjust rpartition rsplit rstrip split splitlines startswith strip swapcase title translate upper zfill

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'connect_db', 'db_location', 'lost_db', 'query_db']

##### Use of the Classes

In [4]:
# When we want to use a class in a program, we can import it like a module.

import sqlite3, os

dbOOp = sqlite3.connect(":memory:")

class DataBase:

    location = dir(dbOOp)

    def state():
        if dir(dbOOp):
            print("Connection is found!")
        else:
            print("NO connection is found!")
    
    def connection_On():
        if dir(dbOOp):
            print("Connected!")
    
    def connection_Off():
        print("Connection is OFF!")

# When all the code above is saved as a ".py" file, we can import the class to any virtual enviroment/program with "import" to use it's properties.
# In this state of the code which is importing the ".py" file of the class, if we want to call the functions inside of the class (or aswe call "methods"), we will get an error.

DataBase.state()
DataBase.connection_Off()           # ERROR!     >>     TypeError: connection_Off() takes 0 positional arguments but 1 was given

Connection is found!
Connection is OFF!

##### "self" Keyword

In [2]:
# To be able to use any class's methods, we need to assign an extra parameter to the modules which programmers call "self".

import sqlite3, os

dbOOp = sqlite3.connect(":memory:")

class DataBase:

    location = dir(dbOOp)

    def state(self):
        if dir(dbOOp):
            print("Connection is found!")
        else:
            print("NO connection is found!")
    
    def connection_On(self):
        if dir(dbOOp):
            print("Connected!")
    
    def connection_Off(self):
        print("Connection is OFF!")

# Wtih "self" parameter, we can access to the methods of the object from outside of the class.

##### "\_\_init\_\_" Method

In [1]:
# We use "__init__" to define what the sytem will do when an intantiation is created.

class Ex:
    def __init__(self):
        print("Class is created.")

exObj = Ex()

Class is created.

##### Inheritance in Between Classes

In [ ]:
# When we create multiple classes, if e want to use any methods/attributes from a different class, we can doit as we please because of "inheritance" between classes. 
# This technicality is most useful when working on a long-term program.

class Employees:
    def __init__(self):
        self.Name = ""
        self.Age = ""
        self.diploma = ""

class DataScientist:
    def __init__(self):
        self.lang = []
        self.exp = ""

class AI_Engineer:
    def __init__(self):
        self.lang = []
        self.exp = ""
        self.projects = ""

# We can add the attributes from "Employees" class to any other class with inheritance.
# We can achiee this with using "Eemployees" as a parameter.

class Employees:
    def __init__(self):
        self.Name = ""
        self.Age = ""
        self.diploma = ""

class DataScientist(Employees):         # Inheritance
    def __init__(self):
        self.lang = []
        self.exp = ""

class AI_Engineer(Employees):         # Inheritance
    def __init__(self):
        self.lang = []
        self.exp = ""
        self.projects = ""

# With inheritance, other classes will have the attributes added from the "Employees" class.

##### Functional Programming

Functions are very important in Python. When we are programming, we can choose to use OOP or functional programming.
Functions are "first-level" objects.
There are different kind of functions. One of them is "stateless functions". The others are "top-level functions", "vectorial functions" and "anonymous functions".

Functional programming is more flexible and easier to use in different occasions.

##### Pure Functions

In [5]:
A = 5

def impureSum(x):
    return (x + A)

def pureSum(x, y):
    return (x + y)

impureSum(6)            # When we change A's value, the output will change.

A = 9
impureSum(6)            # This function is "impure" which means, it will be effected from any change.

pureSum(5, 6)           # This function is "pure" which means, it won't be effected by any change other than it's parameters.

11

##### Anonymous Functions

In [12]:
# We can create functions 

def oldSum(a, b):
    return a + b

print("oldSum() function's result: ", oldSum(3, 2))

newSum = lambda a, b: a + b
print("newSum() function which is created by \"lambda\"", newSum(3, 2))

listUnordered = [("b", 3),("a", 8),("d", 12),("c", 1)]

sorted(listUnordered, key = lambda x: x[1])         # List is sorted by it's 1st element.

oldSum() function's result:  5
newSum() function which is created by "lambda" 5

[('c', 1), ('b', 3), ('a', 8), ('d', 12)]

##### Vectorial Operations

In [16]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

a*b

# Numpy module is perfect for mathematical operations especially vectors/matrixes.

array([ 2,  6, 12, 20])

##### "map()", "filter()" and "reduce()"

In [5]:
# If a function can take any function/objects as parameter, it's called "first-class functions".

# "map()" function allows us to use an anon function on an object.
# map(<anon function>, <object>)

listNum = [1, 2, 3, 4, 5]

list(map(lambda x: x + 10, listNum))
#       (   <function>   , <vector>)

# "filter()" function
# "filter()" function allows us to extract the elements which proves the statements true from a given object to another newly created object.

listNum = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

list(filter(lambda x: x % 2 == 0, listNum))
#          (     <function>     , <object>)

# "reduce()" function
# "reduce()" from "functools" module allows us to reduce the output of the return object.

from functools import reduce

listNum = [1, 2, 3, 4, 5]
reduce(lambda a, b: a + b, listNum)
#     (    <function>    , <object>)

15

##### Creating a Module for Functional Programming

In [18]:
# We can create modules with many functions embedded in to use more efficiently.
# The first step of creating a module is, creating a new ".py" file.

import Calculate

salary = 5800
new_salary = Calculate.newSalary(5800)
print("New salary is :", new_salary)

# If we want a specific method in a module, we can import it without importing the module.

from Calculate import newSalary

salary = 8800
new_salary = Calculate.newSalary(salary)
print("New salary is :", new_salary)

# If module has an "attribute" we can get the value of them.

New salary is : 6960.0
New salary is : 10560.0

#### Data Manipulation with Python

##### Jupyter Lab

In [ ]:
# Jupyter Lab is a notebook extension for programmers. This file is a Jupyter notebook (.ipynb).

##### Numpy

In [4]:
import numpy as np
dir(np)

a = np.array([1,2,3,4])          # "np.array(<list of elements>)" is used to create an array.
b = np.array([2,3,4,5])
print("Multiplication of the two arrays: ", a*b)

# With Numpy, we could register more data with arrays better than lists. The data will take up less space and operations will be more fluent.

Multiplication of the two arrays:  [ 2  6 12 20]

##### Creating A Numpy Array

In [34]:
# We can create an array with a list of elements. "np.array(<list of elements>)" is used to create an array.
import numpy as np

arrayA = np.array([1,2,3,4])
print("arryA: ", arrayA, "Type: ", type(arrayA), sep="\t")         # <class 'numpy.ndarray'>

# Array's elements will be the same data type.
arrayB = np.array([3.14, 2, 6, 12])
print("arrayB: ", arrayB)           # [ 3.14  2.    6.   12.  ] (All the elements is the same type (float))
print("Type of the elements in arrayB", type(arrayB[0]))            # All the elements is the same type "<class 'numpy.float64'>".

# We can change the type of the elements of an existing array, we can use "dtype".
np.array([3.14, 2, 6, 12], dtype="int")

zeros = np.zeros(4, dtype="int")         # np.ones/zeros(<rows, columns>)
ones = np.ones(4, dtype="int")
print("ones: ", ones, "\nzeros: ", zeros)

import random
randInt = random.randint(0, 10)
randArray = np.ones((randInt, randInt), dtype="int")
print("Random sized Array of ones: \n", randArray)

# To create an array which is consists of any given number, we use "np.full()".
intArray = np.full((3,3), 7, dtype="int")
print("Array which is consists of any given number: \n", intArray)

controlledArray = np.arange(0, 50, 2)
print("Array with controlled steps: \n", controlledArray)

# To create an array which is between two integers with a given space between space we use "np.linspace(<start>, <stop>, <number of elements>)"
linspaceArray = np.linspace(0,10,20)
print("Array with defined start/stop and number of elements: \n", linspaceArray)

# ( ! ) For the other ways to create an array, we can execute the "dir(np)" command.
dir(np)

arryA: 	[1 2 3 4]	Type: 	<class 'numpy.ndarray'>
arrayB:  [ 3.14  2.    6.   12.  ]
Type of the elements in arrayB <class 'numpy.float64'>
ones:  [1 1 1 1]
zeros:  [0 0 0 0]
Random sized Array of ones:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Array which is consists of any given number:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Array with controlled steps:
 [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
Array with defined start/stop and number of elements:
 [ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distributor_init',
 '_financial_names',
 '_globals',
 '_mat',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_version',
 'abs',
 'absolute',
 'add',
 'add_docstring',
 'add_newdoc',
 'add_newdoc_ufunc',
 'all',
 'allclose',
 'alltrue',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'array2string',
 'array_equal',
 'array_equiv',
 'array_repr',
 'array_split',
 'array_str',
 'asanyarray',
 'asarray',
 'asarray_chkfinite',
 'ascontiguousarray',
 'asfarray',
 'asfortranarray',
 'asmatrix',
 'atleast_1d',
 'atleast_2d',
 'atleast_3d',
 'average',
 'bartlett',
 'base_repr',
 'binary_repr',
 'bincount',
 'bitwise_and',
 'bitwise_not',
 'bitwise_or',
 'bitwise_xor',
 'blackman',
 'block',
 'bmat',
 'bool8',
 'bool_',
 'broadcast',
 'broadcast_arrays',
 'broadcast_shapes',
 'broadcast_to',
 'busday_count',
 'busday_offset',
 'busdaycalendar',
 'byte',
 'byte_bounds',
 'bytes0',
 'bytes_',
 'c_',
 'can_cast',
 'cast',
 'cbrt',
 'cdouble',
 'ceil',
 'cfloat',
 'char',
 'character',
 'chararray',
 'choose',
 'clip',
 'clongdouble',
 'clongfloat',
 'column_stack',
 'common_type',
 'compare_chararrays',
 'compat',
 'complex128',
 'complex64',
 'complex_',
 'complexfloating',
 'compress',
 'concatenate',
 'conj',
 'conjugate',
 'convolve',
 'copy',
 'copysign',
 'copyto',
 'core',
 'corrcoef',
 'correlate',
 'cos',
 'cosh',
 'count_nonzero',
 'cov',
 'cross',
 'csingle',
 'ctypeslib',
 'cumprod',
 'cumproduct',
 'cumsum',
 'datetime64',
 'datetime_as_string',
 'datetime_data',
 'deg2rad',
 'degrees',
 'delete',
 'deprecate',
 'deprecate_with_doc',
 'diag',
 'diag_indices',
 'diag_indices_from',
 'diagflat',
 'diagonal',
 'diff',
 'digitize',
 'disp',
 'divide',
 'divmod',
 'dot',
 'double',
 'dsplit',
 'dstack',
 'dtype',
 'e',
 'ediff1d',
 'einsum',
 'einsum_path',
 'emath',
 'empty',
 'empty_like',
 'equal',
 'errstate',
 'euler_gamma',
 'exp',
 'exp2',
 'expand_dims',
 'expm1',
 'extract',
 'eye',
 'fabs',
 'fastCopyAndTranspose',
 'fft',
 'fill_diagonal',
 'find_common_type',
 'finfo',
 'fix',
 'flatiter',
 'flatnonzero',
 'flexible',
 'flip',
 'fliplr',
 'flipud',
 'float16',
 'float32',
 'float64',
 'float_',
 'float_power',
 'floating',
 'floor',
 'floor_divide',
 'fmax',
 'fmin',
 'fmod',
 'format_float_positional',
 'format_float_scientific',
 'format_parser',
 'frexp',
 'from_dlpack',
 'frombuffer',
 'fromfile',
 'fromfunction',
 'fromiter',
 'frompyfunc',
 'fromregex',
 'fromstring',
 'full',
 'full_like',
 'gcd',
 'generic',
 'genfromtxt',
 'geomspace',
 'get_array_wrap',
 'get_include',
 'get_printoptions',
 'getbufsize',
 'geterr',
 'geterrcall',
 'geterrobj',
 'gradient',
 'greater',
 'greater_equal',
 'half',
 'hamming',
 'hanning',
 'heaviside',
 'histogram',
 'histogram2d',
 'histogram_bin_edges',
 'histogramdd',
 'hsplit',
 'hstack',
 'hypot',
 'i0',
 'identity',
 'iinfo',
 'imag',
 'in1d',
 'index_exp',
 'indices',
 'inexact',
 'inf',
 'info',
 'infty',
 'inner',
 'insert',
 'int0',
 'int16',
 'int32',
 'int64',
 'int8',
 'int_',
 'intc',
 'integer',
 'interp',
 'intersect1d',
 'intp',
 'invert',
 'is_busday',
 'isclose',
 'iscomplex',
 'iscomplexobj',
 'isfinite',
 'isfortran',
 'isin',
 'isinf',
 'isnan',
 'isnat',
 'isneginf',
 'isposinf',
 'isreal',
 'isrealobj',
 'isscalar',
 'issctype',
 'issubclass_',
 'issubdtype',
 'issubsctype',
 'iterable',
 'ix_',
 'kaiser',
 'kron',
 'lcm',
 'ldexp',
 'left_shift',
 'less',
 'less_equal',
 'lexsort',
 'lib',
 'linalg',
 'linspace',
 'little_endian',
 'load',
 'loadtxt',
 'log',
 'log10',
 'log1p',
 'log2',
 'logaddexp',
 'logaddexp2',
 'logical_and',
 'logical_not',
 'logical_or',
 'logical_xor',
 'logspace',
 'longcomplex',
 'longdouble',
 'longfloat',
 'longlong',
 'lookfor',
 'ma',
 'mask_indices',
 'mat',
 'math',
 'matmul',
 'matrix',
 'matrixlib',
 'max',
 'maximum',
 'maximum_sctype',
 'may_share_memory',
 'mean',
 'median',
 'memmap',
 'meshgrid',
 'mgrid',
 'min',
 'min_scalar_type',
 'minimum',
 'mintypecode',
 'mod',
 'modf',
 'moveaxis',
 'msort',
 'multiply',
 'nan',
 'nan_to_num',
 'nanargmax',
 'nanargmin',
 'nancumprod',
 'nancumsum',
 'nanmax',
 'nanmean',
 'nanmedian',
 'nanmin',
 'nanpercentile',
 'nanprod',
 'nanquantile',
 'nanstd',
 'nansum',
 'nanvar',
 'nbytes',
 'ndarray',
 'ndenumerate',
 'ndim',
 'ndindex',
 'nditer',
 'negative',
 'nested_iters',
 'newaxis',
 'nextafter',
 'nonzero',
 'not_equal',
 'numarray',
 'number',
 'obj2sctype',
 'object0',
 'object_',
 'ogrid',
 'oldnumeric',
 'ones',
 'ones_like',
 'os',
 'outer',
 'packbits',
 'pad',
 'partition',
 'percentile',
 'pi',
 'piecewise',
 'place',
 'poly',
 'poly1d',
 'polyadd',
 'polyder',
 'polydiv',
 'polyfit',
 'polyint',
 'polymul',
 'polynomial',
 'polysub',
 'polyval',
 'positive',
 'power',
 'printoptions',
 'prod',
 'product',
 'promote_types',
 'ptp',
 'put',
 'put_along_axis',
 'putmask',
 'quantile',
 'r_',
 'rad2deg',
 'radians',
 'random',
 'ravel',
 'ravel_multi_index',
 'real',
 'real_if_close',
 'rec',
 'recarray',
 'recfromcsv',
 'recfromtxt',
 'reciprocal',
 'record',
 'remainder',
 'repeat',
 'require',
 'reshape',
 'resize',
 'result_type',
 'right_shift',
 'rint',
 'roll',
 'rollaxis',
 'roots',
 'rot90',
 'round',
 'round_',
 'row_stack',
 's_',
 'safe_eval',
 'save',
 'savetxt',
 'savez',
 'savez_compressed',
 'sctype2char',
 'sctypeDict',
 'sctypes',
 'searchsorted',
 'select',
 'set_numeric_ops',
 'set_printoptions',
 'set_string_function',
 'setbufsize',
 'setdiff1d',
 'seterr',
 'seterrcall',
 'seterrobj',
 'setxor1d',
 'shape',
 'shares_memory',
 'short',
 'show_config',
 'sign',
 'signbit',
 'signedinteger',
 'sin',
 'sinc',
 'single',
 'singlecomplex',
 'sinh',
 'size',
 'sometrue',
 'sort',
 'sort_complex',
 'source',
 'spacing',
 'split',
 'sqrt',
 'square',
 'squeeze',
 'stack',
 'std',
 'str0',
 'str_',
 'string_',
 'subtract',
 'sum',
 'swapaxes',
 'sys',
 'take',
 'take_along_axis',
 'tan',
 'tanh',
 'tensordot',
 'test',
 'testing',
 'tile',
 'timedelta64',
 'trace',
 'tracemalloc_domain',
 'transpose',
 'trapz',
 'tri',
 'tril',
 'tril_indices',
 'tril_indices_from',
 'trim_zeros',
 'triu',
 'triu_indices',
 'triu_indices_from',
 'true_divide',
 'trunc',
 'typecodes',
 'typename',
 'ubyte',
 'ufunc',
 'uint',
 'uint0',
 'uint16',
 'uint32',
 'uint64',
 'uint8',
 'uintc',
 'uintp',
 'ulonglong',
 'unicode_',
 'union1d',
 'unique',
 'unpackbits',
 'unravel_index',
 'unsignedinteger',
 'unwrap',
 'use_hugepage',
 'ushort',
 'vander',
 'var',
 'vdot',
 'vectorize',
 'version',
 'void',
 'void0',
 'vsplit',
 'vstack',
 'warnings',
 'where',
 'who',
 'zeros',
 'zeros_like']

##### Properties of Arrays

In [12]:
# Numpy array has different properties such as;
# 1.) ndim: Dimensions of the array. (vector or matrix)
# 2.) shape: Shape of the array. (m x n)
# 3.) size: Size of the array. (Number of elements)
# 4.) dtype: Data type of the array's elements.

import numpy as np

arrayA = np.random.randint(10, size = 10)           # Vector (One-dimensional Array)
print(arrayA)

dictProp = {"Dimensions": arrayA.ndim, "Shape": arrayA.shape, "Size": arrayA.size, "Data Type": arrayA.dtype}

for prop, value in dictProp.items():
    print(f"{prop}: {value}")

arrayB = np.random.randint(10, size = (3,5))
print("\n", arrayB, sep="")

dictProp2 = {"Dimensions": arrayB.ndim, "Shape": arrayB.shape, "Size": arrayB.size, "Data Type": arrayB.dtype}

for prop, value in dictProp2.items():
    print(f"{prop}: {value}")

[2 2 0 0 0 4 2 4 8 2]
Dimensions: 1
Shape: (10,)
Size: 10
Data Type: int32

[[8 4 2 2 7]
 [6 8 8 3 5]
 [1 5 3 2 7]]
Dimensions: 2
Shape: (3, 5)
Size: 15
Data Type: int32

##### Reshaping an Array

In [16]:
# We can reshape an existing array with "reshape()" method.

import numpy as np

arrayEx = np.arange(1, 10)
print("Example array: ", arrayEx)

arrayReshaped = arrayEx.reshape((3, 3))
print("Reshaped array: ", arrayReshaped, sep = "\n")

Example array:  [1 2 3 4 5 6 7 8 9]
Reshaped array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

##### Concatenation in Arrays

In [33]:
# Concatenation is an operation that we use to combine two arrays together.

import numpy as np

arrayX = np.array([1, 2, 3])
arrayY = np.array([4, 5, 6])

arrayCon_v1 = np.concatenate([arrayX, arrayY])
arrayCon_v2 = np.concatenate([arrayY, arrayX])

print(">> After two different concatenation:", arrayCon_v1, arrayCon_v2, sep = "\n")

# This method's behaviour changes when implied to two dimensioned arrays.

arrayA = np.array([[1, 2, 3], [4, 5, 6]])
arrayB = np.array([[7, 8, 9]])

print("\n>> Concatenation in two dimensions:", arrayA, "", arrayB, sep = "\n")

arrayC = np.concatenate([arrayA, arrayB])
print("\nAfter concatenation: ", arrayC, sep = "\n")

# For different concatenation (based of columns);
arrayColmn = np.concatenate([arrayA, arrayA], axis = 1)         # axis = 0 (based on line) / 1 (based on column)
print("\nAfter concatenation (based on columns):", arrayColmn, sep = "\n")          #  [1 2 3]   +   [1 2 3]   =   [1 2 3 1 2 3]
#                                                                                      [4 5 6]       [4 5 6]       [4 5 6 4 5 6]

>> After two different concatenation:
[1 2 3 4 5 6]
[4 5 6 1 2 3]

>> Concatenation in two dimensions:
[[1 2 3]
 [4 5 6]]

[[7 8 9]]

After concatenation:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After concatenation (based on columns):
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]

##### Splitting an Array

In [12]:
# In some occasions, we want to split an existing array to different arrays. To achieve this, we use "split()".

import numpy as np

arrayA = np.array([1, 2, 3, 99, 99, 3, 2, 1])

arraySplit = np.split(arrayA, [3, 5])            # Splits from 3rd element to 5th ([99, 99])
print(arraySplit)

# To use the splitted arrays, we can define a variable for them.

arrayA1, arrayA2, arrayA3 = np.split(arrayA, [3, 5])
print(f"{arrayA1 = }\n{arrayA2 = }\n{arrayA3 = } ")

# The process a bit different for two-dimensioned arrays.
    # Vertical Splitting ( vsplit(<array>, <index>) )
arrayS = np.arange(16).reshape(4, 4)
print("\nArrayS: ", arrayS)
arrayS_v = np.vsplit(arrayS, [2])           # index : [2]    >>    between [0,2]
print("\nVertically-split arrayS: ", *arrayS_v, sep="\n")           # [0 1 2 3]
#                                                                     [4 5 6 7]
#                                                                          
#                                                                     [ 8  9 10 11]
#                                                                     [12 13 14 15]

arrayS_h = np.hsplit(arrayS, [2])           # index : [2]    >>    between [0,2]
print("\nHorizontally-split arrayS: ", *arrayS_h, sep="\n")         # [ 0  1]       [ 2  3] 
#                                                                     [ 4  5]       [ 6  7]       
#                                                                     [ 8  9]       [10 11]
#                                                                     [12 13]       [14 15]

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]
arrayA1 = array([1, 2, 3])
arrayA2 = array([99, 99])
arrayA3 = array([3, 2, 1])

ArrayS:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Vertically-split arrayS:
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]

Horizontally-split arrayS:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

##### Sorting an Array

In [23]:
# We can sort an array with "np.sort()" method.
import numpy as np

arraySort = np.random.randint(0, 20, (4, 4))
print("arraySort: ", arraySort, sep = "\n")

arraySortedVer = np.sort(arraySort, axis = 0)
print("\nSorted vertically (based on columns): ", arraySortedVer, sep = "\n")
arraySortedHor = np.sort(arraySort, axis = 1)
print("\nSorted horizontally (based on lines): ", arraySortedHor, sep = "\n")

arraySort:
[[ 5  5  7 12]
 [11 18  3 15]
 [16 19  7  7]
 [ 0 19  0 10]]

Sorted vertically (based on columns):
[[ 0  5  0  7]
 [ 5 18  3 10]
 [11 19  7 12]
 [16 19  7 15]]

Sorted horizontally (based on lines):
[[ 5  5  7 12]
 [ 3 11 15 18]
 [ 7  7 16 19]
 [ 0  0 10 19]]

##### Accesing the Data in Arrays

In [43]:
# We can access any data in an existing array.
import numpy as np

arrayX = np.random.randint(0, 10, [8])
print("arrayX: ", arrayX, sep = "\n")

for i in range(8):
    print(arrayX[i])            # arrayX[<index>]

arrayXY = np.random.randint(0, 10, (4, 4))
print("\narrayXY: ", arrayXY, sep = "\n")

print(arrayXY[0, 0])
print(arrayXY[2, 3])

arrayX:
[6 9 9 2 2 8 2 9]
6
9
9
2
2
8
2
9

arrayXY:
[[5 6 9 2]
 [2 1 6 3]
 [7 6 1 7]
 [9 5 4 2]]
5
7

##### Using "Fancy Indexing"

In [7]:
# To gather elements more efficiently, we can use fancy indexing. With fancy indexing, we can input a list of indexes to get from an array.
import numpy as np

arrayF = np.arange(0, 30, 3)
print("arrayF: ", arrayF, sep  = "\n")

listToGet = [0, 3, 4, 5]
print("Gathered elements with fancy indexing: ", arrayF[listToGet])         # [   0         9        12         15    ]
#                                                                             [arrayF[0] arrayF[3] arrayF[4] arrayF[5]]

# Fancy Indexing can be used for two-dimensioned arrays as well.

arrayV = np.random.randint(0, 20, size = (4, 4))
print("\narrayV: ", arrayV, sep = "\n")

lineBased = np.array([0, 1])
columnBased = np.array([1, 2])
print("Gathered elements with fancy indexing: ", arrayV[lineBased, columnBased])            #  [ 7 14  8 10]    With the given input: [ arrayV[0, 1] arrayV[1, 2] ]
#                                                                                              [ 7  1  0 19]                          [       14           0      ]
#                                                                                              [ 4  6  5  7]
#                                                                                              [18  3 18  4]

arrayF:
[ 0  3  6  9 12 15 18 21 24 27]
Gathered elements with fancy indexing:  [ 0  9 12 15]

arrayV:
[[ 7 14  8 10]
 [ 7  1  0 19]
 [ 4  6  5  7]
 [18  3 18  4]]
Gathered elements with fancy indexing:  [14  0]

##### Combined Indexing

In [10]:
# For even more powerful operations, fancy indexing can be combined with the other indexing schemes.

arrayX = np.arange(12).reshape((3, 4))
print("arrayX: ", arrayX, sep  ="\n")

print("\nResult with basic + fancy indexing: ", arrayX[2, [2, 0, 1]], sep = "\n")

print("\nResults with slicing + fancy indexing: ", arrayX[1:, [2, 0, 1]], sep = "\n")

arrayX:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Result with basic + fancy indexing:
[10  8  9]

Results with slicing + fancy indexing:
[[ 6  4  5]
 [10  8  9]]

##### Conditional Operations for Array Elements

In [3]:
# We can check whether an array's elements supports any conditions or not.

import numpy as np

arrayCon = np.array([1, 2, 3, 4])
print("Elements which are less than 3: ", arrayCon < 3)

# To get the elements which supports any conditions, we need to use an array indexing.

arrayCon[arrayCon < 3]

Elements which are less than 3:  [ True  True False False]

array([1, 2])

##### Mathematical Operations for Arrays

In [9]:
# We can do the basic math opertions with arrays.
import numpy as np

arrayM = np.array([1, 2, 3, 4])

print(arrayM + 1)
print(arrayM - 1)
print(arrayM*2)
print(arrayM/2)
print(arrayM**2)

# All these operations happens because of the "ufunc".

np.add(arrayM, 1)           # Equivalent to "arrayM + 1"
np.subtract(arrayM, 1)          # Equivalent to "arrayM - 1"
np.multiply(arrayM, 2)          # Equivalent to "arrayM * 2"
np.divide(arrayM, 2)            # Equivalent to "arrayM / 2"
np.power(arrayM, 2)         # Equivalent to "arrayM ** 2"

# To learn more about available mathematical/statistical operations, we can use "dir(np)".
dir(np)

# ( ! ) It's important to prepare a "cheatsheet" for important modules such as "random", "numpy" or "cmath".

[2 3 4 5]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distributor_init',
 '_financial_names',
 '_globals',
 '_mat',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_version',
 'abs',
 'absolute',
 'add',
 'add_docstring',
 'add_newdoc',
 'add_newdoc_ufunc',
 'all',
 'allclose',
 'alltrue',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'array2string',
 'array_equal',
 'array_equiv',
 'array_repr',
 'array_split',
 'array_str',
 'asanyarray',
 'asarray',
 'asarray_chkfinite',
 'ascontiguousarray',
 'asfarray',
 'asfortranarray',
 'asmatrix',
 'atleast_1d',
 'atleast_2d',
 'atleast_3d',
 'average',
 'bartlett',
 'base_repr',
 'binary_repr',
 'bincount',
 'bitwise_and',
 'bitwise_not',
 'bitwise_or',
 'bitwise_xor',
 'blackman',
 'block',
 'bmat',
 'bool8',
 'bool_',
 'broadcast',
 'broadcast_arrays',
 'broadcast_shapes',
 'broadcast_to',
 'busday_count',
 'busday_offset',
 'busdaycalendar',
 'byte',
 'byte_bounds',
 'bytes0',
 'bytes_',
 'c_',
 'can_cast',
 'cast',
 'cbrt',
 'cdouble',
 'ceil',
 'cfloat',
 'char',
 'character',
 'chararray',
 'choose',
 'clip',
 'clongdouble',
 'clongfloat',
 'column_stack',
 'common_type',
 'compare_chararrays',
 'compat',
 'complex128',
 'complex64',
 'complex_',
 'complexfloating',
 'compress',
 'concatenate',
 'conj',
 'conjugate',
 'convolve',
 'copy',
 'copysign',
 'copyto',
 'core',
 'corrcoef',
 'correlate',
 'cos',
 'cosh',
 'count_nonzero',
 'cov',
 'cross',
 'csingle',
 'ctypeslib',
 'cumprod',
 'cumproduct',
 'cumsum',
 'datetime64',
 'datetime_as_string',
 'datetime_data',
 'deg2rad',
 'degrees',
 'delete',
 'deprecate',
 'deprecate_with_doc',
 'diag',
 'diag_indices',
 'diag_indices_from',
 'diagflat',
 'diagonal',
 'diff',
 'digitize',
 'disp',
 'divide',
 'divmod',
 'dot',
 'double',
 'dsplit',
 'dstack',
 'dtype',
 'e',
 'ediff1d',
 'einsum',
 'einsum_path',
 'emath',
 'empty',
 'empty_like',
 'equal',
 'errstate',
 'euler_gamma',
 'exp',
 'exp2',
 'expand_dims',
 'expm1',
 'extract',
 'eye',
 'fabs',
 'fastCopyAndTranspose',
 'fft',
 'fill_diagonal',
 'find_common_type',
 'finfo',
 'fix',
 'flatiter',
 'flatnonzero',
 'flexible',
 'flip',
 'fliplr',
 'flipud',
 'float16',
 'float32',
 'float64',
 'float_',
 'float_power',
 'floating',
 'floor',
 'floor_divide',
 'fmax',
 'fmin',
 'fmod',
 'format_float_positional',
 'format_float_scientific',
 'format_parser',
 'frexp',
 'from_dlpack',
 'frombuffer',
 'fromfile',
 'fromfunction',
 'fromiter',
 'frompyfunc',
 'fromregex',
 'fromstring',
 'full',
 'full_like',
 'gcd',
 'generic',
 'genfromtxt',
 'geomspace',
 'get_array_wrap',
 'get_include',
 'get_printoptions',
 'getbufsize',
 'geterr',
 'geterrcall',
 'geterrobj',
 'gradient',
 'greater',
 'greater_equal',
 'half',
 'hamming',
 'hanning',
 'heaviside',
 'histogram',
 'histogram2d',
 'histogram_bin_edges',
 'histogramdd',
 'hsplit',
 'hstack',
 'hypot',
 'i0',
 'identity',
 'iinfo',
 'imag',
 'in1d',
 'index_exp',
 'indices',
 'inexact',
 'inf',
 'info',
 'infty',
 'inner',
 'insert',
 'int0',
 'int16',
 'int32',
 'int64',
 'int8',
 'int_',
 'intc',
 'integer',
 'interp',
 'intersect1d',
 'intp',
 'invert',
 'is_busday',
 'isclose',
 'iscomplex',
 'iscomplexobj',
 'isfinite',
 'isfortran',
 'isin',
 'isinf',
 'isnan',
 'isnat',
 'isneginf',
 'isposinf',
 'isreal',
 'isrealobj',
 'isscalar',
 'issctype',
 'issubclass_',
 'issubdtype',
 'issubsctype',
 'iterable',
 'ix_',
 'kaiser',
 'kron',
 'lcm',
 'ldexp',
 'left_shift',
 'less',
 'less_equal',
 'lexsort',
 'lib',
 'linalg',
 'linspace',
 'little_endian',
 'load',
 'loadtxt',
 'log',
 'log10',
 'log1p',
 'log2',
 'logaddexp',
 'logaddexp2',
 'logical_and',
 'logical_not',
 'logical_or',
 'logical_xor',
 'logspace',
 'longcomplex',
 'longdouble',
 'longfloat',
 'longlong',
 'lookfor',
 'ma',
 'mask_indices',
 'mat',
 'math',
 'matmul',
 'matrix',
 'matrixlib',
 'max',
 'maximum',
 'maximum_sctype',
 'may_share_memory',
 'mean',
 'median',
 'memmap',
 'meshgrid',
 'mgrid',
 'min',
 'min_scalar_type',
 'minimum',
 'mintypecode',
 'mod',
 'modf',
 'moveaxis',
 'msort',
 'multiply',
 'nan',
 'nan_to_num',
 'nanargmax',
 'nanargmin',
 'nancumprod',
 'nancumsum',
 'nanmax',
 'nanmean',
 'nanmedian',
 'nanmin',
 'nanpercentile',
 'nanprod',
 'nanquantile',
 'nanstd',
 'nansum',
 'nanvar',
 'nbytes',
 'ndarray',
 'ndenumerate',
 'ndim',
 'ndindex',
 'nditer',
 'negative',
 'nested_iters',
 'newaxis',
 'nextafter',
 'nonzero',
 'not_equal',
 'numarray',
 'number',
 'obj2sctype',
 'object0',
 'object_',
 'ogrid',
 'oldnumeric',
 'ones',
 'ones_like',
 'os',
 'outer',
 'packbits',
 'pad',
 'partition',
 'percentile',
 'pi',
 'piecewise',
 'place',
 'poly',
 'poly1d',
 'polyadd',
 'polyder',
 'polydiv',
 'polyfit',
 'polyint',
 'polymul',
 'polynomial',
 'polysub',
 'polyval',
 'positive',
 'power',
 'printoptions',
 'prod',
 'product',
 'promote_types',
 'ptp',
 'put',
 'put_along_axis',
 'putmask',
 'quantile',
 'r_',
 'rad2deg',
 'radians',
 'random',
 'ravel',
 'ravel_multi_index',
 'real',
 'real_if_close',
 'rec',
 'recarray',
 'recfromcsv',
 'recfromtxt',
 'reciprocal',
 'record',
 'remainder',
 'repeat',
 'require',
 'reshape',
 'resize',
 'result_type',
 'right_shift',
 'rint',
 'roll',
 'rollaxis',
 'roots',
 'rot90',
 'round',
 'round_',
 'row_stack',
 's_',
 'safe_eval',
 'save',
 'savetxt',
 'savez',
 'savez_compressed',
 'sctype2char',
 'sctypeDict',
 'sctypes',
 'searchsorted',
 'select',
 'set_numeric_ops',
 'set_printoptions',
 'set_string_function',
 'setbufsize',
 'setdiff1d',
 'seterr',
 'seterrcall',
 'seterrobj',
 'setxor1d',
 'shape',
 'shares_memory',
 'short',
 'show_config',
 'sign',
 'signbit',
 'signedinteger',
 'sin',
 'sinc',
 'single',
 'singlecomplex',
 'sinh',
 'size',
 'sometrue',
 'sort',
 'sort_complex',
 'source',
 'spacing',
 'split',
 'sqrt',
 'square',
 'squeeze',
 'stack',
 'std',
 'str0',
 'str_',
 'string_',
 'subtract',
 'sum',
 'swapaxes',
 'sys',
 'take',
 'take_along_axis',
 'tan',
 'tanh',
 'tensordot',
 'test',
 'testing',
 'tile',
 'timedelta64',
 'trace',
 'tracemalloc_domain',
 'transpose',
 'trapz',
 'tri',
 'tril',
 'tril_indices',
 'tril_indices_from',
 'trim_zeros',
 'triu',
 'triu_indices',
 'triu_indices_from',
 'true_divide',
 'trunc',
 'typecodes',
 'typename',
 'ubyte',
 'ufunc',
 'uint',
 'uint0',
 'uint16',
 'uint32',
 'uint64',
 'uint8',
 'uintc',
 'uintp',
 'ulonglong',
 'unicode_',
 'union1d',
 'unique',
 'unpackbits',
 'unravel_index',
 'unsignedinteger',
 'unwrap',
 'use_hugepage',
 'ushort',
 'vander',
 'var',
 'vdot',
 'vectorize',
 'version',
 'void',
 'void0',
 'vsplit',
 'vstack',
 'warnings',
 'where',
 'who',
 'zeros',
 'zeros_like']

##### Introduction to Pandas

In [1]:
# Pandas is frequently used in data science/AI/ML fields. It's shortened from "panel data" to "Pandas". Panel data, a data type which is multi-dimensional data type involving measurements over time.
#It's mostly used in economics and finance because of the alternatives over arrays and existing methods.

# "Dataframe" is frequently used when navigating through/using "Pandas".

##### Creating a Pandas Series

In [ ]:
# Dataframes is a type of data which is frequently used in Pandas. Dataframes are pretty similar to arrays except they include an index value for the values as well.
    # ( ! ) Downloading the library "pip install pandas".

import pandas as pd

pd_series = pd.Series([100, 50, 9, 123, 67])
print("Newly created pandas series:", pd_series, sep = "\n")         # 0    100          on the first column: index values
#                                                                      1     50          on the second column: elements
#                                                                      2      9
#                                                                      3    123
#                                                                      4     67
#                                                                     dtype: int64
type(pd_series)

print(["Index Information: ", pd_series.axes], ["Values data type: ", pd_series.dtype], ["Size: ", pd_series.size], ["Dimension: ", pd_series.ndim], sep = "\n")

# We can separate the values as an "array" with ".values()" method.
print("Values: ", pd_series.values, type(pd_series.values))

##### Changing the Indexes of Values

In [33]:
series_A = pd.Series([99, 22, 332, 94, 5])

# We can define the indexes manually with emphasising the parameter "index".

series_A = pd.Series([24, 2024, 4800, 8800], index = ["Age", "Diploma Year", "Current Revenue", "Future Revenue"])           # Indexes can be a different data type than "int" as well.
print("Pandas Series with Manual Index: ", series_A, sep = "\n")

# We can pull out the values with indexes.
series_A["Age"]

# We can use "slicing" as well.
series_A["Age": "Current Revenue"]

# We can use dictionaries to create a pandas series.
series_X = pd.Series({"Name": "Ahmet", "Surname": "SERÇE", "Age": 24, "Married": False})
print("\nPandas Series which is created by using a dictionary: ", series_X, sep = "\n")

Pandas Series with Manual Index:
Age                  24
Diploma Year       2024
Current Revenue    4800
Future Revenue     8800
dtype: int64

Pandas Series which is created by using a dictionary:
Name       Ahmet
Surname    SERÇE
Age           24
Married    False
dtype: object

##### Concatenating Pandas Series

In [38]:
# We can concatenate two or more pandas series together with "concat()" method.
series_AX = pd.concat([series_X, series_A[1:]])         # ( ! ) We use "[]" when concatenating series.
print("Concatenated series: ", series_AX, sep = "\n")

Concatenated series:
Name               Ahmet
Surname            SERÇE
Age                   24
Married            False
Diploma Year        2024
Current Revenue     4800
Future Revenue      8800
dtype: object

##### Operations in a Pandas Series

In [45]:
import numpy as np

array_A = np.array([1, 2, 33, 45, 54, 75])
print("Array:", array_A)
series_A = pd.Series(array_A)
print("\nSeries:", series_A, sep = "\n")

# Slicing in series
print("\nSliced series:", series_A[0:3], sep = "\n")

Array: [ 1  2 33 45 54 75]

Series:
0     1
1     2
2    33
3    45
4    54
5    75
dtype: int32

Sliced series:
0     1
1     2
2    33
dtype: int32

In [57]:
new_series = pd.Series([121, 200, 150, 99], index = ["reg", "log", "cart", "rf"])
print("New Series:", new_series, sep = "\n")

new_series.index
new_series.keys
list(new_series.items())
new_series.values

# Interrogation of Values
"reg" in new_series         # Output   >>   True
"a" in new_series           # Output   >>   False

# Changing the Values
new_series["reg"] = 130
print("\nNew Series after change:", new_series, sep = "\n")

New Series:
reg     121
log     200
cart    150
rf       99
dtype: int64

New Series after change:
reg     130
log     200
cart    150
rf       99
dtype: int64

##### Creating a Dataframe with Pandas

In [19]:
# Why we should use a dataframe instead of a numpy array?
    # Numpy arrays supports a fixed data type which means we can only work with numbers. With dataframes, we have the ability to "tag" the information with custom indexes.
    # This is a critical behaviour for AI/ML models.

# To create a dataframe, we use ".DataFrame()" method.

import pandas as pd
import numpy as np

list_of_num = [12, 32, 48, 56, 22, 89]
dataFrame = pd.DataFrame(list_of_num, columns = ["Variables"])
print("Created dataframe:", dataFrame, sep  = "\n")
print("Type: ", type(dataFrame))

# We can store different kind of values in a dataframe. It's pretty similar to arrays with some differences.

print("\nValues:", dataFrame.values, sep = "\n")
print("Value type: ", type(dataFrame.values))
print("Dimension: ", dataFrame.ndim)
print("Shape: ", dataFrame.shape)
print("Size: ", dataFrame.size)
print("Axes: ", dataFrame.axes)

# We can change the columns of an existing dataframe.
dataFrame.columns = ["Results"]
print("\nDataframe after the column change:", dataFrame, sep = "\n")

Created dataframe:
   Variables
0         12
1         32
2         48
3         56
4         22
5         89
Type:  <class 'pandas.core.frame.DataFrame'>

Values:
[[12]
 [32]
 [48]
 [56]
 [22]
 [89]]
Value type:  <class 'numpy.ndarray'>
Dimension:  2
Shape:  (6, 1)
Size:  6
Axes:  [RangeIndex(start=0, stop=6, step=1), Index(['Variables'], dtype='object')]

Dataframe after the column change:
   Results
0       12
1       32
2       48
3       56
4       22
5       89

##### Operations with a DataFrame

In [3]:
# Operations for a dataframe is quite similar to a pandas series but with some differences.

import numpy as np
import pandas as pd

# We can create a dataframe with a dictionary.
array_1 = np.random.randint(10, size = 5)
array_2 = np.random.randint(10, size = 5)
array_3 = np.random.randint(10, size = 5)
print("Created arrays:", array_1, array_2, array_3, sep = "\n")

dict_X = {"Var1": array_1, "Var2": array_2, "Var3": array_3}

dataFrame_X = pd.DataFrame(dict_X)
print("\nCreated dataframe using dictionary:", dataFrame_X, sep = "\n")         # Keys are "column names", key values are "values".

# We can use "slicing" as well.
print("\nSlice:", dataFrame_X[0:1])

# We can change the indexes of a dataframe.
dataFrame_X.index = ["a", "b", "c", "d", "e"]
print("\nDataframe with different indexes:", dataFrame_X, sep = "\n")
print("\nSlice with new indexes:", dataFrame_X["a":"c"], sep = "\n")

# We can delete any index values, we can use ".drop()" method.
dataFrame_X.drop("a", axis = 0, inplace = True)         # "inplace" parameter makes the changes permanent.
print("\nAfter removing \"a\" row:", dataFrame_X, sep = "\n")

Created arrays:
[7 9 6 2 3]
[1 1 0 7 4]
[0 9 0 3 1]

Created dataframe using dictionary:
   Var1  Var2  Var3
0     7     1     0
1     9     1     9
2     6     0     0
3     2     7     3
4     3     4     1

Slice:    Var1  Var2  Var3
0     7     1     0

Dataframe with different indexes:
   Var1  Var2  Var3
a     7     1     0
b     9     1     9
c     6     0     0
d     2     7     3
e     3     4     1

Slice with new indexes:
   Var1  Var2  Var3
a     7     1     0
b     9     1     9
c     6     0     0

After removing "a" row:
   Var1  Var2  Var3
b     9     1     9
c     6     0     0
d     2     7     3
e     3     4     1

##### Locating Variables w/ Labels

In [19]:
# When locating a variable, it's crucial to not make any mistakes. We often use "iloc()" method to locate them.

import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randint(1, 30, size = (10, 3)), columns = ["var1" ,"var2", "var3"])
print("Dataframe:", df, sep = "\n")

# The "loc()" function is "label based data selecting method" which means that we have to pass the name of the row or column which we want to select. 
# ( ! ) This method "includes" the last element of the range passed in it, unlike iloc().
print("\nWith loc():", df.loc[0:3], sep = "\n")         # Slicing through label "0" to label "3" (3 is included).

# The "iloc()"" function is an "indexed-based selecting method" which means that we have to pass an integer index in the method to select a specific row/column.
print("\nWith iloc():", df.iloc[0:3], sep = "\n")        # Slicing through index "0" to index "3" (3 is not included).

print(df.iloc[0, 0])
print(df.iloc[:3, :2])

print("\nloc() Example:", df.loc[0:3, "var3"], sep = "\n")          # From "var3", locate [0:3] indexes.

Dataframe:
   var1  var2  var3
0    16    21     4
1    10    24    24
2     6    19     6
3    27     3    26
4    25    10    15
5    12    28    23
6    25    11     5
7    22    21     2
8     4    13    14
9    18    15    18

With loc():
   var1  var2  var3
0    16    21     4
1    10    24    24
2     6    19     6
3    27     3    26

With iloc():
   var1  var2  var3
0    16    21     4
1    10    24    24
2     6    19     6
16
   var1  var2
0    16    21
1    10    24
2     6    19

loc() Example:
0     4
1    24
2     6
3    26
Name: var3, dtype: int32

##### Operations with Conditions in a Dataframe

In [32]:
# We can define a condition to execute the operations.
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randint(1, 30, size = (10, 3)), columns = ["var1" ,"var2", "var3"])
print("Dataframe:", df, sep = "\n")

print("\nChoosing \"var1\" column:", df["var1"], sep = "\n")

print("\nConditions on columns (\"var2\"):", df[0:2]["var2"], sep = "\n")

# We can use "fancy indexing" here if we want to.
print("\nConditions on columns (\"var2\" and \"var3\"):", df[0:2][["var2", "var3"]], sep = "\n")

# We can define any conditions with logical operators.
print("\nDefining a condition (for \"var1\" values which are greater than 15):", df[df.var1 > 15]["var1"], sep = "\n")

# We can use "loc()" with the conditions if needed.
print("\nUsing loc() with conditions:", df.loc[(df.var1 > 15), ["var1", "var2"]], sep = "\n")

Dataframe:
   var1  var2  var3
0    19    26     2
1    21     9    19
2    27    23    19
3    29    29    10
4     1     4    17
5    22    21    16
6    14    20    20
7    11    14     8
8    24     8     6
9    11    28     2

Choosing "var1" column:
0    19
1    21
2    27
3    29
4     1
5    22
6    14
7    11
8    24
9    11
Name: var1, dtype: int32

Conditions on columns ("var2"):
0    26
1     9
Name: var2, dtype: int32

Conditions on columns ("var2" and "var3"):
   var2  var3
0    26     2
1     9    19

Defining a condition (for "var1" values which are greater than 15):
0    19
1    21
2    27
3    29
5    22
8    24
Name: var1, dtype: int32

Using loc() with conditions:
   var1  var2
0    19    26
1    21     9
2    27    23
3    29    29
5    22    21
8    24     8

##### Dataframe Joining/Combining

In [12]:
# In some occasions, there are multiple dataframes used for the project. Combining dataframes is a quite important task.
import numpy as np
import pandas as pd

df_1 = pd.DataFrame(np.random.randint(1, 30, size = (10, 3)), columns = ["var1" ,"var2", "var3"])
print("Dataframe 1:", df_1, sep = "\n")

df_2 = df_1 + 100
print("\nDataframe 2:", df_2, sep = "\n")

# We can combine two dataframes with "concat()" method.
pd.concat([df_1, df_2], axis = 0)

# ( ! ) After the operation, indexes does not change and thus cause a problem. We need to check the documentation for solving this problem.
help(pd.concat)
print("\nDataframe after the concatenation:", pd.concat([df_1, df_2], ignore_index = True), sep = "\n")            # With "ignore_index" parameter, we succesfully changed the improper indexes.

Dataframe 1:
   var1  var2  var3
0     5    22    15
1    17     5     4
2    18     5    29
3     1    29     5
4    16    23    11
5    25     4     9
6    16    25     2
7    25     3     2
8    19     3    17
9    21    19    22

Dataframe 2:
   var1  var2  var3
0   105   122   115
1   117   105   104
2   118   105   129
3   101   129   105
4   116   123   111
5   125   104   109
6   116   125   102
7   125   103   102
8   119   103   117
9   121   119   122
Help on function concat in module pandas.core.reshape.concat:

concat(objs: 'Iterable[NDFrame] | Mapping[HashableT, NDFrame]', axis: 'Axis' = 0, join: 'str' = 'outer', ignore_index: 'bool' = False, keys=None, levels=None, names=None, verify_integrity: 'bool' = False, sort: 'bool' = False, copy: 'bool' = True) -> 'DataFrame | Series'
    Concatenate pandas objects along a particular axis.

    Allows optional set logic along the other axes.

    Can also add a layer of hierarchical indexing on the concatenation axis,
    which may be useful if the labels are the same (or overlapping) on
    the passed axis number.

    Parameters
    ----------
    objs : a sequence or mapping of Series or DataFrame objects
        If a mapping is passed, the sorted keys will be used as the `keys`
        argument, unless it is passed, in which case the values will be
        selected (see below). Any None objects will be dropped silently unless
        they are all None in which case a ValueError will be raised.
    axis : {0/'index', 1/'columns'}, default 0
        The axis to concatenate along.
    join : {'inner', 'outer'}, default 'outer'
        How to handle indexes on other axis (or axes).
    ignore_index : bool, default False
        If True, do not use the index values along the concatenation axis. The
        resulting axis will be labeled 0, ..., n - 1. This is useful if you are
        concatenating objects where the concatenation axis does not have
        meaningful indexing information. Note the index values on the other
        axes are still respected in the join.
    keys : sequence, default None
        If multiple levels passed, should contain tuples. Construct
        hierarchical index using the passed keys as the outermost level.
    levels : list of sequences, default None
        Specific levels (unique values) to use for constructing a
        MultiIndex. Otherwise they will be inferred from the keys.
    names : list, default None
        Names for the levels in the resulting hierarchical index.
    verify_integrity : bool, default False
        Check whether the new concatenated axis contains duplicates. This can
        be very expensive relative to the actual data concatenation.
    sort : bool, default False
        Sort non-concatenation axis if it is not already aligned when `join`
        is 'outer'.
        This has no effect when ``join='inner'``, which already preserves
        the order of the non-concatenation axis.

        .. versionchanged:: 1.0.0

           Changed to not sort by default.

    copy : bool, default True
        If False, do not copy data unnecessarily.

    Returns
    -------
    object, type of objs
        When concatenating all ``Series`` along the index (axis=0), a
        ``Series`` is returned. When ``objs`` contains at least one
        ``DataFrame``, a ``DataFrame`` is returned. When concatenating along
        the columns (axis=1), a ``DataFrame`` is returned.

    See Also
    --------
    DataFrame.join : Join DataFrames using indexes.
    DataFrame.merge : Merge DataFrames by indexes or columns.

    Notes
    -----
    The keys, levels, and names arguments are all optional.

    A walkthrough of how this method fits in with other tools for combining
    pandas objects can be found `here
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html>`__.

    It is not recommended to build DataFrames by adding single rows in a
    for loop. Build a list of rows and make a DataFrame in a single concat.

    Examples
    --------
    Combine two ``Series``.

    >>> s1 = pd.Series(['a', 'b'])
    >>> s2 = pd.Series(['c', 'd'])
    >>> pd.concat([s1, s2])
    0    a
    1    b
    0    c
    1    d
    dtype: object

    Clear the existing index and reset it in the result
    by setting the ``ignore_index`` option to ``True``.

    >>> pd.concat([s1, s2], ignore_index=True)
    0    a
    1    b
    2    c
    3    d
    dtype: object

    Add a hierarchical index at the outermost level of
    the data with the ``keys`` option.

    >>> pd.concat([s1, s2], keys=['s1', 's2'])
    s1  0    a
        1    b
    s2  0    c
        1    d
    dtype: object

    Label the index keys you create with the ``names`` option.

    >>> pd.concat([s1, s2], keys=['s1', 's2'],
    ...           names=['Series name', 'Row ID'])
    Series name  Row ID
    s1           0         a
                 1         b
    s2           0         c
                 1         d
    dtype: object

    Combine two ``DataFrame`` objects with identical columns.

    >>> df1 = pd.DataFrame([['a', 1], ['b', 2]],
    ...                    columns=['letter', 'number'])
    >>> df1
      letter  number
    0      a       1
    1      b       2
    >>> df2 = pd.DataFrame([['c', 3], ['d', 4]],
    ...                    columns=['letter', 'number'])
    >>> df2
      letter  number
    0      c       3
    1      d       4
    >>> pd.concat([df1, df2])
      letter  number
    0      a       1
    1      b       2
    0      c       3
    1      d       4

    Combine ``DataFrame`` objects with overlapping columns
    and return everything. Columns outside the intersection will
    be filled with ``NaN`` values.

    >>> df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
    ...                    columns=['letter', 'number', 'animal'])
    >>> df3
      letter  number animal
    0      c       3    cat
    1      d       4    dog
    >>> pd.concat([df1, df3], sort=False)
      letter  number animal
    0      a       1    NaN
    1      b       2    NaN
    0      c       3    cat
    1      d       4    dog

    Combine ``DataFrame`` objects with overlapping columns
    and return only those that are shared by passing ``inner`` to
    the ``join`` keyword argument.

    >>> pd.concat([df1, df3], join="inner")
      letter  number
    0      a       1
    1      b       2
    0      c       3
    1      d       4

    Combine ``DataFrame`` objects horizontally along the x axis by
    passing in ``axis=1``.

    >>> df4 = pd.DataFrame([['bird', 'polly'], ['monkey', 'george']],
    ...                    columns=['animal', 'name'])
    >>> pd.concat([df1, df4], axis=1)
      letter  number  animal    name
    0      a       1    bird   polly
    1      b       2  monkey  george

    Prevent the result from including duplicate index values with the
    ``verify_integrity`` option.

    >>> df5 = pd.DataFrame([1], index=['a'])
    >>> df5
       0
    a  1
    >>> df6 = pd.DataFrame([2], index=['a'])
    >>> df6
       0
    a  2
    >>> pd.concat([df5, df6], verify_integrity=True)
    Traceback (most recent call last):
        ...
    ValueError: Indexes have overlapping values: ['a']

    Append a single row to the end of a ``DataFrame`` object.

    >>> df7 = pd.DataFrame({'a': 1, 'b': 2}, index=[0])
    >>> df7
        a   b
    0   1   2
    >>> new_row = pd.Series({'a': 3, 'b': 4})
    >>> new_row
    a    3
    b    4
    dtype: int64
    >>> pd.concat([df7, new_row.to_frame().T], ignore_index=True)
        a   b
    0   1   2
    1   3   4


Dataframe after the concatenation:
    var1  var2  var3
0      5    22    15
1     17     5     4
2     18     5    29
3      1    29     5
4     16    23    11
5     25     4     9
6     16    25     2
7     25     3     2
8     19     3    17
9     21    19    22
10   105   122   115
11   117   105   104
12   118   105   129
13   101   129   105
14   116   123   111
15   125   104   109
16   116   125   102
17   125   103   102
18   119   103   117
19   121   119   122

##### High-Level Dataframe Merging Operations

In [7]:
# In some occasions, we need to find a way to specialize dataframe joining such as merging.
import pandas as pd

df1 = pd.DataFrame({
    "Employees": ["Ali", "Veli", "Ayşe", "Fatma"], 
    "Group": ["Accountancy", "Engineering", "Engineering", "Human Resources"]
})

df2 = pd.DataFrame({
    "Employees": ["Ayşe", "Ali", "Veli", "Fatma"],
    "Employment": [2010, 2009, 2014, 2019]
})

display(df1)
display(df2)

df_merged = pd.merge(df1, df2, how = "left", on = "Employees")
display(df_merged)

  Employees            Group
0       Ali      Accountancy
1      Veli      Engineering
2      Ayşe      Engineering
3     Fatma  Human Resources

  Employees  Employment
0      Ayşe        2010
1       Ali        2009
2      Veli        2014
3     Fatma        2019

  Employees            Group  Employment
0       Ali      Accountancy        2009
1      Veli      Engineering        2014
2      Ayşe      Engineering        2010
3     Fatma  Human Resources        2019

##### Aggregation and Grouping in a Dataframe

In [2]:
# Once data cleaning is done, we use functions which helps us to understand the data's characteristic properties.
import seaborn as sns

df_planets = sns.load_dataset("planets")
display(df_planets.head())
print("Shape: ", df_planets.shape)

# The most important aggregation functions/methods are:
# count(), first(), last(), mean(), median(), min(), max(), std(), var() and sum().

display(df_planets.describe().T)          # ".describe()" method contains "count(), mean(), std(), min() and max()" methods.

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

Shape:  (1035, 6)

,count,mean,std,min,25%,50%,75%,max
number,1035.0,1.785507,1.240976,1.000000,1.00000,1.0000,2.000,7.0
orbital_period,992.0,2002.917596,26014.728304,0.090706,5.44254,39.9795,526.005,730000.0
mass,513.0,2.638161,3.818617,0.003600,0.22900,1.2600,3.040,25.0
distance,808.0,264.069282,733.116493,1.350000,32.56000,55.2500,178.500,8500.0
year,1035.0,2009.070531,3.972567,1989.000000,2007.00000,2010.0000,2012.000,2014.0

##### Grouping Operations in Dataframes

In [14]:
import pandas as pd

df = pd.DataFrame({"Group": ["A", "B", "C", "A", "B", "C"], "Data": [10, 11, 52, 23, 43, 55]})
display(df, df.columns)

# Grouping is an operation which locates the categorical variables and catches them to be able to make operations.

display(df.groupby("Group"))            # Output   >>   <pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000012545875EA0>

# In the previous line of code, python caught the categorical variables included in column "Group". With this process, we can execute any intended operations.

df.groupby("Group").mean()
df.groupby("Group").std()
df.groupby("Group").sum()

import seaborn as sns

df_planets = sns.load_dataset("planets")
display(df_planets.head())

# Let's say we want to catch the "method" categorical variable.
df_planets.groupby("method")

# We can't do any operations with just "method" categorical variable. We need to have some sort of data that corresponds to it.

df_planets.groupby("method")["orbital_period"]          # Output   >>   <pandas.core.groupby.generic.SeriesGroupBy object at 0x0000022C5ED5C970>

# With this operation done, we can execute any operation to the gouped dataset.
display(df_planets.groupby("method")["orbital_period"].mean())

display(df_planets.groupby("method")["distance"].mean())

display(df_planets.groupby("method")["orbital_period"].describe())

  Group  Data
0     A    10
1     B    11
2     C    52
3     A    23
4     B    43
5     C    55

Index(['Group', 'Data'], dtype='object')

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

method
Astrometry                         17.875000
Eclipse Timing Variations         315.360000
Imaging                            67.715937
Microlensing                     4144.000000
Orbital Brightness Modulation    1180.000000
Pulsar Timing                    1200.000000
Pulsation Timing Variations              NaN
Radial Velocity                    51.600208
Transit                           599.298080
Transit Timing Variations        1104.333333
Name: distance, dtype: float64

,count,mean,std,min,25%,50%,75%,max
method,,,,,,,,
Astrometry,2.0,631.180000,544.217663,246.360000,438.770000,631.180000,823.590000,1016.000000
Eclipse Timing Variations,9.0,4751.644444,2499.130945,1916.250000,2900.000000,4343.500000,5767.000000,10220.000000
Imaging,12.0,118247.737500,213978.177277,4639.150000,8343.900000,27500.000000,94250.000000,730000.000000
Microlensing,7.0,3153.571429,1113.166333,1825.000000,2375.000000,3300.000000,3550.000000,5100.000000
Orbital Brightness Modulation,3.0,0.709307,0.725493,0.240104,0.291496,0.342887,0.943908,1.544929
Pulsar Timing,5.0,7343.021201,16313.265573,0.090706,25.262000,66.541900,98.211400,36525.000000
Pulsation Timing Variations,1.0,1170.000000,NaN,1170.000000,1170.000000,1170.000000,1170.000000,1170.000000
Radial Velocity,553.0,823.354680,1454.926210,0.736540,38.021000,360.200000,982.000000,17337.500000
Transit,397.0,21.102073,46.185893,0.355000,3.160630,5.714932,16.145700,331.600590
Transit Timing Variations,3.0,79.783500,71.599884,22.339500,39.675250,57.011000,108.505500,160.000000

##### Advanced Grouping Operations (Aggregate, Filter, Transform, Apply)

In [19]:
import pandas as pd
import numpy as np

df = pd.DataFrame({"Groups": ["A", "B", "C", "A", "B", "C"], "Var1": [10, 23, 33, 22, 11, 99], "Var2": [100, 253, 333, 262, 111, 969]})
display(df)

  Groups  Var1  Var2
0      A    10   100
1      B    23   253
2      C    33   333
3      A    22   262
4      B    11   111
5      C    99   969

##### "aggregate( )"

In [21]:
# If we need to execute an operation which is not pre-defined for a dataframe, we should use "aggregate()".

display(df.groupby("Groups").aggregate(["min", np.median, max]))         # All the listed operations is executed for all the variables included in the categorical variable "Groups".

# ( ! ) We usually prefer to use double quotes ("") for default operations which is included in Python's default library.

# We can choose spesific operations for all the variables.

display(df.groupby("Groups").aggregate({"Var1": np.median, "Var2": min}))

       Var1            Var2
        min median max  min median  max
Groups
A        10   16.0  22  100  181.0  262
B        11   17.0  23  111  182.0  253
C        33   66.0  99  333  651.0  969

        Var1  Var2
Groups
A       16.0   100
B       17.0   111
C       66.0   333

##### "filter( )"

In [22]:
# In some occasions, we need to filter the data from a dataset. Most of the time, filtering is quite complex so because of that reason we define a function for filtering.

def filter_func(x):
    return x["Var1"].std() > 9

# With this method, we can filter any dataframe with more control over the filering.
df.groupby("Groups").filter(filter_func)

  Groups  Var1  Var2
2      C    33   333
5      C    99   969

##### "transform( )"

In [25]:
# We can transform any dataframe with the user-defined conditions (it's more practical to use if conditions are complex).
df_drop_str = df.iloc[:, 1:3]
# Get rid of the string categories. If don't, an error will be raised.
df_drop_str.transform(lambda x: (x - x.mean()) / x.std())

       Var1      Var2
0 -0.687871 -0.738461
1 -0.299074 -0.263736
2  0.000000 -0.015514
3 -0.328982 -0.235811
4 -0.657963 -0.704331
5  1.973890  1.957853

##### "apply( )"

In [31]:
# We use "apply()" to apply any operations to a dataframe. 
display(df_drop_str)
display(df_drop_str.apply(np.sum))
display(df_drop_str.apply(np.mean))

   Var1  Var2
0    10   100
1    23   253
2    33   333
3    22   262
4    11   111
5    99   969

Var1     198
Var2    2028
dtype: int64

Var1     33.0
Var2    338.0
dtype: float64

##### Pivot Tables

In [43]:
import pandas as pd
import seaborn as sns

df_titanic = sns.load_dataset("titanic")
display(df_titanic.head())

df_titanic.groupby("sex")["survived"].mean()

# Pivotting can be done by defining multiple groups and variables.

df_titanic.groupby(["sex", "class"])[["survived"]].aggregate("mean").unstack()

# Sme process can be done in a more practical way with "pivot_table"
display(df_titanic.pivot_table("survived", index = "sex", columns = "class"))

# We can create a categorical data and use "pivot_table" on it as well.
df_titanic.age.head()
age = pd.cut(df_titanic["age"], [0, 18, 90])
age.head(10)

display(df_titanic.pivot_table("survived", ["sex", age], "class"))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

class               First    Second     Third
sex    age
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

##### Processing/Reading an External Dataset

In [49]:
import pandas as pd

# Reading .csv and .txt files
csv = pd.read_csv("reading_data\ornekcsv.csv")
display(csv)            # Reading Error!

csv = pd.read_csv("reading_data\ornekcsv.csv", sep = ";")
display(csv)            # Corrected

txt = pd.read_csv("reading_data\duz_metin.txt")
display(txt)            # Seperation done by " ". Reading is done correctly.

# Reading .xlsx files

xlsx = pd.read_excel("reading_data\ornekx.xlsx")
display(xlsx)

       a;b;c
0    78;12;1
1    78;12;2
2   78;324;3
3      7;2;4
4    88;23;5
5       6;2;
6    56;11;6
7     7;12;7
8    56;21;7
9    346;2;8
10     5;1;8
11  456;21;8
12   3;12;88

      a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

    1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2
6   8 2
7   9 2
8  10 2

      a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

#### Seaborn

In [ ]:
# In this part of he notebook, the index is as follows:
    # Data Visualization
    # The First Look to the Data
    # Categorical Variables
    # Continuous Variables
    # Scatter Plots
    # Correlation Plots
    # Line Plots
    # Time - Domain Plots
    # Analytical Analysis of Variables

##### Analysing The Data

In [ ]:
# Analysing the data as a "whole" is the first step to understand the data's structure. Representing the data/summarizing the data helps the programmer to see "the big picture".

##### Data Visualization

In [ ]:
# Data visualization is a crucial skill to master. Mostly, it's quite hard to understand the data at first. Visualiazing helps the programmer to understand the behaviour of the dataset and makes it easier to solve the problem.

# Modules which is frequently used in data visualization are:
    # Matplotlib
    # Pandas
    # Seaborn
    # ggplot (integrated from R)
    # Bokeh (Interacive Graphs)
    # Plot.ly

##### The First Look to the Data

In [2]:
import seaborn as sns

planets = sns.load_dataset("planets")
planets.head()

# What is behind of this data? What is it's story?

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [4]:
# The first tep is to actually copy the dataset.
df = planets.copy()
df.head()

       method  number  orbital_period  mass  distance  year
1030  Transit       1        3.941507   NaN     172.0  2006
1031  Transit       1        2.615864   NaN     148.0  2007
1032  Transit       1        3.191524   NaN     174.0  2007
1033  Transit       1        4.125083   NaN     293.0  2008
1034  Transit       1        4.187757   NaN     260.0  2008

In [5]:
# We need to learn about the dataset's properties.
df.info()           # Dtype: object   >>   categorical variable

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          1035 non-null   object
 1   number          1035 non-null   int64
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB

In [6]:
df.dtypes

method             object
number              int64
orbital_period    float64
mass              float64
distance          float64
year                int64
dtype: object

In [11]:
# In some occasions, we need to change the data type "object" to "categorical variable".

import pandas as pd

df.method = pd.Categorical(df.method)
df.dtypes

method            category
number               int64
orbital_period     float64
mass               float64
distance           float64
year                 int64
dtype: object

##### Potrayal of the Dataset

In [19]:
import seaborn as sns

planets = sns.load_dataset("planets")

df = planets.copy()
display(df.head())
print(df.shape, df.columns, sep = "\n")

display(df.describe().T)            # "Categorical variables" and "NaNs" are ignored.

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

(1035, 6)
Index(['method', 'number', 'orbital_period', 'mass', 'distance', 'year'], dtype='object')

,count,mean,std,min,25%,50%,75%,max
number,1035.0,1.785507,1.240976,1.000000,1.00000,1.0000,2.000,7.0
orbital_period,992.0,2002.917596,26014.728304,0.090706,5.44254,39.9795,526.005,730000.0
mass,513.0,2.638161,3.818617,0.003600,0.22900,1.2600,3.040,25.0
distance,808.0,264.069282,733.116493,1.350000,32.56000,55.2500,178.500,8500.0
year,1035.0,2009.070531,3.972567,1989.000000,2007.00000,2010.0000,2012.000,2014.0